export const hireallCustomFieldNames = {
  crockery: [
    "Case Size",
    "Colour",
    "Material",
    "Suitable For",
    "Dimensions / Diameter <!-- must be supplied in centimeters and inches. Format cm/inch. -->",
    "Dishwasher Safe",
    "Microwave Safe",
    "Oven Safe",
  ],
  tables: [
    "Case Size",
    "Colour",
    "Table top colour",
    "Leg colour",
    "Material",
    "Dimensions",
    "Suitable for",
    "Seats",
  ],
  chairs: [
    "Seat Height",
    "Material",
    "Colour",
    "Stackable / Foldable",
    "Usage <!-- indoor/outdoor -->",
  ],
  glassware: [
    "Case Size",
    "Colour",
    "Material",
    "Suitable For",
    "Capacity <!-- must be supplied in centilitres and fluid ounces. Format cl/oz. -->",
    "Dishwasher Safe",
  ],
  cutlery: [
    "Suitability",
    "Dishwasher Safe",
    "Colour",
    "Material",
    "Case size",
    "Made in",
    "Handle material",
    "Pack Size",
  ],
  furniture: [
    "Material",
    "Colour",
    "Stackable / Foldable",
    "Usage",
    "Seat Height",
    "Case size",
    "Dimensions",
    "Cushion",
    "Seats",
    "Frame material",
    "Sofa frame material",
  ],
  tableService: [
    "Pack Size",
    "Colour",
    "Dishwasher safe",
    "Size",
    "Capacity",
    "Case size",
    "Suitable for",
    "Dishwasher Safe",
    "Material",
    "Suitable For",
    "Dimensions / Diameter",
  ],
  outdoor: [
    "Case size",
    "Fuel type",
    "Power",
    "Unit dimensions",
    "Griddle dimensions",
    "Storage Requirements",
    "Capacity",
    "Suitable for",
    "Pack size",
    "Suitability",
    "Dishwasher Safe",
    "Colour",
    "Material",
    "Grill dimensions",
    "Weight",
    "Total Heat Input",
    "Legs",
    "Assembly",
    "Bag size",
    "Usage",
    "Fuel",
    "Metal",
    "Foldable legs",
    "Dimensions <!-- Length, Width, Height please. Or if it's round then Diameter first then Height. Seat Height would appear last -->",
    "Power Requirement",
  ],
  cateringEquipment: [
    "Case Size",
    "Fuel Requirement",
    "Suitable for",
    "Material",
    "Dishwasher Safe",
    "Pack size",
    "Colour",
    "Case size",
    "Fuel type",
    "Power",
    "Unit dimensions",
    "Griddle dimensions",
    "Compatibility",
    "Capacity",
    "Measurements",
    "Pack Size",
    "Power Requirement",
    "Number of rings",
    "Number of Shelves",
    "Shelf size",
    "Finish",
    "Suitability",
    "Stackable",
    "Will fit",
    "Insulation Type",
    "Access",
    "Plumbing",
    "Water Fill",
    "Waste",
    "Storage Requirements",
    "Power requirement",
    "Power consumption",
    "Hot Cupboard Capacity",
    "Number of wells",
    "Legs",
    "Suitable For",
    "Number of Baskets",
    "Basket Capacity",
    "Model Type",
    "Shelf Size",
    "Power Supply",
    "Power Consumption",
    "No of Shelves",
    "Temp Range",
    "Burn Time",
    "Warning",
    "Number of Lamps",
    "On Wheels",
    "Grill size",
    "Grill dimensions",
    "Weight",
    "Total Heat Input",
    "Assembly",
    "Safety",
    "Bag size",
    "Usage",
    "Number of Sinks",
    "Waste Requirement",
    "Water Connection",
    "Fuel",
    "Metal",
    "Diameter",
    "Suitable Plates",
    "Number of Lights",
    "Number of Rings",
    "Foldable legs",
    "Dimensions",
    "Power requirements",
    "Water Capacity",
    "Model",
    "Number of Tiers",
    "Hotcupboard Capacity",
    "Water / Waste",
    "Cooking area",
    "Cleanup",
    "Number of racks",
    "Wheels",
    "Water Supply",
    "Coverage",
    "Bulb Type",
    "Mounting",
    "Length",
    "Storage",
    "Energy Efficiency",
  ],
  buffetWare: [
      "Dishwasher Safe",
      "Colour",
      "Material",
      "Case size",
      "**Please Note**",
      "Fits",
      "Shape",
      "Capacity",
      "Suitable For",
      "Dishwasher safe",
      "Microwave Safe",
      "Dimensions",
      "Diameter",
      "Number of Branches",
      "Candles Included",
      "Oven Safe",
      "Qty per roll",
      "Use",
      "Qty on roll",
      "Finish",
      "Candle included",
      "Table Numbers Included",
      "Suitable for microwave",
      "Made in",
      "Handle material",
      "Tempered Glass",
      "Stackable"
    ]
};
