export const hireallCustomFieldNames = {
  crockery: [
    "Case Size",
    "Colour",
    "Material",
    "Suitable For",
    "Dimensions / Diameter <!-- must be supplied in centimeters and inches. Format cm/inch. -->",
    "Dishwasher Safe",
    "Microwave Safe",
    "Oven Safe",
  ],
  tables: [
    "Case Size",
    "Colour",
    "Table top colour",
    "Leg colour",
    "Material",
    "Dimensions",
    "Suitable for",
    "Seats",
  ],
  chairs: [
    "Seat Height",
    "Material",
    "Colour",
    "Stackable / Foldable",
    "Usage <!-- indoor/outdoor -->",
  ],
  glassware: [
    "Case Size",
    "Colour",
    "Material",
    "Suitable For",
    "Capacity <!-- must be supplied in centilitres and fluid ounces. Format cl/oz. -->",
    "Dishwasher Safe",
  ],
  cutlery: [
      "Suitability",
      "Dishwasher Safe",
      "Colour",
      "Material",
      "Case size",
      "Made in",
      "Handle material",
      "Pack Size"
    ],
    furniture:  [
      "Material",
      "Colour",
      "Stackable / Foldable",
      "Usage",
      "Seat Height",
      "Case size",
      "Dimensions",
      "Cushion",
      "Seats",
      "Frame material",
      "Sofa frame material"
    ],
    tableService: [
      "Pack Size",
      "Colour",
      "Dishwasher safe",
      "Size",
      "Capacity",
      "Case size",
      "Suitable for",
      "Dishwasher Safe",
      "Material",
      "Suitable For",
      "Dimensions / Diameter",
    ],
    outdoor: [
      "Case size",
      "Fuel type",
      "Power",
      "Unit dimensions",
      "Griddle dimensions",
      "Storage Requirements",
      "Capacity",
      "Suitable for",
      "Pack size",
      "Suitability",
      "Dishwasher Safe",
      "Colour",
      "Material",
      "Grill dimensions",
      "Weight",
      "Total Heat Input",
      "Legs",
      "Assembly",
      "Bag size",
      "Usage",
      "Fuel",
      "Metal",
      "Foldable legs",
      "Dimensions <!-- Length, Width, Height please. Or if it's round then Diameter first then Height. Seat Height would appear last -->",
      "Power Requirement",
    ]
};