import { getProductBySku } from "../../functions/products/getProductBySKU";
import { updateProduct } from "../../functions/products/updateProduct";

const data = [
  {
    sku: "9661",
    name: "Actyva Color Brilliante Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9078",
    name: "Alfaparf Anti Breakage Fluid Buy 2 Get 1 Free",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14763",
    name: "Alfaparf Bundle For Curly Hair With a Sensitive Scalp",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14758",
    name: "Alfaparf Bundle For Dull & Thin Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14760",
    name: "Alfaparf Bundle For Fine Hair With Dry Ends",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14759",
    name: "Alfaparf Bundle For Hair Loss/PostPartum Hair Loss",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14761",
    name: "Alfaparf Bundle For Hair That Lacks Shine & Gloss",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14762",
    name: "Alfaparf Bundle For Hair That Lacks Volume",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14764",
    name: "Alfaparf Bundle For Hair That's Rebellious, Dry & Frizzy",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9077",
    name: "Alfaparf Crystalli Liquidi 30ml Buy 2 Get 1 Free",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9084",
    name: "Alfaparf Curls Defining Cream Buy 2 Get 1 Free",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9804",
    name: "Alfaparf Curls Hydration Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9805",
    name: "Alfaparf Curls Leave-In Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9803",
    name: "Alfaparf Curls Shampoo and Co Wash Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13038",
    name: "Alfaparf Goodbye Dry Bundle - Moisture",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9802",
    name: "Alfaparf Rebalance Oily Scalp Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9806",
    name: "Alfaparf Reconstruction Leave-In Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11076",
    name: "Alfaparf Semi Di Lino - Blonde Anti-Yellow Trio",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11074",
    name: "Alfaparf Semi Di Lino - Blonde Shampoo & Conditioner Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11075",
    name: "Alfaparf Semi Di Lino - Brunette Shampoo & Conditioner Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10365a",
    name: "Alfaparf Semi Di Lino - Curls Gift Set with Free Cristalli Liquidi 30ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10363a",
    name: "Alfaparf Semi Di Lino - Diamond Gift Set with Free Cristalli Liquidi 15ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10362a",
    name: "Alfaparf Semi Di Lino - Moisture Gift Set with Free Cristalli Liquidi 15ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10361a",
    name: "Alfaparf Semi Di Lino - Reconstruction Gift Set with Free Cristalli Liquidi 30ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10364b",
    name: "Alfaparf Semi Di Lino - Volume Gift Set with Alfaparf Semi Di Lino Volumizing Spray 125ml ",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10364a",
    name: "Alfaparf Semi Di Lino - Volume Gift Set with Free Cristalli Liquidi 30ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8756",
    name: "Alfaparf Semi Di Lino Curls Gift Set",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14137",
    name: "Alfaparf Semi Di Lino Density Thickening Bundle - The Full Routine",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14136",
    name: "Alfaparf Semi Di Lino Density Thickening Shampoo & Conditioner Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9954",
    name: "Alfaparf Semi Di Lino Diamond - Ultimate Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8760",
    name: "Alfaparf Semi Di Lino Diamond Gift Set",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10377",
    name: "Alfaparf Semi Di Lino Moisture - Hair Care Trio",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9955",
    name: "Alfaparf Semi Di Lino Moisture - Ultimate Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14408",
    name: "Alfaparf Semi Di Lino Moisture Beauty Box with FREE Alfaparf Semi Di Lino Cristalli Liquidi 15ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8759",
    name: "Alfaparf Semi Di Lino Moisture Gift Set",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9956",
    name: "Alfaparf Semi Di Lino Reconstruction - Ultimate Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8758",
    name: "Alfaparf Semi Di Lino Reconstruction Gift Set",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9087",
    name: "Alfaparf Semi Di Lino Scalp RENEW Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9229",
    name: "Alfaparf Semi Di Lino Scalp RENEW Energizing Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9907",
    name: "Alfaparf Semi Di Lino Smooth - Essential Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9908",
    name: "Alfaparf Semi Di Lino Smooth - Treatment Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9906",
    name: "Alfaparf Semi Di Lino Smooth - Ultimate Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12757",
    name: "Alfaparf Semi Di Lino Smooth Deluxe Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12756",
    name: "Alfaparf Semi Di Lino Smooth Extra Value Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12758",
    name: "Alfaparf Semi Di Lino Smooth Holiday Gift Set PLUS Free Cristalli Liquidi 15ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8757",
    name: "Alfaparf Semi Di Lino Volume Gift Set",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9801",
    name: "Alfaparf Sensitive Skin Relief Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13040",
    name: "Alfaparf The Scalp Rescue Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9085",
    name: "Alfaparf Volumizing Spray Buy 2 Get 1 Free",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12341",
    name: "Bye-Bye Dry Scalp Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12338",
    name: "Calm Your Scalp Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11863",
    name: "Cerave Cleanser Large Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13037",
    name: "Color WOW Colour Rescue Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "7822",
    name: "Color Wow Dream Clean Regime Bundle - Damaged Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "7823",
    name: "Color Wow Dream Clean Regime bundle - For Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8787",
    name: "Color WOW Dream Clean Shampoo & Conditioner (Normal to Thick) Duo Pack",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11050",
    name: "Color Wow Dream Coat & Dream Filter 200ml Plus Free Travel Duo's",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14027",
    name: "Color WOW Dream Coat & Dream Filter Bundle - TRAVEL SIZE",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11497",
    name: "Color Wow Dream Coat & Money Masque Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14029",
    name: "Color Wow Dream Coat & Money Masque Bundle - TRAVEL SIZE",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11049",
    name: "Color Wow Dream Coat 200ml plus FREE Ultimate Travel Duo's",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10902",
    name: "Color Wow Dream Coat 200ml with FREE Dream Filter 50ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11498",
    name: "Color Wow Dream Filter & Money Masque Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14028",
    name: "Color Wow Dream Filter & Money Masque Bundle - TRAVEL SIZE",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11048",
    name: "Color Wow Dream Filter 200ml plus FREE Ultimate Travel Duo's",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10903",
    name: "Color Wow Dream Filter 200ml with FREE Dream Filter 50ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "7820",
    name: "Color Wow Dream Smooth Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14030",
    name: "Color WOW Extra Strength Dream Coat & Dream Filter Bundle - TRAVEL SIZE",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9230",
    name: "Color Wow Heroes Collection with DETOX bag",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11499",
    name: "Color Wow Shampoo, Conditioner & Money Masque Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11047",
    name: "Color Wow Style Ultimate Travel Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14031",
    name: "Color WOW Travel Sized Treats Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11500",
    name: "Color Wow Ultimate Styling Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10139",
    name: "Eleven Keep My Blonde - Collection",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12340",
    name: "Greasy No More Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8841",
    name: "Joico - K-Pak Shampoo & Conditioner Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10140",
    name: "Joico Blonde Life Brightening - Ultimate Collection",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9231",
    name: "Joico Blonde Life Collection with FREE Mask",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12123",
    name: "Joico Blonde Life Shampoo & Conditioner Gift Set 2022",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10141",
    name: "Joico Blonde Life Violet - Ultimate Collection",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10569",
    name: "Joico Colorful Anti-Fade Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12124",
    name: "Joico Colorful Shampoo & Conditioner Gift Set 2022",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10210",
    name: "Joico Colour Therapy Ultimate Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10303",
    name: "Joico Defy Damage Protective Shield & Sleepover Foil",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12125",
    name: "Joico Defy Damage Shampoo & Conditioner Gift Set 2022",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9656",
    name: "Joico Defy Damage Sleepover Overnight Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12126",
    name: "Joico Hydrasplash Shampoo & Conditioner Gift Set 2022",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10209",
    name: "Joico Hydrasplash Ultimate Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10211",
    name: "Joico Joifull Ultimate Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12127",
    name: "Joico JoiFull Volume Shampoo & Conditioner Gift Set 2022",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "5397",
    name: "Kerastase Aura Botanica Shampoo & Conditioner Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12903",
    name: "Kerastase Aura Botanica Soin Fondamental Conditioner 200ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11170",
    name: "Kerastase Bain Force Architecte Refill Pouch & Refillable Bottle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13933",
    name: "Kérastase Blond Absolu - The Three Step Regime Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10142",
    name: "Kerastase Blond Absolu - Ultimate Collection",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11166",
    name: "Kerastase Blond Absolu Bain Lumière Refill Pouch & Refillable Bottle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14246",
    name: "Kérastase Blond Absolu Lumiere Shampoo, Conditioner and Masque Trio",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11862",
    name: "Kerastase Blond Absolu Neutralise and Condition Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14268",
    name: "Kérastase Blond Absolu Neutralise, Condition and Hydrate Trio",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14244",
    name: "Kérastase Blond Absolu Protect and Hydrate Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14290",
    name: "Kérastase Blond Absolu Routine for Blonde Hair & Scalp",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14289",
    name: "Kérastase Blond Absolu Routine for Cool-Toned Blonde Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14291",
    name: "Kérastase Blond Absolu Routine for Damaged Highlighted/Blonde Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14288",
    name: "Kérastase Blond Absolu Routine for Honey Blonde Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14230",
    name: "Kérastase Blond Absolu Shampoo, Conditioner and Oil Hair Routine for Lightened or Highlighted Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14234",
    name: "Kérastase Blond Absolu Shampoo, Conditioner and Treatment Hair Routine for Lightened or Highlighted Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11850",
    name: "Kerastase Blond Absolu Shine and Hydrating Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12904",
    name: "Kerastase Blond Absolu Shine And Hydrating Duo For Everyday Use",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14217",
    name: "Kérastase Blond Absolu Shine, Strength and Neutralising Trio",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14225",
    name: "Kérastase Blond Absolu Ultra Violet Shampoo, Masque and Conditioner Trio",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14245",
    name: "Kérastase Blond Absolu Ultraviolet Shampoo, Conditioner and Oil Trio for Brightening Blonde Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14267",
    name: "Kérastase Blond Absolu Ultraviolet Shampoo, Conditioner and Treatment Routine for Brightening Blonde Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11171",
    name: "Kerastase Chroma Absolu Bain Respect Riche Refill Pouch & Refillable Bottle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14203",
    name: "Kérastase Chroma Absolu Duo - Fine to Medium Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14216",
    name: "Kérastase Chroma Absolu Duo - Medium to Thick Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14254",
    name: "Kérastase Chroma Absolu Hydrate, Strengthen and Shine Trio",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14271",
    name: "Kérastase Chroma Absolu Nourish, Neutralise and Shine Trio",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14242",
    name: "Kérastase Chroma Absolu Trio - Fine to Medium Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14250",
    name: "Kérastase Chroma Absolu Trio - Medium to Thick Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14224",
    name: "Kérastase Chronologiste Youth Revitalising Bain Regenerant Shampoo 250ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14233",
    name: "Kérastase Coily Hair Duos Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14266",
    name: "Kérastase Coily Hair Heroes Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8966",
    name: "Kerastase Colour Protection Shampoo and Conditioner Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14256",
    name: "Kérastase Complete Care for Coily Hair Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14265",
    name: "Kérastase Complete Care For Very Curly Hair Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14237",
    name: "Kérastase Complete Care For Wavy To Curly Hair Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10194A",
    name: "Kerastase Curl Manifesto - Ultimate Collection",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10401",
    name: "Kerastase Curl Manifesto Coily Hair Routine",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10400",
    name: "Kerastase Curl Manifesto Very Curly Hair Routine",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10399",
    name: "Kerastase Curl Manifesto Wavy To Curly Hair Routine",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14257",
    name: "Kérastase Curl Nourishment Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14247",
    name: "Kérastase Curly Hair Heroes Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12905",
    name: "Kerastase Densifique Bain Densite (250ml) Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11855",
    name: "Kerastase Densifique Bain Densite 250ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12906",
    name: "Kerastase Densifique Bain Homme (250ml) Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11878",
    name: "Kerastase Densifique Bain Homme 250ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11870",
    name: "Kerastase Densifique Conditioner 200ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14272",
    name: "Kérastase Densifique Masque Densite 200ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14201",
    name: "Kérastase Densifique Shampoo and Conditioner Hair Duo Routine",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14251",
    name: "Kérastase Densifique Shampoo, Conditioner and Ultime Oil Hair Trio Routine",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14222",
    name: "Kérastase Discipline 3 Step Smoothing Anti-Frizz Routine",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12907",
    name: "Kerastase Discipline Bain Fluidealiste",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12908",
    name: "Kerastase Discipline Bain Fluidealiste (250ml) Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14221",
    name: "Kérastase Discipline Bain Fluidealiste Gentle 250ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14209",
    name: "Kérastase Discipline Bain Fluidealiste Gentle and Fondant Fluidealiste Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14235",
    name: "Kérastase Discipline Fondant Fluidealiste 200ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14262",
    name: "Kérastase Discipline Keratin Thermique Creme 150ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14255",
    name: "Kérastase Discipline Maskeratine 200ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8968",
    name: "Kerastase Discipline Shampoo and Conditioner Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14208",
    name: "Kérastase Elixir Ultime L'Original Elixir Ultime Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12910",
    name: "Kerastase Elixir Ultime L'Original Hair Oil Duo 100ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12911",
    name: "Kerastase Elixir Ultime Rose Hair Oil Duo 100ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14213",
    name: "Kérastase Extentioniste Everyday 3 Step Routine for Healthy-Looking Lengths",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14229",
    name: "Kérastase Extentioniste Regime for Healthy-Looking Lengths",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14205",
    name: "Kérastase Genesis Anti Hair-Fall Fortifying Serum 90ml with Travel Size Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14286",
    name: "Kérastase Genesis Anti-Fall Haircare Bundle For Dry, Weak Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14202",
    name: "Kérastase Genesis Anti-Hair Fall Duo for Normal/Oily Hair and Free Travel Size Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11167",
    name: "Kerastase Genesis Bain Hydra-Fortifiant Refill Pouch & Refillable Bottle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11168",
    name: "Kerastase Genesis Bain Nutri-Fortifiant Refill Pouch & Refillable Bottle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11857",
    name: "Kerastase Genesis Duo for Normal to Oily Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12912",
    name: "Kerastase Genesis Duo For Normal To Oily Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12913",
    name: "Kerastase Genesis Duo For Thick To Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11389",
    name: "Kerastase Genesis Homme Fortifying Collection",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11353",
    name: "Kerastase Genesis Homme Styling Collection",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11388",
    name: "Kerastase Genesis Homme Thickness Collection",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11350",
    name: "Kerastase Genesis Homme Ultimate Collection",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11872",
    name: "Kerastase Genesis Masque and Shampoo Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14287",
    name: "Kérastase Genesis Nourishing & Fortifying Regime Bundle For Dry, Weakened Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14204",
    name: "Kérastase Genesis Shampoo, Conditioner and Serum Hair Trio Routine",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14263",
    name: "Kérastase Masque Force Architecte 200ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14211",
    name: "Kérastase Masque Resistance Therapiste Elixir Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14138",
    name: "Kérastase Nutritive - The Four Step Routine Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12914",
    name: "Kerastase Nutritive Bain Satin Riche 250ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11169",
    name: "Kerastase Nutritive Bain Satin Riche Refill Pouch & Refillable Bottle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14249",
    name: "Kérastase Nutritive Daily Nourishing Regime for Fine-Medium Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14248",
    name: "Kérastase Nutritive Daily Nourishing Regime for Medium-Thick Very Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12915",
    name: "Kerastase Nutritive Lait Vital 200ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8967",
    name: "Kérastase Nutritive Nourish and Hydrate Duo for Medium/Thick Very Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14218",
    name: "Kérastase Nutritive Nourishing Essentials Bundle for Fine-Medium Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14232",
    name: "Kérastase Nutritive Nourishing Essentials Bundle for Medium-Thick Very Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14210",
    name: "Kérastase Nutritive Nourishment Boosters Duo for Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14260",
    name: "Kérastase Nutritive Root To Tip Hydrating Heroes Nourish and Smooth Bundle for Fine-Medium Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14259",
    name: "Kérastase Nutritive Root To Tip Hydrating Heroes Nourish and Smooth Bundle for Medium-Thick Very Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14521",
    name: "Kérastase Première -The Full Routine Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14493",
    name: "Kérastase Première Decalcifying Pre-Shampoo with Travel Size Shampoo for Damaged Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14494",
    name: "Kérastase Première Decalcifying Repairing Pre-Shampoo & Shampoo Duo for Damaged Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14495",
    name: "Kérastase Première Decalcifying Repairing Shampoo & Conditioner Duo for Damaged Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12917",
    name: "Kerastase Resistance Ciment Anti-Usure - Vita Ciment Advance (200ml) Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11876",
    name: "Kerastase Resistance Ciment Anti-Usure 200ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14219",
    name: "Kérastase Resistance Ciment Thermique 150ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14293",
    name: "Kérastase Resistance Damaged Hair Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14294",
    name: "Kérastase Résistance Extensioniste Routine Haircare Bundle for Damaged Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14214",
    name: "Kérastase Resistance Reconstructing 3 Step Regime",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8965",
    name: "Kérastase Resistance Strengthening Duo for Fine to Medium Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14215",
    name: "Kérastase Resistance Strengthening Trio For Fine to Medium Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14236",
    name: "Kérastase Resistance Therapiste Bain 250ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14261",
    name: "Kérastase Resistance Therapiste Masque 200ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12918",
    name: "Kerastase Resistance Therapiste Shampoo And Masque Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14220",
    name: "Kérastase Resistance Therapiste Shampoo, Masque and Serum Trio",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11875",
    name: "Kerastase Resistance Therapiste Soin 200ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11864",
    name: "Kerastase Resistance Therepiste Serum 30ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12919",
    name: "Kerastase Resistance Therepiste Serum Duo 30ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14243",
    name: "Kérastase Resistance Therepiste Serum Duo 30ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12920",
    name: "Kerastase Resistance Volumifique Bain (250ml) Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11869",
    name: "Kerastase Resistance Volumifique Bain 250ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13093",
    name: "Kerastase Soleil Travel Kit GWP",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11871",
    name: "Kerastase Specifique Bain Anti-Pelliculaire Shampoo 250ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14231",
    name: "Kérastase Specifique Bain Prévention Shampoo 250ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12921",
    name: "Kerastase Specifique Dermo-Calm Bain Vital Shampoo 250ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14264",
    name: "Kérastase Specifique Masque Hydra-Apaisant Conditioner 200ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14238",
    name: "Kérastase Specifique Stimuliste Hair Thickener 125ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14241",
    name: "Kérastase Symbiose 3 Step Anti-Dandruff System for Dry Scalps",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14258",
    name: "Kérastase Symbiose 3 Step Anti-Dandruff System for Oily Scalps",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12339",
    name: "Kerastase Symbiose Anti Dandruff Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14207",
    name: "Kérastase Symbiose Anti-Dandruff Cleanse and Condition Duo for Dry Scalps",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14212",
    name: "Kérastase Symbiose Anti-Dandruff Cleanse and Condition Duo for Oily Scalps",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14270",
    name: "Kérastase Symbiose Anti-Dandruff Cleanse and Nourish Duo for Dry Scalps",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14269",
    name: "Kérastase Symbiose Anti-Dandruff Cleanse and Nourish Duo for Oily Scalps",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14253",
    name: "Kérastase Symbiose Anti-Dandruff Cleanse and Treat Duo for Dry Scalps",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14252",
    name: "Kérastase Symbiose Anti-Dandruff Cleanse and Treat Duo for Oily Scalps",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14239",
    name: "Kérastase Symbiose Anti-Dandruff Exfoliate and Cleanse Duo for Dry Scalps",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14240",
    name: "Kérastase Symbiose Anti-Dandruff Exfoliate and Cleanse Duo for Oily Scalps",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14292",
    name: "Kérastase The Ultimate Heroes Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10123",
    name: "Kerastase Ultime Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14206",
    name: "Kérastase Very Curly Hair Duo Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13216",
    name: "L'Oréal Professionnel Absolut Repair Bundle - FREE 100ml Shampoo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13218",
    name: "L'Oréal Professionnel Absolut Repair Collection - FREE 100ml Shampoo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11798",
    name: "L'Oréal Professionnel Absolut Repair Golden With FREE Mask",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13219",
    name: "L'Oréal Professionnel Absolut Repair Shampoo 750ml + 100ml FREE",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13217",
    name: "L'Oréal Professionnel Absolut Repair Super Size Bundle - FREE 100ml Shampoo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11873",
    name: "L'Oréal Professionnel Blondifier Gloss Shampoo and Conditioner Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11868",
    name: "L'Oréal Professionnel Inforcer Shampoo and Conditioner Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13222",
    name: "L'Oreal Professionnel Metal Detox Collection + FREE 100ml Shampoo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13221",
    name: "L'Oreal Professionnel Metal Detox Duo + FREE 100ml Shampoo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13220",
    name: "L'Oreal Professionnel Metal Detox ULTIMATE Collection + FREE 100ml Shampoo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13224",
    name: "L'Oréal Professionnel Pro Longer Collection + 100ml Shampoo FREE",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11795",
    name: "L'Oréal Professionnel Pro Longer Duo With FREE Mask",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13223",
    name: "L'Oréal Professionnel Pro Longer Shampoo 1500ml + 100ml FREE",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14199",
    name: "L'Oréal Professionnel Pro Longer Shampoo, Conditioner and Cream Trio",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14196",
    name: "L'Oreal Professionnel Serie Expert Absolut Repair Molecular Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14195",
    name: "L'Oreal Professionnel Serie Expert Absolut Repair Molecular Trio",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14197",
    name: "L'Oréal Professionnel Serie Expert Absolut Repair Routine",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12922",
    name: "L'Oreal Professionnel Serie Expert Blondifier Gloss Shampoo And Conditioner Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12924",
    name: "L'Oreal Professionnel Serie Expert Inforcer Shampoo And Masque Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14198",
    name: "L'Oreal Professionnel Serie Expert Scalp Advanced Anti-Dandruff Shampoo and Hair Treatment Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13229",
    name: "L'Oréal Professionnel Serié Expert Scalp Advanced Duo + FREE 100ml Shampoo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13226",
    name: "L'Oréal Professionnel Serié Expert Scalp Advanced Treatment Bundle + FREE 100ml Shampoo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13225",
    name: "L'Oréal Professionnel Serié Expert Scalp Advanced Treatment Bundle + FREE 75ml Mask",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13227",
    name: "L'Oréal Professionnel Serié Expert ULTIMATE Scalp Advanced Treatment + FREE 100ml Shampoo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13228",
    name: "L'Oréal Professionnel Silver Collection + FREE 75ml Mask",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11797",
    name: "L'Oréal Professionnel Vitamino Color Duo With FREE Mask",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13231",
    name: "L'Oréal Professionnel Vitamino Colour Shampoo 1500ml + 100ml FREE",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13234",
    name: "L'Oréal Professionnel Vitamino Colour ULTIMATE Collection + 75ml FREE",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13232",
    name: "L'Oréal Professionnel Vitamino Mask & Conditioner + FREE 100ml Shampoo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13230",
    name: "L'Oréal Professionnel Vitamino Shampoo & Conditioner DUO + FREE 75ml Mask",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13233",
    name: "L'Oréal Professionnel Vitamino SUPER SIZE Shampoo & Conditioner DUO + FREE 100ml Shampoo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10545",
    name: "L'Oreal Steampod V3 Bundle with FREE Travel Case By KARL LAGERFELD",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9632",
    name: "L'Oreal Steampod V3 White with FREE Kerastase Thermique",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11749",
    name: "L'Oreal Steampod V3 White with FREE Paddle Brush",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11750",
    name: "L'Oreal Steampod with FREE Steam-Active Milk 150ml & Paddle Brush",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9631B",
    name: "Loreal Steampod V3 With FREE Steampod Smoothing Treatment 50ml & Kérastase Elixir Ultime 50ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10421",
    name: "Morocanoil Gym Bottle and Repair Essentials Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11077A",
    name: "Moroccanoil -  Light Tones Treat, Hydrate & Restore Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11077",
    name: "Moroccanoil - Treat, Hydrate & Restore Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10127",
    name: "Moroccanoil Blow-Dry Collection - Free 25ml Treatment Oil",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10128",
    name: "Moroccanoil Curl Collection Bundle - Free 25ml Treatment Oil",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10129",
    name: "Moroccanoil Dry Shampoo Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10130",
    name: "Moroccanoil Dry Shampoo Collection - Free 25ml Treatment Oil",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10131",
    name: "Moroccanoil Extra Volume Shampoo & Conditioner 500ml - Free 25ml Treatment Oil",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10734",
    name: "Moroccanoil Hydrate Shampoo & Conditioner 70ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8070",
    name: "Moroccanoil Hydrating 250ml Bundle with FREE GIFT",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10132",
    name: "Moroccanoil Hydrating Shampoo & Conditioner 500ml - Free 25ml Treatment Oil",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9091",
    name: "Moroccanoil Light Treatment Oil 125ml + 20ml Free",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10133",
    name: "Moroccanoil Light Treatment Oil 25ml - Buy 3 Get 4 x 10mls Free",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9092",
    name: "Moroccanoil Mending Infusion 75ml + 20ml Free",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10134",
    name: "Moroccanoil Moisture Repair Shampoo & Conditioner 500ml - Free 25ml Treatment Oil",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12750",
    name: "Moroccanoil Oil Eurovision Treatment Original - 125ml For The Price of 100ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10135",
    name: "Moroccanoil Repair Bundle - Free 25ml Treatment Oil",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10136",
    name: "Moroccanoil Travel Collection - Free 25ml Treatment Oil",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "5882",
    name: "Moroccanoil Travel Size Repair Shampoo & Conditioner 70ml Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9090",
    name: "Moroccanoil Treatment Oil 100ml + 20ml Free",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10137",
    name: "Moroccanoil Treatment Oil 25ml - Buy 3 Get 4 x 10mls Free",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10138",
    name: "Moroccanoil Volume Collection - Free 50ml Treatment Oil",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10143",
    name: "NAK Blonde - Ultimate Collection",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11152",
    name: "NAK Platinum Blonde Trio 100ml Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10917",
    name: "Nioxin 3D Intensive Deep Protect Density Mask 500ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11851",
    name: "Olaplex Bonding Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10097",
    name: "Olaplex Complete Collection",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8875",
    name: "Olaplex Hero Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11861",
    name: "Olaplex No.3 and No.6 Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11858",
    name: "Olaplex No.7 and No.3 Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10098",
    name: "Olaplex Protect and Care Solution Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12263",
    name: "Olaplex Shampoo & Conditioner 1 Litre Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8874",
    name: "Olaplex Shampoo & Conditioner Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11338",
    name: "Olaplex The Anti Damage Duo - No.3 & No.9",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8876",
    name: "Olaplex Ultimate Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10145",
    name: "Protect My Blonde - Ultimate Collection - Staff Picks",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14275",
    name: "Pureology Hydrate Shampoo, Conditioner and Color Fanatic Leave In Conditioner Moisturising Bundle For Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10257A",
    name: "Pureology Hydrate Sheer Shampoo & Conditioner 266ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14274",
    name: "Pureology Hydrate Sheer Shampoo, Conditioner and Color Fanatic Leave In Conditioner Bundle For Fine, Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11359A",
    name: "Pureology Nanoworks Gold Shampoo & Conditioner 266ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14273",
    name: "Pureology Nanoworks Gold Shampoo, Conditioner and Color Fanatic Leave In Conditioner Bundle For Dry, Dull Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9717",
    name: "Pureology Pure Hydrate Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14302",
    name: "Pureology Pure Hydrate Shampoo 50ml GWP",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14277",
    name: "Pureology Pure Volume Shampoo and Conditioner Bundle For Fine, Flat Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14278",
    name: "Pureology Smooth Perfection Shampoo and Conditioner Smoothing Bundle For Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10144",
    name: "Pureology Strength Cure Best Blonde - Collection",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14276",
    name: "Pureology Strength Cure Shampoo, Conditioner and Color Fanatic Leave In Conditioner Bundle For Damaged Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9718",
    name: "Pureology Super Smooth Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12337",
    name: "Quench Your Hair Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14279",
    name: "Redken Acidic Bonding Concentrate Intensive Pre-Treatment, Shampoo, Conditioner Bond Repair Bundle For Damaged Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12925",
    name: "Redken Acidic Bonding Concentrate Shampoo And Conditioner Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14280",
    name: "Redken Acidic Bonding Concentrate Shampoo, Conditioner and 5-Minute Liquid Hair Mask Bond Repair Bundle For Damaged Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10455",
    name: "Redken Acidic Bonding Concentrate Solution Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11852",
    name: "Redken Acidic Bonding Shampoo and Conditioner Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14523",
    name: "Redken Acidic Color Gloss - The Full Routine Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14590",
    name: "Redken Acidic Color Gloss Condition & Treat Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14522",
    name: "Redken Acidic Color Gloss Shampoo & Conditioner Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14592",
    name: "Redken Acidic Color Gloss Shampoo, Conditioner & Glass Gloss Treatment Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14591",
    name: "Redken Acidic Color Gloss Shampoo, Conditioner & Leave In Heat Protectant Treatment Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12926",
    name: "Redken All Soft Conditioner Duo (2 X 250ml)",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12927",
    name: "Redken All Soft Heavy Cream Duo (2 X 250ml)",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11860",
    name: "Redken All Soft Mega Shampoo and Conditioner Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8972",
    name: "Redken All Soft Shampoo and Conditioner 500ml Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8970",
    name: "Redken All Soft Shampoo and Conditioner Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12928",
    name: "Redken All Soft Shampoo Duo (2 X 300ml)",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14281",
    name: "Redken All Soft Shampoo, Conditioner and Moisture Restore Leave In Conditioner, Hydrating Bundle, Softness & Shine, for Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14282",
    name: "Redken All Soft Shampoo, Conditioner and One United Multi-Benefit Leave In Conditioner Spray Hydrating Bundle for Dry Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10453",
    name: "Redken All Soft Solution Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9719",
    name: "Redken Color Extend Blondage Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "9720",
    name: "Redken Color Extend Blondage Ultimate Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12930",
    name: "Redken Color Extend Brownlights Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11867",
    name: "Redken Color Extend Magnetic Shampoo 300ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12931",
    name: "Redken Color Extend Magnetic Shampoo Duo (2 X 300ml)",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8455",
    name: "Redken Colour Extend Blondage Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8969",
    name: "Redken Colour Extend Blondage Shampoo and Conditioner Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12932",
    name: "Redken Curvaceous Conditioner Duo (2 X 250ml)",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11874",
    name: "Redken Curvaceous Cream Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12933",
    name: "Redken Curvaceous High Foam Shampoo Duo (2 X 300ml)",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12934",
    name: "Redken Extreme Anti-Snap Treatment Duo (2 X 250ml)",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12935",
    name: "Redken Extreme Bundle With Free One United",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12936",
    name: "Redken Extreme Conditioner Duo (2 X 300ml)",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11866",
    name: "Redken Extreme Shampoo 300ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "8971",
    name: "Redken Extreme Shampoo and Conditioner Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12937",
    name: "Redken Extreme Shampoo Duo (2 X 300ml)",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14283",
    name: "Redken Extreme Shampoo, Conditioner and Anti-Snap Leave In Conditioner Spray Bundle For Damaged Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14284",
    name: "Redken Extreme Shampoo, Conditioner and One United Multi-Benefit Leave In Conditioner Spray Bundle For Damaged Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10454",
    name: "Redken Extreme Solution Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "11877",
    name: "Redken One United Multi-Benefit Treatment 150ml Duo",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14285",
    name: "Redken Volume Injection Shampoo and Conditioner Bundle For Fine Flat Hair",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14414",
    name: "Ruth Bergin's Healthy Hair Favourites Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12757A",
    name: "Smooth Deluxe Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12756A",
    name: "Smooth Extra Value Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12758A",
    name: "Smooth Holiday Gift Set PLUS Free Cristalli Liquidi 15ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13041",
    name: "Staff Favourites: The Haircare Heroes Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14460",
    name: "The Anti-Hair Loss Box",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12336",
    name: "The Bleach Recovery Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "14459",
    name: "The Energize & Stimulate Hair Growth Box",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13039",
    name: "The K18 Damage Control Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "12335",
    name: "Turn Down The Heat Damage Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10551",
    name: "Color Wow Dream Coat 200ml With FREE Dream Coat 50ml",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "10552",
    name: "Olaplex Blonde Enhancer Bundle",
    category: "Haircare",
    category_id: 982,
  },
  {
    sku: "13293A",
    name: "BeautiEdit - Be Berry Bronzed Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "11553Z",
    name: "BeautiEdit - Glow Hero's",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "13294A",
    name: "BeautiEdit - Glow On The Go Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10730A",
    name: "BeautiEdit - Medium - Tan Treat Hydrate Self-Tanning Foam & MIT",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "13295A",
    name: "BeautiEdit - The Dream Team Medium Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "13296A",
    name: "BeautiEdit - The Dream Team Ultra Dark Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "BE_1",
    name: "BeautiEdit -TIME TO GLOW BUNDLE",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "11553A",
    name: "BeautiEdit PRISTINE - Express Self Tanning Foam 150ml & Mitt",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10731A",
    name: "BeautiEdit Tan Dark - 3 in 1 Self Tanning Foam & MITT",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10730B",
    name: "BeautiEdit Tan Medium - 3 in 1 Self Tanning Foam & MITT",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10732A",
    name: "BeautiEdit Tan Ultra Dark - 3 in 1 Self Tanning Foam & MITT",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "11849",
    name: "CeraVe Best Sellers Duo",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "11865",
    name: "CeraVe Cleanse the Day Away Duo",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "11859",
    name: "CeraVe Your Best Skin PM Duo",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "9452",
    name: "Decleor Antidote Serum Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "9451",
    name: "Decleor Baume De Nuit (Night Balm) Neroli Bigarade Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "8906",
    name: "Decleor Eucalyptus Baume & Botanical Oil Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "100047",
    name: "Decleor Face Essential Cleansing Salon Size Duo",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "9450",
    name: "Decleor Light Day Cream Neroli Bigrade Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "8985",
    name: "Decleor Rosemary Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "8923",
    name: "Decleor Sun-Kissed Cream & Hydrating Body Milk Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "14744",
    name: "Dermalogica -  The Clearing & Brightening Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "GIFT",
    name: "Dermalogica - Gift Certificate",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "14743",
    name: "Dermalogica - The Calming & Nourishing Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "14745",
    name: "Dermalogica - The Dark Spot Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10308",
    name: "Dermalogica Age Smart Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10310",
    name: "Dermalogica Clear Start Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10306",
    name: "Dermalogica Dry / Very Dry Skin Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "GWP26",
    name: "Dermalogica Heroes Collection GWP",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10197",
    name: "Dermalogica Hyperpigmentation Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10305",
    name: "Dermalogica Normal / Dry Skin Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10307",
    name: "Dermalogica Oily Skin Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10311",
    name: "Dermalogica SPF Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10309",
    name: "Dermlogica Ultra Calming Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10320",
    name: "Mio Body Moisturiser with Free Skin Tight Body Serum",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10355",
    name: "Mio Skin Tight Body Serum Buy 2 Get 1 Free",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "10443",
    name: "NUXE Toning Mist and Micellar Water Soothing Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "7785",
    name: "The Ordinary 3 Step Retinol Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "6835",
    name: "The Ordinary Acne Treatment Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "11856",
    name: "The Ordinary Anti-Ageing Hydration Duo",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "6745a",
    name: "The Ordinary Anti-Ageing Trio (3 x 30ml) Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "11853",
    name: "The Ordinary Caffeine Solution 5% + EGCG Duo",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "6833",
    name: "The Ordinary Heroes Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "9960",
    name: "The Ordinary Hyaluronic Acid 2% + B5 - 30ml - Buy 4 Get 1 FREE",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "11854",
    name: "The Ordinary Hyaluronic Acid 2% + B5 Hydration Duo",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "6834",
    name: "The Ordinary Hydrating Skin Set Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "9959",
    name: "The Ordinary Niacinamide 10% + Zinc 1% 30ml - Buy 4 Get 1 FREE",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "7784",
    name: "The Ordinary No-Brainer Bundle",
    category: "Skincare",
    category_id: 983,
  },
  {
    sku: "7783",
    name: "The Ordinary Routine Starter Pack Bundle",
    category: "Skincare",
    category_id: 983,
  },
];

async function bundles() {
  require("./config/config").config("bf");
  for (let i = 0; i < data.length; i++) {
    const d = data[i];
    console.log(i, data.length);
    const product = await getProductBySku(d.sku);
    if (!product) continue;

    if (!product.categories.includes(663)) {
      product.categories.push(663);
    }

    if (!product.categories.includes(d.category_id)) {
      product.categories.push(d.category_id);
    }

    await updateProduct(product.id, { categories: product.categories });
  }
}

bundles();
