import axios from "axios";
import sharp from "sharp";
import { deleteProductImage } from "../../functions/images/deleteProductImage";
import { createProductImageFromBuffer } from "../../functions/images/createProductImage";
import path from "path";
import fs from "fs";
const { config } = require("../../config/config");

// Helper function to format bytes into human-readable units (KB, MB, etc.)
function formatBytes(bytes: number, decimals: number = 2): string {
  if (bytes === 0) return "0 Bytes";

  const k = 1024;
  const sizes = ["Bytes", "KB", "MB", "GB", "TB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));

  // Calculate the value in the appropriate unit
  const value = bytes / Math.pow(k, i);

  // Handle cases where decimals should be omitted for Bytes
  const formattedValue =
    i === 0
      ? value.toString() // No decimals for Bytes
      : value.toFixed(decimals);

  return `${formattedValue} ${sizes[i]}`;
}

async function compressImage(imageUrl: string): Promise<{
  originalSize: number;
  compressedBuffer: Buffer;
  compressedSize: number;
}> {
  try {
    // Fetch the image
    const response = await axios.get(imageUrl, { responseType: "arraybuffer" });
    const imageBuffer = Buffer.from(response.data, "binary");

    // Calculate original size
    const originalSize = Buffer.byteLength(imageBuffer);
    console.log(`Original size: ${formatBytes(originalSize)}`);

    // Determine quality based on original size
    const quality = originalSize > 770 * 1024 ? 50 : 80; // 770 KB threshold
    console.log(`Using quality: ${quality}`);

    // Load the image metadata to get dimensions
    const metadata = await sharp(imageBuffer).metadata();
    const { width, height } = metadata;

    // Check if both dimensions are greater than 1000px
    if (width && height && width > 1000 && height > 1000) {
      console.log("Resizing image to maintain aspect ratio...");
      // Determine the shortest side and scale it to 1000px
      const scaleFactor = 1000 / Math.min(width, height);

      // Resize and compress the image
      const resizedBuffer = await sharp(imageBuffer)
        .resize(
          Math.round(width * scaleFactor),
          Math.round(height * scaleFactor),
          {
            fit: "inside", // Maintain aspect ratio
            withoutEnlargement: true, // Prevent enlarging if already smaller
          }
        )
        .jpeg({ quality })
        .toBuffer();

      // Calculate compressed size
      const compressedSize = Buffer.byteLength(resizedBuffer);
      console.log(`Compressed size: ${formatBytes(compressedSize)}`);

      return { originalSize, compressedBuffer: resizedBuffer, compressedSize };
    } else {
      console.log(
        "Image dimensions are within limits. Compressing without resizing..."
      );
      // Compress the image without resizing
      const compressedBuffer = await sharp(imageBuffer)
        .jpeg({ quality })
        .toBuffer();

      // Calculate compressed size
      const compressedSize = Buffer.byteLength(compressedBuffer);
      console.log(`Compressed size: ${formatBytes(compressedSize)}`);

      return { originalSize, compressedBuffer, compressedSize };
    }
  } catch (error) {
    console.error("Error:", error);
    throw error;
  }
}

const data = [
  {
    product_id: 168,
    image_id: 3283,
    sort_order: 1,
    is_thumbnail: null,
    sku: "333A",
    name: "Folding Chair Burgundy",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/v/156/120__56871.jpg",
    file_size: 74639,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 168,
    image_id: 3284,
    sort_order: 3,
    is_thumbnail: null,
    sku: "333A",
    name: "Folding Chair Burgundy",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/y/757/122__63836.jpg",
    file_size: 64743,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 168,
    image_id: 3285,
    sort_order: 2,
    is_thumbnail: null,
    sku: "333A",
    name: "Folding Chair Burgundy",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/s/432/121__88221.jpg",
    file_size: 63789,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 191,
    image_id: 3278,
    sort_order: 3,
    is_thumbnail: null,
    sku: "1000536",
    name: "Folding Chair Blue For Hire",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/778/117__27801.jpg",
    file_size: 58670,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 191,
    image_id: 3279,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1000536",
    name: "Folding Chair Blue For Hire",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/n/392/116__01421.jpg",
    file_size: 84349,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 191,
    image_id: 3280,
    sort_order: 4,
    is_thumbnail: null,
    sku: "1000536",
    name: "Folding Chair Blue For Hire",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/l/012/119__43997.jpg",
    file_size: 78916,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 191,
    image_id: 3281,
    sort_order: 5,
    is_thumbnail: null,
    sku: "1000536",
    name: "Folding Chair Blue For Hire",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/y/110/118__59341.jpg",
    file_size: 59845,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 191,
    image_id: 3282,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1000536",
    name: "Folding Chair Blue For Hire",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/n/860/115__68315.jpg",
    file_size: 73863,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 255,
    image_id: 3212,
    sort_order: 1,
    is_thumbnail: null,
    sku: "PADBLUE01",
    name: "Padded Banquet Chair Blue",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/w/609/Untitled_design_4__21790.jpg",
    file_size: 80334,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 291,
    image_id: 1960,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "IL08",
    name: "Star Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/f/407/hhk_1__32735.jpg",
    file_size: 21099,
    width: 1366,
    height: 1366,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 291,
    image_id: 3325,
    sort_order: 1,
    is_thumbnail: null,
    sku: "IL08",
    name: "Star Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/j/047/145__90079.jpg",
    file_size: 68403,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 291,
    image_id: 3326,
    sort_order: 2,
    is_thumbnail: null,
    sku: "IL08",
    name: "Star Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/z/443/144__86898.jpg",
    file_size: 23029,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 308,
    image_id: 3182,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1000565",
    name: "Chiavari Chair Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/x/849/16__23330.jpg",
    file_size: 75573,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 308,
    image_id: 3183,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1000565",
    name: "Chiavari Chair Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/a/159/17__31806.jpg",
    file_size: 84617,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 315,
    image_id: 3169,
    sort_order: 2,
    is_thumbnail: null,
    sku: "BTWOOD",
    name: "Bentwood Rustic Oak Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/a/758/4__12551.jpg",
    file_size: 103770,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 315,
    image_id: 3170,
    sort_order: 1,
    is_thumbnail: null,
    sku: "BTWOOD",
    name: "Bentwood Rustic Oak Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/s/701/3__43601.jpg",
    file_size: 73836,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 315,
    image_id: 4177,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "BTWOOD",
    name: "Bentwood Rustic Oak Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/y/648/Untitled_design_6__21255.png",
    file_size: 122199,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 331,
    image_id: 3247,
    sort_order: 1,
    is_thumbnail: null,
    sku: "AURORAWH",
    name: "Aurora Bar Stool White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/u/171/101__93026.jpg",
    file_size: 52943,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 331,
    image_id: 3248,
    sort_order: 4,
    is_thumbnail: null,
    sku: "AURORAWH",
    name: "Aurora Bar Stool White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/065/104__35933.jpg",
    file_size: 34273,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 331,
    image_id: 3249,
    sort_order: 3,
    is_thumbnail: null,
    sku: "AURORAWH",
    name: "Aurora Bar Stool White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/i/930/102__70818.jpg",
    file_size: 45134,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 331,
    image_id: 3250,
    sort_order: 5,
    is_thumbnail: null,
    sku: "AURORAWH",
    name: "Aurora Bar Stool White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/g/057/103__31475.jpg",
    file_size: 49022,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 331,
    image_id: 3251,
    sort_order: 6,
    is_thumbnail: null,
    sku: "AURORAWH",
    name: "Aurora Bar Stool White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/a/715/105__98715.jpg",
    file_size: 48607,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 335,
    image_id: 3332,
    sort_order: 1,
    is_thumbnail: null,
    sku: "SL1008",
    name: "Wow bench - Saffron yellow",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/e/975/151__76899.jpg",
    file_size: 41258,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 335,
    image_id: 3333,
    sort_order: 2,
    is_thumbnail: null,
    sku: "SL1008",
    name: "Wow bench - Saffron yellow",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/p/605/152__66102.jpg",
    file_size: 66461,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 349,
    image_id: 3193,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1000546",
    name: "Chiavari Chair Limewash (deluxe)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/a/215/28__31797.jpg",
    file_size: 72145,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 349,
    image_id: 3194,
    sort_order: 5,
    is_thumbnail: null,
    sku: "1000546",
    name: "Chiavari Chair Limewash (deluxe)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/z/806/31__98475.jpg",
    file_size: 55409,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 349,
    image_id: 3195,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1000546",
    name: "Chiavari Chair Limewash (deluxe)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/o/710/27__73966.jpg",
    file_size: 51463,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 349,
    image_id: 3196,
    sort_order: 4,
    is_thumbnail: null,
    sku: "1000546",
    name: "Chiavari Chair Limewash (deluxe)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/p/730/30__77816.jpg",
    file_size: 53961,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 349,
    image_id: 3197,
    sort_order: 3,
    is_thumbnail: null,
    sku: "1000546",
    name: "Chiavari Chair Limewash (deluxe)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/409/29__38696.jpg",
    file_size: 78487,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 356,
    image_id: 3272,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1000937",
    name: "Zeus Bar Stool Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/e/306/95__59488.jpg",
    file_size: 59368,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 356,
    image_id: 3273,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1000937",
    name: "Zeus Bar Stool Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/f/417/96__68711.jpg",
    file_size: 50450,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 356,
    image_id: 3274,
    sort_order: 5,
    is_thumbnail: null,
    sku: "1000937",
    name: "Zeus Bar Stool Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/f/835/99__71959.jpg",
    file_size: 49081,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 356,
    image_id: 3275,
    sort_order: 3,
    is_thumbnail: null,
    sku: "1000937",
    name: "Zeus Bar Stool Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/y/130/97__94981.jpg",
    file_size: 51522,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 356,
    image_id: 3276,
    sort_order: 6,
    is_thumbnail: null,
    sku: "1000937",
    name: "Zeus Bar Stool Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/y/373/100__01567.jpg",
    file_size: 58516,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 356,
    image_id: 3277,
    sort_order: 4,
    is_thumbnail: null,
    sku: "1000937",
    name: "Zeus Bar Stool Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/r/149/98__78280.jpg",
    file_size: 55491,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 366,
    image_id: 1790,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "F018",
    name: "Chloe White Chameleon Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/p/368/Shot_10.01__09896.jpg",
    file_size: null,
    width: 4872,
    height: 4872,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 366,
    image_id: 3205,
    sort_order: 1,
    is_thumbnail: null,
    sku: "F018",
    name: "Chloe White Chameleon Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/g/023/Untitled_design_3__27206.jpg",
    file_size: 28879,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 435,
    image_id: 3213,
    sort_order: 1,
    is_thumbnail: null,
    sku: "PADRED01",
    name: "Padded Banquet Chair Red",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/577/Untitled_design_5__13185.jpg",
    file_size: 47383,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 472,
    image_id: 3259,
    sort_order: 3,
    is_thumbnail: null,
    sku: "CHST",
    name: "Chiavari Bar Stool - Limewash",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/485/91__38739.jpg",
    file_size: 53990,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 472,
    image_id: 3260,
    sort_order: 1,
    is_thumbnail: null,
    sku: "CHST",
    name: "Chiavari Bar Stool - Limewash",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/d/956/92__42254.jpg",
    file_size: 67787,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 472,
    image_id: 3261,
    sort_order: 2,
    is_thumbnail: null,
    sku: "CHST",
    name: "Chiavari Bar Stool - Limewash",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/691/93__23224.jpg",
    file_size: 38254,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 475,
    image_id: 3286,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "1000550",
    name: "Children's Stool Dark Blue",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/b/891/124__31901.jpg",
    file_size: 24402,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 509,
    image_id: 3206,
    sort_order: 3,
    is_thumbnail: null,
    sku: "OH02",
    name: "Highback Dining Chair White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/u/062/42__08905.jpg",
    file_size: 44980,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 509,
    image_id: 3207,
    sort_order: 1,
    is_thumbnail: null,
    sku: "OH02",
    name: "Highback Dining Chair White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/274/40__10582.jpg",
    file_size: 45170,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 509,
    image_id: 3208,
    sort_order: 2,
    is_thumbnail: null,
    sku: "OH02",
    name: "Highback Dining Chair White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/w/115/41__08955.jpg",
    file_size: 44023,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 520,
    image_id: 3252,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1000150",
    name: "Button Bar Stool Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/x/071/81__13859.jpg",
    file_size: 41213,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 520,
    image_id: 3253,
    sort_order: 3,
    is_thumbnail: null,
    sku: "1000150",
    name: "Button Bar Stool Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/y/000/83__60483.jpg",
    file_size: 52594,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 520,
    image_id: 3254,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1000150",
    name: "Button Bar Stool Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/t/798/82__09601.jpg",
    file_size: 39488,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 520,
    image_id: 3255,
    sort_order: 4,
    is_thumbnail: null,
    sku: "1000150",
    name: "Button Bar Stool Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/y/260/84__47453.jpg",
    file_size: 38973,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 525,
    image_id: 3189,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1000567",
    name: "Chiavari Chair Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/r/573/23__92631.jpg",
    file_size: 58912,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 525,
    image_id: 3190,
    sort_order: 4,
    is_thumbnail: null,
    sku: "1000567",
    name: "Chiavari Chair Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/i/289/26__33386.jpg",
    file_size: 66382,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 525,
    image_id: 3191,
    sort_order: 3,
    is_thumbnail: null,
    sku: "1000567",
    name: "Chiavari Chair Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/m/390/25__63519.jpg",
    file_size: 83923,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 525,
    image_id: 3192,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1000567",
    name: "Chiavari Chair Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/011/24__07156.jpg",
    file_size: 96057,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 530,
    image_id: 3302,
    sort_order: 3,
    is_thumbnail: null,
    sku: "SL1010",
    name: "Pop Bench - Jet Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/q/237/136__87287.jpg",
    file_size: 23554,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 530,
    image_id: 3303,
    sort_order: 4,
    is_thumbnail: null,
    sku: "SL1010",
    name: "Pop Bench - Jet Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/z/166/135__76466.jpg",
    file_size: 37762,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 549,
    image_id: 3288,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "1000583",
    name: "Children's Stool Lime Green",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/n/186/126__98707.jpg",
    file_size: 23957,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 567,
    image_id: 3168,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1000547",
    name: "All Seasons Padded Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/j/881/Untitled_design__76782.jpg",
    file_size: 45952,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 579,
    image_id: 1958,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "IL10",
    name: "Half Moon Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/w/625/hh_1__74985.jpg",
    file_size: 16560,
    width: 1366,
    height: 1366,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 579,
    image_id: 3293,
    sort_order: 3,
    is_thumbnail: null,
    sku: "IL10",
    name: "Half Moon Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/z/910/130__99235.jpg",
    file_size: 26911,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 579,
    image_id: 3294,
    sort_order: 2,
    is_thumbnail: null,
    sku: "IL10",
    name: "Half Moon Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/n/913/128__17432.jpg",
    file_size: 32599,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 579,
    image_id: 3295,
    sort_order: 1,
    is_thumbnail: null,
    sku: "IL10",
    name: "Half Moon Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/d/005/129__81824.jpg",
    file_size: 38858,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 579,
    image_id: 3296,
    sort_order: 4,
    is_thumbnail: null,
    sku: "IL10",
    name: "Half Moon Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/b/321/131__96056.jpg",
    file_size: 39496,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 579,
    image_id: 3297,
    sort_order: 5,
    is_thumbnail: null,
    sku: "IL10",
    name: "Half Moon Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/342/132__55503.jpg",
    file_size: 33002,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 604,
    image_id: 1959,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "IL07",
    name: "Snake Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/z/191/nn_1__49340.jpg",
    file_size: 15994,
    width: 1366,
    height: 1366,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 604,
    image_id: 3320,
    sort_order: 4,
    is_thumbnail: null,
    sku: "IL07",
    name: "Snake Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/x/084/141__87953.jpg",
    file_size: 48163,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 604,
    image_id: 3321,
    sort_order: 2,
    is_thumbnail: null,
    sku: "IL07",
    name: "Snake Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/d/888/139__06030.jpg",
    file_size: 23193,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 604,
    image_id: 3322,
    sort_order: 1,
    is_thumbnail: null,
    sku: "IL07",
    name: "Snake Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/m/731/143__64506.jpg",
    file_size: 37634,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 604,
    image_id: 3323,
    sort_order: 5,
    is_thumbnail: null,
    sku: "IL07",
    name: "Snake Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/s/218/142__93129.jpg",
    file_size: 39652,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 604,
    image_id: 3324,
    sort_order: 3,
    is_thumbnail: null,
    sku: "IL07",
    name: "Snake Bench Illuminated",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/312/140__70467.jpg",
    file_size: 33571,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 618,
    image_id: 3300,
    sort_order: 2,
    is_thumbnail: null,
    sku: "SL1011",
    name: "Pop Bench - Flame Red",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/a/685/136__34877.jpg",
    file_size: 23554,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 618,
    image_id: 3301,
    sort_order: 1,
    is_thumbnail: null,
    sku: "SL1011",
    name: "Pop Bench - Flame Red",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/946/135__26045.jpg",
    file_size: 37762,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 619,
    image_id: 3334,
    sort_order: 3,
    is_thumbnail: null,
    sku: "SL1009",
    name: "Wow bench- Lime green",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/024/152__37532.jpg",
    file_size: 66461,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3217,
    sort_order: 5,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/r/135/56__52589.jpg",
    file_size: 59482,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3218,
    sort_order: 1,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/d/869/52__12876.jpg",
    file_size: 38206,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3219,
    sort_order: 4,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/z/914/55__06667.jpg",
    file_size: 63750,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3220,
    sort_order: 3,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/w/829/54__19495.jpg",
    file_size: 51316,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3221,
    sort_order: 2,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/d/992/53__58814.jpg",
    file_size: 65614,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3378,
    sort_order: 6,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/g/308/62__74207.png",
    file_size: 91931,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3379,
    sort_order: 13,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/b/668/69__02267.png",
    file_size: 68765,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3380,
    sort_order: 12,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/g/925/68__46888.png",
    file_size: 110544,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3381,
    sort_order: 7,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/820/63__07025.png",
    file_size: 147345,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3382,
    sort_order: 14,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/z/991/70__34957.png",
    file_size: 80006,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3383,
    sort_order: 11,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/q/701/67__92427.png",
    file_size: 123722,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3384,
    sort_order: 8,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/s/405/64__55978.png",
    file_size: 124813,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3385,
    sort_order: 9,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/186/65__22562.png",
    file_size: 111890,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3386,
    sort_order: 15,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/v/118/71__32233.png",
    file_size: 184140,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 698,
    image_id: 3387,
    sort_order: 10,
    is_thumbnail: null,
    sku: "F001",
    name: "Chameleon Chair Silver Back",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/o/790/66__70212.png",
    file_size: 132298,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 705,
    image_id: 3257,
    sort_order: 2,
    is_thumbnail: null,
    sku: "11181W",
    name: "Button Bar Stool White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/p/195/90__73915.jpg",
    file_size: 47623,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 705,
    image_id: 3258,
    sort_order: 1,
    is_thumbnail: null,
    sku: "11181W",
    name: "Button Bar Stool White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/d/304/89__73313.jpg",
    file_size: 49325,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 728,
    image_id: 3240,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1000569",
    name: "Folding White Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/q/891/75__74122.jpg",
    file_size: 44568,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 728,
    image_id: 3241,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1000569",
    name: "Folding White Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/r/540/74__57645.jpg",
    file_size: 33165,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 728,
    image_id: 3242,
    sort_order: 3,
    is_thumbnail: null,
    sku: "1000569",
    name: "Folding White Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/873/76__71557.jpg",
    file_size: 55492,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 728,
    image_id: 3243,
    sort_order: 6,
    is_thumbnail: null,
    sku: "1000569",
    name: "Folding White Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/o/999/79__15604.jpg",
    file_size: 46354,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 728,
    image_id: 3244,
    sort_order: 7,
    is_thumbnail: null,
    sku: "1000569",
    name: "Folding White Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/f/174/80__02212.jpg",
    file_size: 53269,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 728,
    image_id: 3245,
    sort_order: 5,
    is_thumbnail: null,
    sku: "1000569",
    name: "Folding White Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/748/78__58228.jpg",
    file_size: 60454,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 728,
    image_id: 3246,
    sort_order: 4,
    is_thumbnail: null,
    sku: "1000569",
    name: "Folding White Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/u/602/77__52523.jpg",
    file_size: 60252,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 861,
    image_id: 3198,
    sort_order: 3,
    is_thumbnail: null,
    sku: "1000564",
    name: "Chiavari Chair Mahogany",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/s/867/32__11426.jpg",
    file_size: 44552,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 861,
    image_id: 3199,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1000564",
    name: "Chiavari Chair Mahogany",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/a/952/34__33569.jpg",
    file_size: 62853,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 861,
    image_id: 3200,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1000564",
    name: "Chiavari Chair Mahogany",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/i/878/33__81323.jpg",
    file_size: 75663,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 874,
    image_id: 1574,
    sort_order: 3,
    is_thumbnail: null,
    sku: "SL1014",
    name: "Pop Bench - Saffron Yellow",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/i/419/Pop_Benches_stacked__76436.jpg",
    file_size: 450186,
    width: 4724,
    height: 4724,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 874,
    image_id: 3308,
    sort_order: 1,
    is_thumbnail: null,
    sku: "SL1014",
    name: "Pop Bench - Saffron Yellow",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/m/956/135__33730.jpg",
    file_size: 37762,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 874,
    image_id: 3309,
    sort_order: 2,
    is_thumbnail: null,
    sku: "SL1014",
    name: "Pop Bench - Saffron Yellow",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/w/000/136__99121.jpg",
    file_size: 23554,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 882,
    image_id: 684,
    sort_order: 1,
    is_thumbnail: null,
    sku: "BS1001",
    name: "Milan High Back Bar Stool - Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/v/798/milan_black_high_back_stool__20835.jpg",
    file_size: null,
    width: 3840,
    height: 5120,
    excesive_file_size_gt_70_kb: null,
    not_square: 1,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 882,
    image_id: 820,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "BS1001",
    name: "Milan High Back Bar Stool - Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/o/093/milan_black_high_back_stool02__43572.jpg",
    file_size: null,
    width: 3840,
    height: 5120,
    excesive_file_size_gt_70_kb: null,
    not_square: 1,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 913,
    image_id: 3201,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1000546A",
    name: "Chiavari Limewash Chair (Standard)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/e/884/36__33917.jpg",
    file_size: 77272,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 913,
    image_id: 3202,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1000546A",
    name: "Chiavari Limewash Chair (Standard)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/f/039/35__62761.jpg",
    file_size: 77491,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 927,
    image_id: 3184,
    sort_order: 1,
    is_thumbnail: null,
    sku: "CRY01",
    name: "Chiavari Chair Crystal with White Pad",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/x/095/21__94603.jpg",
    file_size: 64515,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 927,
    image_id: 3185,
    sort_order: 5,
    is_thumbnail: null,
    sku: "CRY01",
    name: "Chiavari Chair Crystal with White Pad",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/w/631/22__16739.jpg",
    file_size: 69307,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 927,
    image_id: 3186,
    sort_order: 2,
    is_thumbnail: null,
    sku: "CRY01",
    name: "Chiavari Chair Crystal with White Pad",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/p/646/18__60838.jpg",
    file_size: 67961,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 927,
    image_id: 3187,
    sort_order: 3,
    is_thumbnail: null,
    sku: "CRY01",
    name: "Chiavari Chair Crystal with White Pad",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/m/915/20__26399.jpg",
    file_size: 68095,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 927,
    image_id: 3188,
    sort_order: 4,
    is_thumbnail: null,
    sku: "CRY01",
    name: "Chiavari Chair Crystal with White Pad",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/784/19__52481.jpg",
    file_size: 63815,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 941,
    image_id: 3172,
    sort_order: 1,
    is_thumbnail: null,
    sku: "F002",
    name: "Chameleon Chair Gold & Bronze with Black Legs",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/881/6__38282.jpg",
    file_size: 63171,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 941,
    image_id: 3173,
    sort_order: 4,
    is_thumbnail: null,
    sku: "F002",
    name: "Chameleon Chair Gold & Bronze with Black Legs",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/r/772/9__10375.jpg",
    file_size: 52587,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 941,
    image_id: 3174,
    sort_order: 2,
    is_thumbnail: null,
    sku: "F002",
    name: "Chameleon Chair Gold & Bronze with Black Legs",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/q/739/7__65370.jpg",
    file_size: 85903,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 941,
    image_id: 3175,
    sort_order: 3,
    is_thumbnail: null,
    sku: "F002",
    name: "Chameleon Chair Gold & Bronze with Black Legs",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/u/639/8__25485.jpg",
    file_size: 95671,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 943,
    image_id: 1569,
    sort_order: 3,
    is_thumbnail: null,
    sku: "SL1013",
    name: "Pop Bench - Lime Green",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/531/Pop_Benches_stacked__84194.jpg",
    file_size: 450186,
    width: 4724,
    height: 4724,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 943,
    image_id: 3304,
    sort_order: 1,
    is_thumbnail: null,
    sku: "SL1013",
    name: "Pop Bench - Lime Green",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/611/136__72749.jpg",
    file_size: 23554,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 943,
    image_id: 3305,
    sort_order: 2,
    is_thumbnail: null,
    sku: "SL1013",
    name: "Pop Bench - Lime Green",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/646/135__01210.jpg",
    file_size: 37762,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 981,
    image_id: 3266,
    sort_order: 3,
    is_thumbnail: null,
    sku: "BS1000",
    name: "Milan High Back Bar Stool - White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/g/081/111__52347.jpg",
    file_size: 25285,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 981,
    image_id: 3267,
    sort_order: 2,
    is_thumbnail: null,
    sku: "BS1000",
    name: "Milan High Back Bar Stool - White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/q/643/110__17699.jpg",
    file_size: 23949,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 981,
    image_id: 3268,
    sort_order: 4,
    is_thumbnail: null,
    sku: "BS1000",
    name: "Milan High Back Bar Stool - White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/f/074/112__45894.jpg",
    file_size: 53728,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 981,
    image_id: 3269,
    sort_order: 1,
    is_thumbnail: null,
    sku: "BS1000",
    name: "Milan High Back Bar Stool - White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/w/473/113__20355.jpg",
    file_size: 56549,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1027,
    image_id: 3306,
    sort_order: 1,
    is_thumbnail: null,
    sku: "SL1012",
    name: "Pop Bench - Milky white",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/a/757/135__57258.jpg",
    file_size: 37762,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1027,
    image_id: 3307,
    sort_order: 3,
    is_thumbnail: null,
    sku: "SL1012",
    name: "Pop Bench - Milky white",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/q/795/136__83183.jpg",
    file_size: 23554,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1047,
    image_id: 3289,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "1000584",
    name: "Children's Stool White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/o/930/127__95788.jpg",
    file_size: 21038,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1079,
    image_id: 3214,
    sort_order: 1,
    is_thumbnail: null,
    sku: "R003",
    name: "Rustic  Wooden Bench with Foldable legs",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/y/665/49__92016.jpg",
    file_size: 82837,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1079,
    image_id: 3215,
    sort_order: 2,
    is_thumbnail: null,
    sku: "R003",
    name: "Rustic  Wooden Bench with Foldable legs",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/914/50__12610.jpg",
    file_size: 96704,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1079,
    image_id: 3549,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "R003",
    name: "Rustic  Wooden Bench with Foldable legs",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/468/5__71476.png",
    file_size: 60317,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1101,
    image_id: 3349,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "269",
    name: "Milano Conference Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/e/786/167__99827.jpg",
    file_size: 27037,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1101,
    image_id: 3350,
    sort_order: 2,
    is_thumbnail: null,
    sku: "269",
    name: "Milano Conference Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/u/944/168__10175.jpg",
    file_size: 23958,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1101,
    image_id: 3351,
    sort_order: 1,
    is_thumbnail: null,
    sku: "269",
    name: "Milano Conference Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/128/169__99982.jpg",
    file_size: 46959,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1103,
    image_id: 1797,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "1084D",
    name: "Office Chair Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/j/778/Office_chair___40074.1599832238__49390.jpg",
    file_size: 72237,
    width: 1280,
    height: 1280,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1104,
    image_id: 3287,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "1000552",
    name: "Children's Stool Dark Pink",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/x/811/125__72790.jpg",
    file_size: 24020,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1107,
    image_id: 1528,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "ALICE0017",
    name: "Toadstool Table Red and White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/o/595/Red-Toadstool-Table-Prop-to-Rent-lolliprops.ie__09706.jpg",
    file_size: 351831,
    width: 3592,
    height: 3592,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1108,
    image_id: 3290,
    sort_order: 1,
    is_thumbnail: null,
    sku: "ALICE0026",
    name: "Toadstool Green and White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/t/686/123__79448.jpg",
    file_size: 55638,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1109,
    image_id: 3291,
    sort_order: 1,
    is_thumbnail: null,
    sku: "ALICE0027",
    name: "Toadstool Purple and White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/b/194/123__54918.jpg",
    file_size: 55638,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1110,
    image_id: 3292,
    sort_order: 1,
    is_thumbnail: null,
    sku: "ALICE0024",
    name: "Toadstool Red and White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/b/106/123__58613.jpg",
    file_size: 55638,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1117,
    image_id: 3312,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1083B",
    name: "Smartie Bench Black (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/743/137__72921.jpg",
    file_size: 67220,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1117,
    image_id: 3313,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1083B",
    name: "Smartie Bench Black (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/t/474/138__31274.jpg",
    file_size: 36235,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1118,
    image_id: 1590,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "1083C",
    name: "Smartie Bench Fuchsia (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/u/367/smartie_bench_pink__45606.jpg",
    file_size: 75959,
    width: 2779,
    height: 2778,
    excesive_file_size_gt_70_kb: 1,
    not_square: 1,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1118,
    image_id: 3310,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1083C",
    name: "Smartie Bench Fuchsia (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/x/486/137__12769.jpg",
    file_size: 67220,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1118,
    image_id: 3311,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1083C",
    name: "Smartie Bench Fuchsia (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/z/917/138__79159.jpg",
    file_size: 36235,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1119,
    image_id: 1593,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "1083D",
    name: "Smartie Bench Yellow (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/e/056/smartie_bench_yellow_2__71120.jpg",
    file_size: 69497,
    width: 2582,
    height: 2582,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1119,
    image_id: 3318,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1083D",
    name: "Smartie Bench Yellow (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/d/129/138__60048.jpg",
    file_size: 36235,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1119,
    image_id: 3319,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1083D",
    name: "Smartie Bench Yellow (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/l/418/137__03669.jpg",
    file_size: 67220,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1120,
    image_id: 1596,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "1083E",
    name: "Smartie Bench Lime Green (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/w/788/smartie_bench_green___52609.jpg",
    file_size: 86732,
    width: 2926,
    height: 2926,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1120,
    image_id: 3314,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1083E",
    name: "Smartie Bench Lime Green (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/e/577/137__03911.jpg",
    file_size: 67220,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1120,
    image_id: 3315,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1083E",
    name: "Smartie Bench Lime Green (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/b/334/138__58409.jpg",
    file_size: 36235,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1121,
    image_id: 4311,
    sort_order: 3,
    is_thumbnail: null,
    sku: "FLOW15",
    name: "Cube White Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/u/168/12__60971.jpg",
    file_size: 97410,
    width: 3331,
    height: 3331,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1121,
    image_id: 4312,
    sort_order: 5,
    is_thumbnail: null,
    sku: "FLOW15",
    name: "Cube White Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/e/583/14__34259.jpg",
    file_size: 110011,
    width: 3331,
    height: 3331,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1121,
    image_id: 4313,
    sort_order: 2,
    is_thumbnail: null,
    sku: "FLOW15",
    name: "Cube White Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/v/421/11__15834.jpg",
    file_size: 105358,
    width: 3331,
    height: 3331,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1121,
    image_id: 4314,
    sort_order: 4,
    is_thumbnail: null,
    sku: "FLOW15",
    name: "Cube White Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/v/757/15__56654.jpg",
    file_size: 105095,
    width: 3331,
    height: 3331,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1121,
    image_id: 4315,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "FLOW15",
    name: "Cube White Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/a/806/13__76563.jpg",
    file_size: 109126,
    width: 3331,
    height: 3331,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1123,
    image_id: 4305,
    sort_order: 3,
    is_thumbnail: null,
    sku: "FLOW16",
    name: "Cube Black Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/o/860/Black_Cube_5__72534.jpg",
    file_size: 121785,
    width: 3355,
    height: 3355,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1123,
    image_id: 4306,
    sort_order: 4,
    is_thumbnail: null,
    sku: "FLOW16",
    name: "Cube Black Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/853/Black_Cube_3__06131.jpg",
    file_size: 125020,
    width: 3355,
    height: 3355,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1123,
    image_id: 4307,
    sort_order: 2,
    is_thumbnail: null,
    sku: "FLOW16",
    name: "Cube Black Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/v/912/Black_Cube_4__64700.jpg",
    file_size: 119567,
    width: 3355,
    height: 3355,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1123,
    image_id: 4308,
    sort_order: 5,
    is_thumbnail: null,
    sku: "FLOW16",
    name: "Cube Black Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/x/082/Black_Cube_1__96431.jpg",
    file_size: 111701,
    width: 3355,
    height: 3355,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1123,
    image_id: 4309,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "FLOW16",
    name: "Cube Black Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/r/459/Black_Cube_2__17803.jpg",
    file_size: 124817,
    width: 3355,
    height: 3355,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1125,
    image_id: 4310,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "FLOW08",
    name: "Cube Black Bar Stool (Small)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/s/911/Untitled_design_18_2__31786.png",
    file_size: 58126,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1129,
    image_id: 3271,
    sort_order: 1,
    is_thumbnail: null,
    sku: "BARWOOD",
    name: "Traditional Wooden Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/690/94__87931.jpg",
    file_size: 48811,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1131,
    image_id: 1651,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "F016",
    name: "Chameleon Black Suede Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/p/485/Chameleon_Black_Suede_Front_2016__01602.jpg",
    file_size: 280562,
    width: 4872,
    height: 4872,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1131,
    image_id: 3171,
    sort_order: 1,
    is_thumbnail: null,
    sku: "F016",
    name: "Chameleon Black Suede Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/g/205/Untitled_design_1__71501.jpg",
    file_size: 66266,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1132,
    image_id: 3176,
    sort_order: 2,
    is_thumbnail: null,
    sku: "F015",
    name: "Chameleon White Suede Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/s/010/Untitled_design_2__40768.jpg",
    file_size: 22367,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1132,
    image_id: 3177,
    sort_order: 6,
    is_thumbnail: null,
    sku: "F015",
    name: "Chameleon White Suede Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/669/13__23028.jpg",
    file_size: 65224,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1132,
    image_id: 3178,
    sort_order: 1,
    is_thumbnail: null,
    sku: "F015",
    name: "Chameleon White Suede Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/b/969/11__82587.jpg",
    file_size: 60655,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1132,
    image_id: 3179,
    sort_order: 5,
    is_thumbnail: null,
    sku: "F015",
    name: "Chameleon White Suede Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/252/14__51368.jpg",
    file_size: 72486,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1132,
    image_id: 3180,
    sort_order: 3,
    is_thumbnail: null,
    sku: "F015",
    name: "Chameleon White Suede Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/j/957/10__59530.jpg",
    file_size: 63426,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1132,
    image_id: 3181,
    sort_order: 4,
    is_thumbnail: null,
    sku: "F015",
    name: "Chameleon White Suede Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/l/228/12__72616.jpg",
    file_size: 80366,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1133,
    image_id: 3394,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "F017",
    name: "Chameleon Cocoa Brown Suede Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/y/328/212__08491.jpg",
    file_size: 22923,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1133,
    image_id: 3395,
    sort_order: 1,
    is_thumbnail: null,
    sku: "F017",
    name: "Chameleon Cocoa Brown Suede Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/p/802/213__25302.jpg",
    file_size: 23101,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1134,
    image_id: 3222,
    sort_order: 1,
    is_thumbnail: null,
    sku: "F019",
    name: "Chloe White Chameleon Chair (Full Cover)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/700/57__03862.jpg",
    file_size: 72645,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1134,
    image_id: 3223,
    sort_order: 5,
    is_thumbnail: null,
    sku: "F019",
    name: "Chloe White Chameleon Chair (Full Cover)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/z/971/60__52638.jpg",
    file_size: 49459,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1134,
    image_id: 3224,
    sort_order: 3,
    is_thumbnail: null,
    sku: "F019",
    name: "Chloe White Chameleon Chair (Full Cover)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/y/593/58__04444.jpg",
    file_size: 45779,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1134,
    image_id: 3225,
    sort_order: 2,
    is_thumbnail: null,
    sku: "F019",
    name: "Chloe White Chameleon Chair (Full Cover)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/097/Seating_product_images_website___22816.jpg",
    file_size: 80044,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1134,
    image_id: 3226,
    sort_order: 4,
    is_thumbnail: null,
    sku: "F019",
    name: "Chloe White Chameleon Chair (Full Cover)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/l/325/59__54477.jpg",
    file_size: 44608,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1134,
    image_id: 3392,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "F019",
    name: "Chloe White Chameleon Chair (Full Cover)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/n/779/211__39336.jpg",
    file_size: 24025,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1134,
    image_id: 3393,
    sort_order: 6,
    is_thumbnail: null,
    sku: "F019",
    name: "Chloe White Chameleon Chair (Full Cover)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/j/413/210__89305.jpg",
    file_size: 22574,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1135,
    image_id: 3390,
    sort_order: 1,
    is_thumbnail: null,
    sku: "F025",
    name: "Chameleon Charcoal Suede Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/m/739/209__20598.jpg",
    file_size: 22676,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1135,
    image_id: 3391,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "F025",
    name: "Chameleon Charcoal Suede Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/198/208__80192.jpg",
    file_size: 22885,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1136,
    image_id: 3203,
    sort_order: 3,
    is_thumbnail: null,
    sku: "F018A",
    name: "Chloe Ivory Chameleon Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/l/405/38__79703.jpg",
    file_size: 54122,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1136,
    image_id: 3204,
    sort_order: 1,
    is_thumbnail: null,
    sku: "F018A",
    name: "Chloe Ivory Chameleon Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/562/37__36345.jpg",
    file_size: 64043,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1300,
    image_id: 3216,
    sort_order: 1,
    is_thumbnail: null,
    sku: "ST001",
    name: "Salt White Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/849/Untitled_design_6__64404.jpg",
    file_size: 60313,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1300,
    image_id: 4178,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "ST001",
    name: "Salt White Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/v/595/Untitled_design_7__66804.png",
    file_size: 30245,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1366,
    image_id: 3496,
    sort_order: 1,
    is_thumbnail: null,
    sku: "PALMCOF",
    name: "Palm Coffee Table / Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/q/089/42__19713.png",
    file_size: null,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1367,
    image_id: 3493,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "BS1003",
    name: "Volt Barstool Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/f/177/44__71781.png",
    file_size: 127061,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1367,
    image_id: 3494,
    sort_order: 1,
    is_thumbnail: null,
    sku: "BS1003",
    name: "Volt Barstool Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/308/48__66684.png",
    file_size: 910822,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1368,
    image_id: 3491,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "VOLTW",
    name: "Volt Barstool White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/q/824/45__34576.png",
    file_size: 125688,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1368,
    image_id: 3492,
    sort_order: 1,
    is_thumbnail: null,
    sku: "VOLTW",
    name: "Volt Barstool White",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/l/080/43__85695.png",
    file_size: null,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1369,
    image_id: 3489,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "VOLTBCH",
    name: "Volt Chair Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/a/085/46__00629.png",
    file_size: 187248,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1369,
    image_id: 3490,
    sort_order: 1,
    is_thumbnail: null,
    sku: "VOLTBCH",
    name: "Volt Chair Black",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/490/47__81188.png",
    file_size: 1081998,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1400,
    image_id: 3622,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "BS1004",
    name: "Zoey Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/t/702/3__20550.png",
    file_size: 102637,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1400,
    image_id: 3759,
    sort_order: 1,
    is_thumbnail: null,
    sku: "BS1004",
    name: "Zoey Bar Stool",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/a/881/2__75969__88157.png",
    file_size: 433052,
    width: 1080,
    height: 1080,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1472,
    image_id: 3761,
    sort_order: 4,
    is_thumbnail: null,
    sku: "210224",
    name: "Alice Bar Stool Rose Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/d/711/Alice_Barchair_4__38852__12479.jpg",
    file_size: 55873,
    width: 1334,
    height: 1334,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1472,
    image_id: 3763,
    sort_order: 6,
    is_thumbnail: null,
    sku: "210224",
    name: "Alice Bar Stool Rose Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/778/Alice_Barchair_1__93830__64324.jpg",
    file_size: 78024,
    width: 1334,
    height: 1334,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1472,
    image_id: 3765,
    sort_order: 8,
    is_thumbnail: null,
    sku: "210224",
    name: "Alice Bar Stool Rose Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/q/053/Alice_Barchair_3__81599__95778.jpg",
    file_size: 85067,
    width: 1334,
    height: 1334,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1472,
    image_id: 3768,
    sort_order: 9,
    is_thumbnail: null,
    sku: "210224",
    name: "Alice Bar Stool Rose Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/a/592/Alice_Barchair_2__72986__58162.jpg",
    file_size: 84624,
    width: 1334,
    height: 1334,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1472,
    image_id: 3769,
    sort_order: 1,
    is_thumbnail: null,
    sku: "210224",
    name: "Alice Bar Stool Rose Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/n/803/Alice_Barchair__10917__68097.jpg",
    file_size: 87252,
    width: 1883,
    height: 2000,
    excesive_file_size_gt_70_kb: 1,
    not_square: 1,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1472,
    image_id: 4300,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "210224",
    name: "Alice Bar Stool Rose Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/h/305/Alice_5__73647.jpg",
    file_size: 146140,
    width: 3062,
    height: 3062,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1472,
    image_id: 4301,
    sort_order: 2,
    is_thumbnail: null,
    sku: "210224",
    name: "Alice Bar Stool Rose Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/r/267/Alice_4__95537.jpg",
    file_size: 144619,
    width: 3062,
    height: 3062,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1472,
    image_id: 4302,
    sort_order: 5,
    is_thumbnail: null,
    sku: "210224",
    name: "Alice Bar Stool Rose Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/q/318/Alice_2__10338.jpg",
    file_size: 139226,
    width: 3062,
    height: 3062,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1472,
    image_id: 4303,
    sort_order: 7,
    is_thumbnail: null,
    sku: "210224",
    name: "Alice Bar Stool Rose Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/v/677/Alice_3__81700.jpg",
    file_size: 156686,
    width: 3062,
    height: 3062,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1472,
    image_id: 4304,
    sort_order: 3,
    is_thumbnail: null,
    sku: "210224",
    name: "Alice Bar Stool Rose Gold",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/m/871/Alice_1__09210.jpg",
    file_size: 139990,
    width: 3062,
    height: 3062,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1473,
    image_id: 3770,
    sort_order: 0,
    is_thumbnail: 1,
    sku: "230224",
    name: "Ronda Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/c/680/Ronda_-_Stack_Chair_-_Rattan__93503__57996.jpg",
    file_size: 103230,
    width: 2000,
    height: 2000,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1473,
    image_id: 3771,
    sort_order: 1,
    is_thumbnail: null,
    sku: "230224",
    name: "Ronda Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/011/Ronda-_Stack_Chair_Octopus_Dinner_Table_-_Folding_Table_-_Open_House_Days_2023__23686__64445.jpg",
    file_size: 1060405,
    width: 3392,
    height: 3392,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1473,
    image_id: 3772,
    sort_order: 2,
    is_thumbnail: null,
    sku: "230224",
    name: "Ronda Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/g/689/Ronda_-_Stack_Chair_-_Velvet_Black_Seat__09582__41496.jpg",
    file_size: 96721,
    width: 2000,
    height: 2000,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1473,
    image_id: 3773,
    sort_order: 3,
    is_thumbnail: null,
    sku: "230224",
    name: "Ronda Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/o/083/Ronda_-_Stack_Chair___07556__75527.jpg",
    file_size: 49587,
    width: 1207,
    height: 1207,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1473,
    image_id: 3774,
    sort_order: 4,
    is_thumbnail: null,
    sku: "230224",
    name: "Ronda Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/e/314/Ronda_-_Stack_Chair_2__35766__56118.jpg",
    file_size: 93028,
    width: 1166,
    height: 1166,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1473,
    image_id: 3775,
    sort_order: 5,
    is_thumbnail: null,
    sku: "230224",
    name: "Ronda Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/o/915/Ronda-_Stack_Chair_Octopus_Dinner_Table_-_Folding_Table_-_Open_House_Days_2023_1__91229__49085.jpg",
    file_size: 159774,
    width: 1280,
    height: 1280,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1473,
    image_id: 3776,
    sort_order: 6,
    is_thumbnail: null,
    sku: "230224",
    name: "Ronda Chair",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/k/709/Ronda-_Stack_Chair_Octopus_Dinner_Table_-_Folding_Table_-_Open_House_Days_2023_2__93307__46327.jpg",
    file_size: 131290,
    width: 1280,
    height: 1280,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1601,
    image_id: 4661,
    sort_order: 1,
    is_thumbnail: null,
    sku: "1083",
    name: "Smartie Bench White (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/z/966/137__72921.1675708896.1280.1280__03055.jpg",
    file_size: 131187,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: 1,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
  {
    product_id: 1601,
    image_id: 4662,
    sort_order: 2,
    is_thumbnail: null,
    sku: "1083",
    name: "Smartie Bench White (5 seater)",
    image_url:
      "https://store-jqwssthhhd.mybigcommerce.com/product_images/n/610/138__31274.1675708896.1280.1280__24667.jpg",
    file_size: 59086,
    width: 1028,
    height: 1028,
    excesive_file_size_gt_70_kb: null,
    not_square: null,
    excessive_file_dimensions: 1,
    insufficent_file_dimensions: null,
  },
].sort((a, b) => (b.file_size || 0)  - (a.file_size || 0));

async function main() {
  try {
    config("ch");

    console.log(`${data.length} images to compress`);

    await new Promise((resolve) => setTimeout(resolve, 5000));

    let totalOriginalSize = 0;
    let totalCompressedSize = 0;

    for (let i = 1; i < data.length; i++) {
      console.log(i, data.length);
      const row = data[i];
      console.log(`updating image for product ${row.product_id}`);
      console.log(row.image_url);

      // Example usage
      const res = await compressImage(row.image_url);
      totalOriginalSize += res.originalSize;
      totalCompressedSize += res.compressedSize;

      console.log(`deleting product image...`);
      try {
        await deleteProductImage(row.product_id, row.image_id);
      } catch {
        console.log(`could not delete product image for ${row.product_id}`);
      }

      await createProductImageFromBuffer(
        row.product_id,
        res.compressedBuffer,
        row.name + "image",
        Boolean(row.is_thumbnail),
        row.sort_order
      );

      fs.appendFileSync(
        path.resolve(__dirname, "image-compression.log"),
        `Compressed image for product(${row.product_id}) sku:${
          row.sku
        } reduced size by  ${formatBytes(
          res.originalSize - res.compressedSize
        )}`,
        { encoding: "utf-8" }
      );
      console.log();
    }
    fs.appendFileSync(
      path.resolve(__dirname, "image-compression.log"),
      `${data.length} images compressed in total saving ${formatBytes(
        totalOriginalSize - totalCompressedSize
      )} in unnecessary download data for users`,
      { encoding: "utf-8" }
    );
  } catch (err) {
    console.log(err);
  }
}
main();
