import { deleteCustomField } from "../../functions/custom-fields/deleteCustomField";
import { getCustomField } from "../../functions/custom-fields/getCustomField";
import { CustomField } from "../../functions/custom-fields/getCustomFields";
import { updateCustomField } from "../../functions/custom-fields/updateCustomField";

let data = [
  {
    product_id: 163,
    product_name: "Folding Chair Burgundy",
    custom_field_id: 686,
    custom_field_name: "Seat Height",
    custom_field_value: "44cm",
    delete: "FALSE",
  },
  {
    product_id: 163,
    product_name: "Folding Chair Burgundy",
    custom_field_id: 687,
    custom_field_name: "Material",
    custom_field_value: "Polypropylene seat and back",
    delete: "FALSE",
  },
  {
    product_id: 163,
    product_name: "Folding Chair Burgundy",
    custom_field_id: 688,
    custom_field_name: "Colour",
    custom_field_value: "Blue or Burgundy or Teal",
    delete: "FALSE",
  },
  {
    product_id: 163,
    product_name: "Folding Chair Burgundy",
    custom_field_id: 689,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable and Foldable",
    delete: "FALSE",
  },
  {
    product_id: 163,
    product_name: "Folding Chair Burgundy",
    custom_field_id: 690,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 171,
    product_name: "Regatta Outdoor Bistro Chair",
    custom_field_id: 691,
    custom_field_name: "Seat Height",
    custom_field_value: "44cm",
    delete: "FALSE",
  },
  {
    product_id: 171,
    product_name: "Regatta Outdoor Bistro Chair",
    custom_field_id: 692,
    custom_field_name: "Material",
    custom_field_value: "Chrome and polypropelene seat",
    delete: "FALSE",
  },
  {
    product_id: 171,
    product_name: "Regatta Outdoor Bistro Chair",
    custom_field_id: 693,
    custom_field_name: "Colour",
    custom_field_value: "Rattan",
    delete: "FALSE",
  },
  {
    product_id: 171,
    product_name: "Regatta Outdoor Bistro Chair",
    custom_field_id: 694,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 10 high",
    delete: "FALSE",
  },
  {
    product_id: 171,
    product_name: "Regatta Outdoor Bistro Chair",
    custom_field_id: 695,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 246,
    product_name: "Padded Banquet Chair Blue",
    custom_field_id: 701,
    custom_field_name: "Seat Height",
    custom_field_value: "47cm",
    delete: "FALSE",
  },
  {
    product_id: 246,
    product_name: "Padded Banquet Chair Blue",
    custom_field_id: 702,
    custom_field_name: "Material",
    custom_field_value: "Aluminium Frame with Fabric Seat Pad and Back",
    delete: "FALSE",
  },
  {
    product_id: 246,
    product_name: "Padded Banquet Chair Blue",
    custom_field_id: 703,
    custom_field_name: "Colour",
    custom_field_value: "Red or Blue",
    delete: "FALSE",
  },
  {
    product_id: 246,
    product_name: "Padded Banquet Chair Blue",
    custom_field_id: 704,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 10 high",
    delete: "FALSE",
  },
  {
    product_id: 246,
    product_name: "Padded Banquet Chair Blue",
    custom_field_id: 705,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 281,
    product_name: "Star Bench Illuminated",
    custom_field_id: 706,
    custom_field_name: "Seat Height",
    custom_field_value: "43cm",
    delete: "FALSE",
  },
  {
    product_id: 281,
    product_name: "Star Bench Illuminated",
    custom_field_id: 707,
    custom_field_name: "Material",
    custom_field_value: "Polyethylene",
    delete: "FALSE",
  },
  {
    product_id: 281,
    product_name: "Star Bench Illuminated",
    custom_field_id: 708,
    custom_field_name: "Colour",
    custom_field_value: "Variable",
    delete: "FALSE",
  },
  {
    product_id: 281,
    product_name: "Star Bench Illuminated",
    custom_field_id: 709,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or Foldable",
    delete: "FALSE",
  },
  {
    product_id: 281,
    product_name: "Star Bench Illuminated",
    custom_field_id: 710,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 297,
    product_name: "Chiavari Chair Black",
    custom_field_id: 646,
    custom_field_name: "Seat Height",
    custom_field_value: "45cm",
    delete: "FALSE",
  },
  {
    product_id: 297,
    product_name: "Chiavari Chair Black",
    custom_field_id: 647,
    custom_field_name: "Material",
    custom_field_value: "Black Wooden Frame",
    delete: "FALSE",
  },
  {
    product_id: 297,
    product_name: "Chiavari Chair Black",
    custom_field_id: 648,
    custom_field_name: "Colour",
    custom_field_value: "Black",
    delete: "FALSE",
  },
  {
    product_id: 297,
    product_name: "Chiavari Chair Black",
    custom_field_id: 649,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 8 high",
    delete: "FALSE",
  },
  {
    product_id: 297,
    product_name: "Chiavari Chair Black",
    custom_field_id: 650,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 303,
    product_name: "Bentwood Rustic Oak Chair",
    custom_field_id: 711,
    custom_field_name: "Seat Height",
    custom_field_value: "45cm",
    delete: "FALSE",
  },
  {
    product_id: 303,
    product_name: "Bentwood Rustic Oak Chair",
    custom_field_id: 712,
    custom_field_name: "Material",
    custom_field_value: "Oak",
    delete: "FALSE",
  },
  {
    product_id: 303,
    product_name: "Bentwood Rustic Oak Chair",
    custom_field_id: 713,
    custom_field_name: "Colour",
    custom_field_value: "Wood",
    delete: "FALSE",
  },
  {
    product_id: 303,
    product_name: "Bentwood Rustic Oak Chair",
    custom_field_id: 714,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 10 high",
    delete: "FALSE",
  },
  {
    product_id: 303,
    product_name: "Bentwood Rustic Oak Chair",
    custom_field_id: 715,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 316,
    product_name: "Aurora Bar Stool White",
    custom_field_id: 716,
    custom_field_name: "Seat Height",
    custom_field_value: "63cm -77cm",
    delete: "FALSE",
  },
  {
    product_id: 316,
    product_name: "Aurora Bar Stool White",
    custom_field_id: 717,
    custom_field_name: "Material",
    custom_field_value: "Chrome base with white faux leather seat and back",
    delete: "FALSE",
  },
  {
    product_id: 316,
    product_name: "Aurora Bar Stool White",
    custom_field_id: 718,
    custom_field_name: "Colour",
    custom_field_value: "White",
    delete: "FALSE",
  },
  {
    product_id: 316,
    product_name: "Aurora Bar Stool White",
    custom_field_id: 719,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or foldable",
    delete: "FALSE",
  },
  {
    product_id: 316,
    product_name: "Aurora Bar Stool White",
    custom_field_id: 720,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 320,
    product_name: "Wow bench - Saffron yellow",
    custom_field_id: 721,
    custom_field_name: "Seat Height",
    custom_field_value: "43cm",
    delete: "FALSE",
  },
  {
    product_id: 320,
    product_name: "Wow bench - Saffron yellow",
    custom_field_id: 722,
    custom_field_name: "Material",
    custom_field_value: "Polyethylene",
    delete: "FALSE",
  },
  {
    product_id: 320,
    product_name: "Wow bench - Saffron yellow",
    custom_field_id: 723,
    custom_field_name: "Colour",
    custom_field_value: "Yellow",
    delete: "FALSE",
  },
  {
    product_id: 320,
    product_name: "Wow bench - Saffron yellow",
    custom_field_id: 724,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable not Foldable",
    delete: "FALSE",
  },
  {
    product_id: 320,
    product_name: "Wow bench - Saffron yellow",
    custom_field_id: 725,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 334,
    product_name: "Chiavari Chair Limewash (deluxe)",
    custom_field_id: 651,
    custom_field_name: "Seat Height",
    custom_field_value: "45cm",
    delete: "FALSE",
  },
  {
    product_id: 334,
    product_name: "Chiavari Chair Limewash (deluxe)",
    custom_field_id: 652,
    custom_field_name: "Material",
    custom_field_value: "Beechwood frame with limewash finish",
    delete: "FALSE",
  },
  {
    product_id: 334,
    product_name: "Chiavari Chair Limewash (deluxe)",
    custom_field_id: 653,
    custom_field_name: "Colour",
    custom_field_value: "Limewash",
    delete: "FALSE",
  },
  {
    product_id: 334,
    product_name: "Chiavari Chair Limewash (deluxe)",
    custom_field_id: 654,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 10 high",
    delete: "FALSE",
  },
  {
    product_id: 334,
    product_name: "Chiavari Chair Limewash (deluxe)",
    custom_field_id: 655,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 341,
    product_name: "Zeus Bar Stool Black",
    custom_field_id: 731,
    custom_field_name: "Seat Height",
    custom_field_value: "75cm",
    delete: "FALSE",
  },
  {
    product_id: 341,
    product_name: "Zeus Bar Stool Black",
    custom_field_id: 732,
    custom_field_name: "Material",
    custom_field_value: "Chrome frame with faux leather seat pad",
    delete: "FALSE",
  },
  {
    product_id: 341,
    product_name: "Zeus Bar Stool Black",
    custom_field_id: 733,
    custom_field_name: "Colour",
    custom_field_value: "Black seat pad",
    delete: "FALSE",
  },
  {
    product_id: 341,
    product_name: "Zeus Bar Stool Black",
    custom_field_id: 734,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 2 high",
    delete: "FALSE",
  },
  {
    product_id: 341,
    product_name: "Zeus Bar Stool Black",
    custom_field_id: 735,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 343,
    product_name: "Mighty B Beanbag",
    custom_field_id: 737,
    custom_field_name: "Material",
    custom_field_value: "Waterproof Polyester",
    delete: "FALSE",
  },
  {
    product_id: 343,
    product_name: "Mighty B Beanbag",
    custom_field_id: 738,
    custom_field_name: "Colour",
    custom_field_value: "Lime / Red / Grey / Black",
    delete: "FALSE",
  },
  {
    product_id: 343,
    product_name: "Mighty B Beanbag",
    custom_field_id: 739,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or Foldable",
    delete: "FALSE",
  },
  {
    product_id: 343,
    product_name: "Mighty B Beanbag",
    custom_field_id: 740,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 388,
    product_name: "Zeus Bar Stool with Royal Blue Pad Cover",
    custom_field_id: 751,
    custom_field_name: "Seat Height",
    custom_field_value: "75cm",
    delete: "FALSE",
  },
  {
    product_id: 388,
    product_name: "Zeus Bar Stool with Royal Blue Pad Cover",
    custom_field_id: 752,
    custom_field_name: "Material",
    custom_field_value: "Chrome frame with lycra seat pad",
    delete: "FALSE",
  },
  {
    product_id: 388,
    product_name: "Zeus Bar Stool with Royal Blue Pad Cover",
    custom_field_id: 753,
    custom_field_name: "Colour",
    custom_field_value: "Blue",
    delete: "FALSE",
  },
  {
    product_id: 388,
    product_name: "Zeus Bar Stool with Royal Blue Pad Cover",
    custom_field_id: 754,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 2 high",
    delete: "FALSE",
  },
  {
    product_id: 388,
    product_name: "Zeus Bar Stool with Royal Blue Pad Cover",
    custom_field_id: 755,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 424,
    product_name: "Wooden Picnic Bench",
    custom_field_id: 767,
    custom_field_name: "Material",
    custom_field_value: "Solid Wood",
    delete: "FALSE",
  },
  {
    product_id: 424,
    product_name: "Wooden Picnic Bench",
    custom_field_id: 768,
    custom_field_name: "Colour",
    custom_field_value: "Teak",
    delete: "FALSE",
  },
  {
    product_id: 424,
    product_name: "Wooden Picnic Bench",
    custom_field_id: 769,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or Foldable",
    delete: "FALSE",
  },
  {
    product_id: 424,
    product_name: "Wooden Picnic Bench",
    custom_field_id: 770,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 444,
    product_name: "Chiavari Bar Stool - Limewash",
    custom_field_id: 656,
    custom_field_name: "Seat Height",
    custom_field_value: "75cm",
    delete: "FALSE",
  },
  {
    product_id: 444,
    product_name: "Chiavari Bar Stool - Limewash",
    custom_field_id: 657,
    custom_field_name: "Material",
    custom_field_value: "Beechwood Frame with Limewash finish",
    delete: "FALSE",
  },
  {
    product_id: 444,
    product_name: "Chiavari Bar Stool - Limewash",
    custom_field_id: 658,
    custom_field_name: "Colour",
    custom_field_value: "Limewash",
    delete: "FALSE",
  },
  {
    product_id: 444,
    product_name: "Chiavari Bar Stool - Limewash",
    custom_field_id: 659,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 4 high",
    delete: "FALSE",
  },
  {
    product_id: 444,
    product_name: "Chiavari Bar Stool - Limewash",
    custom_field_id: 660,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 479,
    product_name: "Highback Dining Chair White",
    custom_field_id: 8040,
    custom_field_name: "Seat Height",
    custom_field_value: "48cm/19in",
    delete: "FALSE",
  },
  {
    product_id: 479,
    product_name: "Highback Dining Chair White",
    custom_field_id: 8041,
    custom_field_name: "Material",
    custom_field_value: "White vinyl cover with silver powder coated frame",
    delete: "FALSE",
  },
  {
    product_id: 479,
    product_name: "Highback Dining Chair White",
    custom_field_id: 8042,
    custom_field_name: "Colour",
    custom_field_value: "White",
    delete: "FALSE",
  },
  {
    product_id: 479,
    product_name: "Highback Dining Chair White",
    custom_field_id: 8043,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable (stacks 10 high)",
    delete: "FALSE",
  },
  {
    product_id: 479,
    product_name: "Highback Dining Chair White",
    custom_field_id: 8044,
    custom_field_name: "Usage",
    custom_field_value: "Corporate events, private parties, banqueting events",
    delete: "FALSE",
  },
  {
    product_id: 486,
    product_name: "Button Bar Stool Black",
    custom_field_id: 776,
    custom_field_name: "Seat Height",
    custom_field_value: "58cm -73cm",
    delete: "FALSE",
  },
  {
    product_id: 486,
    product_name: "Button Bar Stool Black",
    custom_field_id: 777,
    custom_field_name: "Material",
    custom_field_value: "Chrome Frame with faux leather chair pad",
    delete: "FALSE",
  },
  {
    product_id: 486,
    product_name: "Button Bar Stool Black",
    custom_field_id: 778,
    custom_field_name: "Colour",
    custom_field_value: "Black",
    delete: "FALSE",
  },
  {
    product_id: 486,
    product_name: "Button Bar Stool Black",
    custom_field_id: 779,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or Foldable",
    delete: "FALSE",
  },
  {
    product_id: 486,
    product_name: "Button Bar Stool Black",
    custom_field_id: 780,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 491,
    product_name: "Chiavari Chair Gold",
    custom_field_id: 661,
    custom_field_name: "Seat Height",
    custom_field_value: "45cm",
    delete: "FALSE",
  },
  {
    product_id: 491,
    product_name: "Chiavari Chair Gold",
    custom_field_id: 662,
    custom_field_name: "Material",
    custom_field_value: "Beechwood Frame",
    delete: "FALSE",
  },
  {
    product_id: 491,
    product_name: "Chiavari Chair Gold",
    custom_field_id: 663,
    custom_field_name: "Colour",
    custom_field_value: "Gold",
    delete: "FALSE",
  },
  {
    product_id: 491,
    product_name: "Chiavari Chair Gold",
    custom_field_id: 664,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 8 high",
    delete: "FALSE",
  },
  {
    product_id: 491,
    product_name: "Chiavari Chair Gold",
    custom_field_id: 665,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 493,
    product_name: "Zeus Bar Stool with Silver Pad Cover",
    custom_field_id: 781,
    custom_field_name: "Seat Height",
    custom_field_value: "75cm",
    delete: "FALSE",
  },
  {
    product_id: 493,
    product_name: "Zeus Bar Stool with Silver Pad Cover",
    custom_field_id: 782,
    custom_field_name: "Material",
    custom_field_value: "Chrome frame with lycra seat pad",
    delete: "FALSE",
  },
  {
    product_id: 493,
    product_name: "Zeus Bar Stool with Silver Pad Cover",
    custom_field_id: 783,
    custom_field_name: "Colour",
    custom_field_value: "Silver",
    delete: "FALSE",
  },
  {
    product_id: 493,
    product_name: "Zeus Bar Stool with Silver Pad Cover",
    custom_field_id: 784,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 2 high",
    delete: "FALSE",
  },
  {
    product_id: 493,
    product_name: "Zeus Bar Stool with Silver Pad Cover",
    custom_field_id: 785,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 496,
    product_name: "Pop Bench",
    custom_field_id: 786,
    custom_field_name: "Seat Height",
    custom_field_value: "42cm",
    delete: "FALSE",
  },
  {
    product_id: 496,
    product_name: "Pop Bench",
    custom_field_id: 787,
    custom_field_name: "Material",
    custom_field_value: "Polyethylene",
    delete: "FALSE",
  },
  {
    product_id: 496,
    product_name: "Pop Bench",
    custom_field_id: 788,
    custom_field_name: "Colour",
    custom_field_value:
      "Jet Black, Flame Red, Saffron Yellow, Lime Green / Milky White",
    delete: "FALSE",
  },
  {
    product_id: 496,
    product_name: "Pop Bench",
    custom_field_id: 789,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable",
    delete: "FALSE",
  },
  {
    product_id: 496,
    product_name: "Pop Bench",
    custom_field_id: 790,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 533,
    product_name: "All Seasons Padded Chair",
    custom_field_id: 791,
    custom_field_name: "Seat Height",
    custom_field_value: "46cm",
    delete: "FALSE",
  },
  {
    product_id: 533,
    product_name: "All Seasons Padded Chair",
    custom_field_id: 792,
    custom_field_name: "Material",
    custom_field_value: "Aluminium frame with fabric seat pad and back",
    delete: "FALSE",
  },
  {
    product_id: 533,
    product_name: "All Seasons Padded Chair",
    custom_field_id: 793,
    custom_field_name: "Colour",
    custom_field_value: "Gold",
    delete: "FALSE",
  },
  {
    product_id: 533,
    product_name: "All Seasons Padded Chair",
    custom_field_id: 794,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 10 high",
    delete: "FALSE",
  },
  {
    product_id: 533,
    product_name: "All Seasons Padded Chair",
    custom_field_id: 795,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 544,
    product_name: "Half Moon Bench Illuminated",
    custom_field_id: 796,
    custom_field_name: "Seat Height",
    custom_field_value: "43cm",
    delete: "FALSE",
  },
  {
    product_id: 544,
    product_name: "Half Moon Bench Illuminated",
    custom_field_id: 797,
    custom_field_name: "Material",
    custom_field_value: "Polyethylene",
    delete: "FALSE",
  },
  {
    product_id: 544,
    product_name: "Half Moon Bench Illuminated",
    custom_field_id: 798,
    custom_field_name: "Colour",
    custom_field_value: "Variable",
    delete: "FALSE",
  },
  {
    product_id: 544,
    product_name: "Half Moon Bench Illuminated",
    custom_field_id: 799,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or Foldable",
    delete: "FALSE",
  },
  {
    product_id: 544,
    product_name: "Half Moon Bench Illuminated",
    custom_field_id: 800,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 568,
    product_name: "Snake Bench Illuminated",
    custom_field_id: 811,
    custom_field_name: "Seat Height",
    custom_field_value: "43cm",
    delete: "FALSE",
  },
  {
    product_id: 568,
    product_name: "Snake Bench Illuminated",
    custom_field_id: 812,
    custom_field_name: "Material",
    custom_field_value: "Polyethylene",
    delete: "FALSE",
  },
  {
    product_id: 568,
    product_name: "Snake Bench Illuminated",
    custom_field_id: 813,
    custom_field_name: "Colour",
    custom_field_value: "Variable",
    delete: "FALSE",
  },
  {
    product_id: 568,
    product_name: "Snake Bench Illuminated",
    custom_field_id: 814,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or Foldable",
    delete: "FALSE",
  },
  {
    product_id: 568,
    product_name: "Snake Bench Illuminated",
    custom_field_id: 815,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 582,
    product_name: "Wow bench- Lime green",
    custom_field_id: 826,
    custom_field_name: "Seat Height",
    custom_field_value: "43cm",
    delete: "FALSE",
  },
  {
    product_id: 582,
    product_name: "Wow bench- Lime green",
    custom_field_id: 827,
    custom_field_name: "Material",
    custom_field_value: "Polyethylene",
    delete: "FALSE",
  },
  {
    product_id: 582,
    product_name: "Wow bench- Lime green",
    custom_field_id: 828,
    custom_field_name: "Colour",
    custom_field_value: "Green",
    delete: "FALSE",
  },
  {
    product_id: 582,
    product_name: "Wow bench- Lime green",
    custom_field_id: 829,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable not Foldable",
    delete: "FALSE",
  },
  {
    product_id: 582,
    product_name: "Wow bench- Lime green",
    custom_field_id: 830,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 630,
    product_name: "Candy Lounge Armchair - Soft yellow",
    custom_field_id: 2027,
    custom_field_name: "Seat Height",
    custom_field_value: "37cm",
    delete: "FALSE",
  },
  {
    product_id: 630,
    product_name: "Candy Lounge Armchair - Soft yellow",
    custom_field_id: 2028,
    custom_field_name: "Material",
    custom_field_value: "Polyurethane",
    delete: "FALSE",
  },
  {
    product_id: 630,
    product_name: "Candy Lounge Armchair - Soft yellow",
    custom_field_id: 2029,
    custom_field_name: "Colour",
    custom_field_value: "Yellow",
    delete: "FALSE",
  },
  {
    product_id: 630,
    product_name: "Candy Lounge Armchair - Soft yellow",
    custom_field_id: 2030,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or foldable",
    delete: "FALSE",
  },
  {
    product_id: 630,
    product_name: "Candy Lounge Armchair - Soft yellow",
    custom_field_id: 2031,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 650,
    product_name: "Chameleon Chair Silver Back",
    custom_field_id: 831,
    custom_field_name: "Seat Height",
    custom_field_value: "47cm",
    delete: "FALSE",
  },
  {
    product_id: 650,
    product_name: "Chameleon Chair Silver Back",
    custom_field_id: 832,
    custom_field_name: "Material",
    custom_field_value: "Steel Frame with Fabric Seat Pad",
    delete: "FALSE",
  },
  {
    product_id: 650,
    product_name: "Chameleon Chair Silver Back",
    custom_field_id: 833,
    custom_field_name: "Colour",
    custom_field_value: "Silver Frame, chair pad colour optional",
    delete: "FALSE",
  },
  {
    product_id: 650,
    product_name: "Chameleon Chair Silver Back",
    custom_field_id: 834,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 6 high",
    delete: "FALSE",
  },
  {
    product_id: 650,
    product_name: "Chameleon Chair Silver Back",
    custom_field_id: 835,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 657,
    product_name: "Button Bar Stool White",
    custom_field_id: 836,
    custom_field_name: "Seat Height",
    custom_field_value: "58cm -73cm",
    delete: "FALSE",
  },
  {
    product_id: 657,
    product_name: "Button Bar Stool White",
    custom_field_id: 837,
    custom_field_name: "Material",
    custom_field_value: "Chrome base with faux leather pad",
    delete: "FALSE",
  },
  {
    product_id: 657,
    product_name: "Button Bar Stool White",
    custom_field_id: 838,
    custom_field_name: "Colour",
    custom_field_value: "White",
    delete: "FALSE",
  },
  {
    product_id: 657,
    product_name: "Button Bar Stool White",
    custom_field_id: 839,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not foldable or stackable",
    delete: "FALSE",
  },
  {
    product_id: 657,
    product_name: "Button Bar Stool White",
    custom_field_id: 840,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 680,
    product_name: "Folding White Chair",
    custom_field_id: 851,
    custom_field_name: "Seat Height",
    custom_field_value: "46cm",
    delete: "FALSE",
  },
  {
    product_id: 680,
    product_name: "Folding White Chair",
    custom_field_id: 852,
    custom_field_name: "Material",
    custom_field_value: "Lacquered Resin",
    delete: "FALSE",
  },
  {
    product_id: 680,
    product_name: "Folding White Chair",
    custom_field_id: 853,
    custom_field_name: "Colour",
    custom_field_value: "White",
    delete: "FALSE",
  },
  {
    product_id: 680,
    product_name: "Folding White Chair",
    custom_field_id: 854,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Foldable and Stackable",
    delete: "FALSE",
  },
  {
    product_id: 680,
    product_name: "Folding White Chair",
    custom_field_id: 855,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 760,
    product_name: "Children's Wooden Picnic Bench",
    custom_field_id: 872,
    custom_field_name: "Material",
    custom_field_value: "Solid Acacia",
    delete: "FALSE",
  },
  {
    product_id: 760,
    product_name: "Children's Wooden Picnic Bench",
    custom_field_id: 873,
    custom_field_name: "Colour",
    custom_field_value: "Wood",
    delete: "FALSE",
  },
  {
    product_id: 760,
    product_name: "Children's Wooden Picnic Bench",
    custom_field_id: 874,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or foldable",
    delete: "FALSE",
  },
  {
    product_id: 760,
    product_name: "Children's Wooden Picnic Bench",
    custom_field_id: 875,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 792,
    product_name: "Chiavari Chair Mahogany",
    custom_field_id: 666,
    custom_field_name: "Seat Height",
    custom_field_value: "45cm",
    delete: "FALSE",
  },
  {
    product_id: 792,
    product_name: "Chiavari Chair Mahogany",
    custom_field_id: 667,
    custom_field_name: "Material",
    custom_field_value: "Mahogany Frame",
    delete: "FALSE",
  },
  {
    product_id: 792,
    product_name: "Chiavari Chair Mahogany",
    custom_field_id: 668,
    custom_field_name: "Colour",
    custom_field_value: "Mahogany",
    delete: "FALSE",
  },
  {
    product_id: 792,
    product_name: "Chiavari Chair Mahogany",
    custom_field_id: 669,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 8 high",
    delete: "FALSE",
  },
  {
    product_id: 792,
    product_name: "Chiavari Chair Mahogany",
    custom_field_id: 670,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 810,
    product_name: "Milan High Back Bar Stool - Black",
    custom_field_id: 896,
    custom_field_name: "Seat Height",
    custom_field_value: "75cm",
    delete: "FALSE",
  },
  {
    product_id: 810,
    product_name: "Milan High Back Bar Stool - Black",
    custom_field_id: 897,
    custom_field_name: "Material",
    custom_field_value: "Polypropylene Seat and Back",
    delete: "FALSE",
  },
  {
    product_id: 810,
    product_name: "Milan High Back Bar Stool - Black",
    custom_field_id: 898,
    custom_field_name: "Colour",
    custom_field_value: "Black",
    delete: "FALSE",
  },
  {
    product_id: 810,
    product_name: "Milan High Back Bar Stool - Black",
    custom_field_id: 899,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 6 high",
    delete: "FALSE",
  },
  {
    product_id: 810,
    product_name: "Milan High Back Bar Stool - Black",
    custom_field_id: 900,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 839,
    product_name: "Chiavari Limewash Chair (Standard)",
    custom_field_id: 671,
    custom_field_name: "Seat Height",
    custom_field_value: "45cm",
    delete: "FALSE",
  },
  {
    product_id: 839,
    product_name: "Chiavari Limewash Chair (Standard)",
    custom_field_id: 672,
    custom_field_name: "Material",
    custom_field_value: "Wooden Frame with limewash finish",
    delete: "FALSE",
  },
  {
    product_id: 839,
    product_name: "Chiavari Limewash Chair (Standard)",
    custom_field_id: 673,
    custom_field_name: "Colour",
    custom_field_value: "Limewash",
    delete: "FALSE",
  },
  {
    product_id: 839,
    product_name: "Chiavari Limewash Chair (Standard)",
    custom_field_id: 674,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 8 high",
    delete: "FALSE",
  },
  {
    product_id: 839,
    product_name: "Chiavari Limewash Chair (Standard)",
    custom_field_id: 675,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 853,
    product_name: "Chiavari Chair Crystal with White Pad",
    custom_field_id: 676,
    custom_field_name: "Seat Height",
    custom_field_value: "44cm",
    delete: "FALSE",
  },
  {
    product_id: 853,
    product_name: "Chiavari Chair Crystal with White Pad",
    custom_field_id: 677,
    custom_field_name: "Material",
    custom_field_value: "Polycarbonate Resin Frame",
    delete: "FALSE",
  },
  {
    product_id: 853,
    product_name: "Chiavari Chair Crystal with White Pad",
    custom_field_id: 678,
    custom_field_name: "Colour",
    custom_field_value: "Clear",
    delete: "FALSE",
  },
  {
    product_id: 853,
    product_name: "Chiavari Chair Crystal with White Pad",
    custom_field_id: 679,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 6 high",
    delete: "FALSE",
  },
  {
    product_id: 853,
    product_name: "Chiavari Chair Crystal with White Pad",
    custom_field_id: 680,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 865,
    product_name: "Chameleon Chair Gold & Bronze with Black Legs",
    custom_field_id: 906,
    custom_field_name: "Seat Height",
    custom_field_value: "47cm",
    delete: "FALSE",
  },
  {
    product_id: 865,
    product_name: "Chameleon Chair Gold & Bronze with Black Legs",
    custom_field_id: 907,
    custom_field_name: "Material",
    custom_field_value: "Steel Frame with Fabric Seat Pad",
    delete: "FALSE",
  },
  {
    product_id: 865,
    product_name: "Chameleon Chair Gold & Bronze with Black Legs",
    custom_field_id: 908,
    custom_field_name: "Colour",
    custom_field_value: "Gold / Bronze Frame, chair pad colour optional",
    delete: "FALSE",
  },
  {
    product_id: 865,
    product_name: "Chameleon Chair Gold & Bronze with Black Legs",
    custom_field_id: 909,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 8 high",
    delete: "FALSE",
  },
  {
    product_id: 865,
    product_name: "Chameleon Chair Gold & Bronze with Black Legs",
    custom_field_id: 910,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 902,
    product_name: "Milan High Back Bar Stool - White",
    custom_field_id: 921,
    custom_field_name: "Seat Height",
    custom_field_value: "75cm",
    delete: "FALSE",
  },
  {
    product_id: 902,
    product_name: "Milan High Back Bar Stool - White",
    custom_field_id: 922,
    custom_field_name: "Material",
    custom_field_value: "Polypropylene Seat and Chrome Frame",
    delete: "FALSE",
  },
  {
    product_id: 902,
    product_name: "Milan High Back Bar Stool - White",
    custom_field_id: 923,
    custom_field_name: "Colour",
    custom_field_value: "White",
    delete: "FALSE",
  },
  {
    product_id: 902,
    product_name: "Milan High Back Bar Stool - White",
    custom_field_id: 924,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 6 high",
    delete: "FALSE",
  },
  {
    product_id: 902,
    product_name: "Milan High Back Bar Stool - White",
    custom_field_id: 925,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 960,
    product_name: "Candy Ottoman Grey - Large",
    custom_field_id: 2186,
    custom_field_name: "Seat Height",
    custom_field_value: "40cm",
    delete: "FALSE",
  },
  {
    product_id: 960,
    product_name: "Candy Ottoman Grey - Large",
    custom_field_id: 2187,
    custom_field_name: "Material",
    custom_field_value: "Polyurethane",
    delete: "FALSE",
  },
  {
    product_id: 960,
    product_name: "Candy Ottoman Grey - Large",
    custom_field_id: 2188,
    custom_field_name: "Colour",
    custom_field_value: "Grey",
    delete: "FALSE",
  },
  {
    product_id: 960,
    product_name: "Candy Ottoman Grey - Large",
    custom_field_id: 2189,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or foldable",
    delete: "FALSE",
  },
  {
    product_id: 960,
    product_name: "Candy Ottoman Grey - Large",
    custom_field_id: 2190,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 968,
    product_name: "Traditional Wooden Deckchair Blue and White",
    custom_field_id: 936,
    custom_field_name: "Seat Height",
    custom_field_value: "43cm",
    delete: "FALSE",
  },
  {
    product_id: 968,
    product_name: "Traditional Wooden Deckchair Blue and White",
    custom_field_id: 937,
    custom_field_name: "Material",
    custom_field_value: "Timber framed with cotton seat",
    delete: "FALSE",
  },
  {
    product_id: 968,
    product_name: "Traditional Wooden Deckchair Blue and White",
    custom_field_id: 938,
    custom_field_name: "Colour",
    custom_field_value: "Blue & White block stripes",
    delete: "FALSE",
  },
  {
    product_id: 968,
    product_name: "Traditional Wooden Deckchair Blue and White",
    custom_field_id: 939,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable and Foldable",
    delete: "FALSE",
  },
  {
    product_id: 968,
    product_name: "Traditional Wooden Deckchair Blue and White",
    custom_field_id: 940,
    custom_field_name: "Usage",
    custom_field_value: "Indoor or Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 995,
    product_name: "Rustic  Wooden Bench with Foldable legs",
    custom_field_id: 942,
    custom_field_name: "Material",
    custom_field_value: "Pinewood",
    delete: "FALSE",
  },
  {
    product_id: 995,
    product_name: "Rustic  Wooden Bench with Foldable legs",
    custom_field_id: 943,
    custom_field_name: "Colour",
    custom_field_value: "Dark Wood",
    delete: "FALSE",
  },
  {
    product_id: 995,
    product_name: "Rustic  Wooden Bench with Foldable legs",
    custom_field_id: 944,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Foldable",
    delete: "FALSE",
  },
  {
    product_id: 995,
    product_name: "Rustic  Wooden Bench with Foldable legs",
    custom_field_id: 945,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 997,
    product_name: "Candy Ottoman Grey - Small",
    custom_field_id: 2210,
    custom_field_name: "Seat Height",
    custom_field_value: "40cm",
    delete: "FALSE",
  },
  {
    product_id: 997,
    product_name: "Candy Ottoman Grey - Small",
    custom_field_id: 2211,
    custom_field_name: "Material",
    custom_field_value: "Polyurethane",
    delete: "FALSE",
  },
  {
    product_id: 997,
    product_name: "Candy Ottoman Grey - Small",
    custom_field_id: 2212,
    custom_field_name: "Colour",
    custom_field_value: "Grey",
    delete: "FALSE",
  },
  {
    product_id: 997,
    product_name: "Candy Ottoman Grey - Small",
    custom_field_id: 2213,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or foldable",
    delete: "FALSE",
  },
  {
    product_id: 997,
    product_name: "Candy Ottoman Grey - Small",
    custom_field_id: 2214,
    custom_field_name: "Usage",
    custom_field_value: "Indoor/Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 1017,
    product_name: "Milano Conference Chair",
    custom_field_id: 951,
    custom_field_name: "Seat Height",
    custom_field_value: "43cm",
    delete: "FALSE",
  },
  {
    product_id: 1017,
    product_name: "Milano Conference Chair",
    custom_field_id: 952,
    custom_field_name: "Material",
    custom_field_value: "Chrome legs with fabric seat and back",
    delete: "FALSE",
  },
  {
    product_id: 1017,
    product_name: "Milano Conference Chair",
    custom_field_id: 953,
    custom_field_name: "Colour",
    custom_field_value: "Charcoal",
    delete: "FALSE",
  },
  {
    product_id: 1017,
    product_name: "Milano Conference Chair",
    custom_field_id: 954,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 10 high",
    delete: "FALSE",
  },
  {
    product_id: 1017,
    product_name: "Milano Conference Chair",
    custom_field_id: 955,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1019,
    product_name: "Office Chair Black",
    custom_field_id: 962,
    custom_field_name: "Material",
    custom_field_value: "Chrome base with black mesh material",
    delete: "FALSE",
  },
  {
    product_id: 1019,
    product_name: "Office Chair Black",
    custom_field_id: 963,
    custom_field_name: "Colour",
    custom_field_value: "Black",
    delete: "FALSE",
  },
  {
    product_id: 1019,
    product_name: "Office Chair Black",
    custom_field_id: 964,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or foldable",
    delete: "FALSE",
  },
  {
    product_id: 1019,
    product_name: "Office Chair Black",
    custom_field_id: 965,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1019,
    product_name: "Office Chair Black",
    custom_field_id: 8045,
    custom_field_name: "Seat Height",
    custom_field_value: "Adjustable",
    delete: "FALSE",
  },
  {
    product_id: 1037,
    product_name: "Cube White Bar Stool",
    custom_field_id: 996,
    custom_field_name: "Seat Height",
    custom_field_value: "79cm",
    delete: "FALSE",
  },
  {
    product_id: 1037,
    product_name: "Cube White Bar Stool",
    custom_field_id: 997,
    custom_field_name: "Material",
    custom_field_value: "Steel Frame with faux leather or bamboo seat pad",
    delete: "FALSE",
  },
  {
    product_id: 1037,
    product_name: "Cube White Bar Stool",
    custom_field_id: 998,
    custom_field_name: "Colour",
    custom_field_value: "White Frame with choice of seat pad",
    delete: "FALSE",
  },
  {
    product_id: 1037,
    product_name: "Cube White Bar Stool",
    custom_field_id: 999,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 8 high",
    delete: "FALSE",
  },
  {
    product_id: 1037,
    product_name: "Cube White Bar Stool",
    custom_field_id: 1000,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1039,
    product_name: "Cube Black Bar Stool",
    custom_field_id: 1006,
    custom_field_name: "Seat Height",
    custom_field_value: "79cm",
    delete: "FALSE",
  },
  {
    product_id: 1039,
    product_name: "Cube Black Bar Stool",
    custom_field_id: 1007,
    custom_field_name: "Material",
    custom_field_value: "Steel Frame with faux leather or bamboo seat pad",
    delete: "FALSE",
  },
  {
    product_id: 1039,
    product_name: "Cube Black Bar Stool",
    custom_field_id: 1008,
    custom_field_name: "Colour",
    custom_field_value: "Black frame with choice of seat pad",
    delete: "FALSE",
  },
  {
    product_id: 1039,
    product_name: "Cube Black Bar Stool",
    custom_field_id: 1009,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 8 high",
    delete: "FALSE",
  },
  {
    product_id: 1039,
    product_name: "Cube Black Bar Stool",
    custom_field_id: 1010,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1041,
    product_name: "Cube Black Bar Stool (Small)",
    custom_field_id: 1016,
    custom_field_name: "Seat Height",
    custom_field_value: "43cm",
    delete: "FALSE",
  },
  {
    product_id: 1041,
    product_name: "Cube Black Bar Stool (Small)",
    custom_field_id: 1017,
    custom_field_name: "Material",
    custom_field_value: "Steel Frame with faux leather seat pad or bamboo",
    delete: "FALSE",
  },
  {
    product_id: 1041,
    product_name: "Cube Black Bar Stool (Small)",
    custom_field_id: 1018,
    custom_field_name: "Colour",
    custom_field_value: "Black Frame with choice of seat pad",
    delete: "FALSE",
  },
  {
    product_id: 1041,
    product_name: "Cube Black Bar Stool (Small)",
    custom_field_id: 1019,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 8 high",
    delete: "FALSE",
  },
  {
    product_id: 1041,
    product_name: "Cube Black Bar Stool (Small)",
    custom_field_id: 1020,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1042,
    product_name: "Zeus Bar Stool with Red Pad Cover",
    custom_field_id: 1021,
    custom_field_name: "Seat Height",
    custom_field_value: "82cm",
    delete: "FALSE",
  },
  {
    product_id: 1042,
    product_name: "Zeus Bar Stool with Red Pad Cover",
    custom_field_id: 1022,
    custom_field_name: "Material",
    custom_field_value: "Chrome base with fabric seat pad",
    delete: "FALSE",
  },
  {
    product_id: 1042,
    product_name: "Zeus Bar Stool with Red Pad Cover",
    custom_field_id: 1023,
    custom_field_name: "Colour",
    custom_field_value: "Red",
    delete: "FALSE",
  },
  {
    product_id: 1042,
    product_name: "Zeus Bar Stool with Red Pad Cover",
    custom_field_id: 1024,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 2 high",
    delete: "FALSE",
  },
  {
    product_id: 1042,
    product_name: "Zeus Bar Stool with Red Pad Cover",
    custom_field_id: 1025,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1043,
    product_name: "Zeus Stool with White Spandex Cover",
    custom_field_id: 1026,
    custom_field_name: "Seat Height",
    custom_field_value: "82cm",
    delete: "FALSE",
  },
  {
    product_id: 1043,
    product_name: "Zeus Stool with White Spandex Cover",
    custom_field_id: 1027,
    custom_field_name: "Material",
    custom_field_value: "Chrome and fabric seat pad",
    delete: "FALSE",
  },
  {
    product_id: 1043,
    product_name: "Zeus Stool with White Spandex Cover",
    custom_field_id: 1028,
    custom_field_name: "Colour",
    custom_field_value: "White seat pad",
    delete: "FALSE",
  },
  {
    product_id: 1043,
    product_name: "Zeus Stool with White Spandex Cover",
    custom_field_id: 1029,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks in 2",
    delete: "FALSE",
  },
  {
    product_id: 1043,
    product_name: "Zeus Stool with White Spandex Cover",
    custom_field_id: 1030,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1044,
    product_name: "Aurora Black Stool",
    custom_field_id: 1031,
    custom_field_name: "Seat Height",
    custom_field_value: "63cm or 77cm",
    delete: "FALSE",
  },
  {
    product_id: 1044,
    product_name: "Aurora Black Stool",
    custom_field_id: 1032,
    custom_field_name: "Material",
    custom_field_value: "Chrome leg with leather seat and back",
    delete: "FALSE",
  },
  {
    product_id: 1044,
    product_name: "Aurora Black Stool",
    custom_field_id: 1033,
    custom_field_name: "Colour",
    custom_field_value: "Black",
    delete: "FALSE",
  },
  {
    product_id: 1044,
    product_name: "Aurora Black Stool",
    custom_field_id: 1034,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or foldable",
    delete: "FALSE",
  },
  {
    product_id: 1044,
    product_name: "Aurora Black Stool",
    custom_field_id: 1035,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1045,
    product_name: "Traditional Wooden Bar Stool",
    custom_field_id: 1036,
    custom_field_name: "Seat Height",
    custom_field_value: "75cm",
    delete: "FALSE",
  },
  {
    product_id: 1045,
    product_name: "Traditional Wooden Bar Stool",
    custom_field_id: 1037,
    custom_field_name: "Material",
    custom_field_value: "Wood",
    delete: "FALSE",
  },
  {
    product_id: 1045,
    product_name: "Traditional Wooden Bar Stool",
    custom_field_id: 1038,
    custom_field_name: "Colour",
    custom_field_value: "Walnut",
    delete: "FALSE",
  },
  {
    product_id: 1045,
    product_name: "Traditional Wooden Bar Stool",
    custom_field_id: 1039,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or foldable",
    delete: "FALSE",
  },
  {
    product_id: 1045,
    product_name: "Traditional Wooden Bar Stool",
    custom_field_id: 1040,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1050,
    product_name: "Chloe White Chameleon Chair (Full Cover)",
    custom_field_id: 1061,
    custom_field_name: "Seat Height",
    custom_field_value: "47cm",
    delete: "FALSE",
  },
  {
    product_id: 1050,
    product_name: "Chloe White Chameleon Chair (Full Cover)",
    custom_field_id: 1062,
    custom_field_name: "Material",
    custom_field_value: "Steel frame with full lycra covering",
    delete: "FALSE",
  },
  {
    product_id: 1050,
    product_name: "Chloe White Chameleon Chair (Full Cover)",
    custom_field_id: 1063,
    custom_field_name: "Colour",
    custom_field_value: "White",
    delete: "FALSE",
  },
  {
    product_id: 1050,
    product_name: "Chloe White Chameleon Chair (Full Cover)",
    custom_field_id: 1064,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stacks 6 high",
    delete: "FALSE",
  },
  {
    product_id: 1050,
    product_name: "Chloe White Chameleon Chair (Full Cover)",
    custom_field_id: 1065,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1078,
    product_name: "Alaska Armchair - White",
    custom_field_id: 1117,
    custom_field_name: "Material",
    custom_field_value: "Leather",
    delete: "FALSE",
  },
  {
    product_id: 1078,
    product_name: "Alaska Armchair - White",
    custom_field_id: 1118,
    custom_field_name: "Colour",
    custom_field_value: "White",
    delete: "FALSE",
  },
  {
    product_id: 1078,
    product_name: "Alaska Armchair - White",
    custom_field_id: 1119,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or Foldable",
    delete: "FALSE",
  },
  {
    product_id: 1078,
    product_name: "Alaska Armchair - White",
    custom_field_id: 1120,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1085,
    product_name: "Wingback Armchair Yellow",
    custom_field_id: 4033,
    custom_field_name: "Seat Height",
    custom_field_value: "38cm",
    delete: "FALSE",
  },
  {
    product_id: 1085,
    product_name: "Wingback Armchair Yellow",
    custom_field_id: 4034,
    custom_field_name: "Material",
    custom_field_value: "Velvet Fabric",
    delete: "FALSE",
  },
  {
    product_id: 1085,
    product_name: "Wingback Armchair Yellow",
    custom_field_id: 4035,
    custom_field_name: "Colour",
    custom_field_value: "Yellow",
    delete: "FALSE",
  },
  {
    product_id: 1085,
    product_name: "Wingback Armchair Yellow",
    custom_field_id: 4036,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or foldable",
    delete: "FALSE",
  },
  {
    product_id: 1085,
    product_name: "Wingback Armchair Yellow",
    custom_field_id: 4037,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1086,
    product_name: "Wingback Armchair Red",
    custom_field_id: 1126,
    custom_field_name: "Seat Height",
    custom_field_value: "38cm",
    delete: "FALSE",
  },
  {
    product_id: 1086,
    product_name: "Wingback Armchair Red",
    custom_field_id: 1127,
    custom_field_name: "Material",
    custom_field_value: "Velvet Fabric",
    delete: "FALSE",
  },
  {
    product_id: 1086,
    product_name: "Wingback Armchair Red",
    custom_field_id: 1128,
    custom_field_name: "Colour",
    custom_field_value: "Red",
    delete: "FALSE",
  },
  {
    product_id: 1086,
    product_name: "Wingback Armchair Red",
    custom_field_id: 1129,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or Foldable",
    delete: "FALSE",
  },
  {
    product_id: 1086,
    product_name: "Wingback Armchair Red",
    custom_field_id: 1130,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1087,
    product_name: "Mad Men Armchair",
    custom_field_id: 4038,
    custom_field_name: "Seat Height",
    custom_field_value: "40cm",
    delete: "FALSE",
  },
  {
    product_id: 1087,
    product_name: "Mad Men Armchair",
    custom_field_id: 4039,
    custom_field_name: "Material",
    custom_field_value: "Solid Beech with vinyl seat covering",
    delete: "FALSE",
  },
  {
    product_id: 1087,
    product_name: "Mad Men Armchair",
    custom_field_id: 4040,
    custom_field_name: "Colour",
    custom_field_value: "Beech wood with black seat",
    delete: "FALSE",
  },
  {
    product_id: 1087,
    product_name: "Mad Men Armchair",
    custom_field_id: 4041,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Not stackable or foldable",
    delete: "FALSE",
  },
  {
    product_id: 1087,
    product_name: "Mad Men Armchair",
    custom_field_id: 4042,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1253,
    product_name: "Salt White Chair",
    custom_field_id: 6667,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable",
    delete: "TRUE",
  },
  {
    product_id: 1253,
    product_name: "Salt White Chair",
    custom_field_id: 6668,
    custom_field_name: "Colour",
    custom_field_value: "White",
    delete: "FALSE",
  },
  {
    product_id: 1253,
    product_name: "Salt White Chair",
    custom_field_id: 6669,
    custom_field_name: "Dimensions",
    custom_field_value: "44 x 48 x 80 cm (LxWxH)",
    delete: "FALSE",
  },
  {
    product_id: 1253,
    product_name: "Salt White Chair",
    custom_field_id: 6670,
    custom_field_name: "Usage",
    custom_field_value: "Indoor or Outdoor Use",
    delete: "TRUE",
  },
  {
    product_id: 1253,
    product_name: "Salt White Chair",
    custom_field_id: 8058,
    custom_field_name: "Material",
    custom_field_value: "Polypropylene",
    delete: "FALSE",
  },
  {
    product_id: 1253,
    product_name: "Salt White Chair",
    custom_field_id: 8059,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable",
    delete: "FALSE",
  },
  {
    product_id: 1253,
    product_name: "Salt White Chair",
    custom_field_id: 8060,
    custom_field_name: "Usage",
    custom_field_value: "Indoors/Outdoors",
    delete: "FALSE",
  },
  {
    product_id: 1310,
    product_name: "Milano Chair with Lecture Arm",
    custom_field_id: 6717,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1310,
    product_name: "Milano Chair with Lecture Arm",
    custom_field_id: 6718,
    custom_field_name: "Colour",
    custom_field_value: "Black",
    delete: "FALSE",
  },
  {
    product_id: 1310,
    product_name: "Milano Chair with Lecture Arm",
    custom_field_id: 8073,
    custom_field_name: "Usage",
    custom_field_value: "Lectures, conferences, and events",
    delete: "FALSE",
  },
  {
    product_id: 1311,
    product_name: "Regency Gold Chair",
    custom_field_id: 6719,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1311,
    product_name: "Regency Gold Chair",
    custom_field_id: 6720,
    custom_field_name: "Colour",
    custom_field_value: "Gold",
    delete: "FALSE",
  },
  {
    product_id: 1384,
    product_name: "Palm Rattan 2 Seater Sofa",
    custom_field_id: 6883,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1384,
    product_name: "Palm Rattan 2 Seater Sofa",
    custom_field_id: 6884,
    custom_field_name: "Colour",
    custom_field_value: "Beige",
    delete: "FALSE",
  },
  {
    product_id: 1384,
    product_name: "Palm Rattan 2 Seater Sofa",
    custom_field_id: 6885,
    custom_field_name: "Material",
    custom_field_value: "PU Rattan",
    delete: "FALSE",
  },
  {
    product_id: 1384,
    product_name: "Palm Rattan 2 Seater Sofa",
    custom_field_id: 6886,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Yes stack up to 12 benches",
    delete: "FALSE",
  },
  {
    product_id: 1384,
    product_name: "Palm Rattan 2 Seater Sofa",
    custom_field_id: 6887,
    custom_field_name: "Usage",
    custom_field_value: "Indoor & Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 1384,
    product_name: "Palm Rattan 2 Seater Sofa",
    custom_field_id: 6888,
    custom_field_name: "Dimensions",
    custom_field_value: "72 x 127 x 83 cm (LxWxH)",
    delete: "FALSE",
  },
  {
    product_id: 1384,
    product_name: "Palm Rattan 2 Seater Sofa",
    custom_field_id: 6889,
    custom_field_name: "Cushion",
    custom_field_value: "Yes, black",
    delete: "FALSE",
  },
  {
    product_id: 1385,
    product_name: "Palm Rattan Armchair",
    custom_field_id: 6877,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1385,
    product_name: "Palm Rattan Armchair",
    custom_field_id: 6878,
    custom_field_name: "Colour",
    custom_field_value: "Beige",
    delete: "FALSE",
  },
  {
    product_id: 1385,
    product_name: "Palm Rattan Armchair",
    custom_field_id: 6879,
    custom_field_name: "Usage",
    custom_field_value: "Indoor & Ourdoor",
    delete: "FALSE",
  },
  {
    product_id: 1385,
    product_name: "Palm Rattan Armchair",
    custom_field_id: 6880,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Yes stack up to 10 chairs",
    delete: "FALSE",
  },
  {
    product_id: 1385,
    product_name: "Palm Rattan Armchair",
    custom_field_id: 6881,
    custom_field_name: "Dimensions",
    custom_field_value: "Size: 59 x 58 x 84 cm (LxWxH)",
    delete: "FALSE",
  },
  {
    product_id: 1385,
    product_name: "Palm Rattan Armchair",
    custom_field_id: 6882,
    custom_field_name: "Material",
    custom_field_value: "PU Rattan",
    delete: "FALSE",
  },
  {
    product_id: 1385,
    product_name: "Palm Rattan Armchair",
    custom_field_id: 6890,
    custom_field_name: "Cushion",
    custom_field_value: "Yes, Black",
    delete: "FALSE",
  },
  {
    product_id: 1387,
    product_name: "Volt Barstool Black",
    custom_field_id: 6865,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1387,
    product_name: "Volt Barstool Black",
    custom_field_id: 6866,
    custom_field_name: "Colour",
    custom_field_value: "Black",
    delete: "FALSE",
  },
  {
    product_id: 1387,
    product_name: "Volt Barstool Black",
    custom_field_id: 6867,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable",
    delete: "FALSE",
  },
  {
    product_id: 1387,
    product_name: "Volt Barstool Black",
    custom_field_id: 6868,
    custom_field_name: "Material",
    custom_field_value: "polypropylene and fibreglass",
    delete: "FALSE",
  },
  {
    product_id: 1387,
    product_name: "Volt Barstool Black",
    custom_field_id: 6869,
    custom_field_name: "100% Recyclable",
    custom_field_value: "Yes",
    delete: "FALSE",
  },
  {
    product_id: 1387,
    product_name: "Volt Barstool Black",
    custom_field_id: 6870,
    custom_field_name: "Usage",
    custom_field_value: "Indoor & Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 1387,
    product_name: "Volt Barstool Black",
    custom_field_id: 8062,
    custom_field_name: "Usage",
    custom_field_value: "Outdoor",
    delete: "TRUE",
  },
  {
    product_id: 1388,
    product_name: "Volt Barstool White",
    custom_field_id: 6859,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1388,
    product_name: "Volt Barstool White",
    custom_field_id: 6860,
    custom_field_name: "Colour",
    custom_field_value: "White",
    delete: "FALSE",
  },
  {
    product_id: 1388,
    product_name: "Volt Barstool White",
    custom_field_id: 6861,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable",
    delete: "FALSE",
  },
  {
    product_id: 1388,
    product_name: "Volt Barstool White",
    custom_field_id: 6862,
    custom_field_name: "Usage",
    custom_field_value: "Indoor & Ourdoor",
    delete: "FALSE",
  },
  {
    product_id: 1388,
    product_name: "Volt Barstool White",
    custom_field_id: 6863,
    custom_field_name: "Material",
    custom_field_value: "polypropylene and fibreglass",
    delete: "FALSE",
  },
  {
    product_id: 1388,
    product_name: "Volt Barstool White",
    custom_field_id: 6864,
    custom_field_name: "Recyclable",
    custom_field_value: "Yes",
    delete: "FALSE",
  },
  {
    product_id: 1388,
    product_name: "Volt Barstool White",
    custom_field_id: 8063,
    custom_field_name: "Usage",
    custom_field_value: "Outdoor",
    delete: "TRUE",
  },
  {
    product_id: 1389,
    product_name: "Volt Chair Black",
    custom_field_id: 6853,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1389,
    product_name: "Volt Chair Black",
    custom_field_id: 6854,
    custom_field_name: "Material",
    custom_field_value: "polypropylene and fibreglass",
    delete: "FALSE",
  },
  {
    product_id: 1389,
    product_name: "Volt Chair Black",
    custom_field_id: 6855,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable",
    delete: "FALSE",
  },
  {
    product_id: 1389,
    product_name: "Volt Chair Black",
    custom_field_id: 6856,
    custom_field_name: "Colour",
    custom_field_value: "Black",
    delete: "FALSE",
  },
  {
    product_id: 1389,
    product_name: "Volt Chair Black",
    custom_field_id: 6857,
    custom_field_name: "Usage",
    custom_field_value: "Indoor & Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 1389,
    product_name: "Volt Chair Black",
    custom_field_id: 6858,
    custom_field_name: "Recyclable",
    custom_field_value: "yes",
    delete: "FALSE",
  },
  {
    product_id: 1389,
    product_name: "Volt Chair Black",
    custom_field_id: 8064,
    custom_field_name: "Usage",
    custom_field_value: "Outdoor",
    delete: "TRUE",
  },
  {
    product_id: 1406,
    product_name: "Zoey Bar Stool",
    custom_field_id: 8065,
    custom_field_name: "Colour",
    custom_field_value: "Beige; Black/Brown",
    delete: "FALSE",
  },
  {
    product_id: 1506,
    product_name: "Alice Bar Stool Rose Gold",
    custom_field_id: 6976,
    custom_field_name: "Pack size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1506,
    product_name: "Alice Bar Stool Rose Gold",
    custom_field_id: 6977,
    custom_field_name: "Frame Colour",
    custom_field_value: "Rose Gold Chrome",
    delete: "FALSE",
  },
  {
    product_id: 1506,
    product_name: "Alice Bar Stool Rose Gold",
    custom_field_id: 6978,
    custom_field_name: "Seat Pads",
    custom_field_value: "Green, Gold, Pink  and Black",
    delete: "FALSE",
  },
  {
    product_id: 1506,
    product_name: "Alice Bar Stool Rose Gold",
    custom_field_id: 6979,
    custom_field_name: "Seat Pad Material",
    custom_field_value: "Velvet",
    delete: "FALSE",
  },
  {
    product_id: 1506,
    product_name: "Alice Bar Stool Rose Gold",
    custom_field_id: 6980,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1506,
    product_name: "Alice Bar Stool Rose Gold",
    custom_field_id: 6981,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable",
    delete: "FALSE",
  },
  {
    product_id: 1506,
    product_name: "Alice Bar Stool Rose Gold",
    custom_field_id: 6982,
    custom_field_name: "Seats are fire retardant",
    custom_field_value: "Yes",
    delete: "FALSE",
  },
  {
    product_id: 1506,
    product_name: "Alice Bar Stool Rose Gold",
    custom_field_id: 6983,
    custom_field_name: "Seats treated with Teflon (CRIB5)",
    custom_field_value: "Yes",
    delete: "FALSE",
  },
  {
    product_id: 1506,
    product_name: "Alice Bar Stool Rose Gold",
    custom_field_id: 8066,
    custom_field_name: "Colour",
    custom_field_value: "Velvet Black, Velvet Gold, Velvet Green, Velvet Pink",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 6984,
    custom_field_name: "Pack size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 6985,
    custom_field_name: "Frame Colour",
    custom_field_value: "Black Wood with a Rattan Back rest",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 6986,
    custom_field_name: "Seat Pads",
    custom_field_value: "Black Velvet and Rattan",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 6987,
    custom_field_name: "Seat Pad Material",
    custom_field_value: "Velvet",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 6988,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 6989,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 6990,
    custom_field_name: "Seats are fire retardant",
    custom_field_value: "Yes",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 6991,
    custom_field_name: "Seats treated with Teflon (CRIB5)",
    custom_field_value: "Yes",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 6992,
    custom_field_name: "Dimensions",
    custom_field_value:
      "86cm full height, 41.5cm seat height, 46.5cm w, 41.5cm d",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 6993,
    custom_field_name: "Weight",
    custom_field_value: "4kg",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 8067,
    custom_field_name: "Material",
    custom_field_value: "Wood",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 8068,
    custom_field_name: "Colour",
    custom_field_value: "Natural Rattan, Black Velvet",
    delete: "FALSE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 8069,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable",
    delete: "TRUE",
  },
  {
    product_id: 1507,
    product_name: "Ronda Chair",
    custom_field_id: 8070,
    custom_field_name: "Usage",
    custom_field_value: "Catering events",
    delete: "TRUE",
  },
  {
    product_id: 1509,
    product_name: "Palm Black Armchair",
    custom_field_id: 7000,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1509,
    product_name: "Palm Black Armchair",
    custom_field_id: 7001,
    custom_field_name: "Colour",
    custom_field_value: "Black",
    delete: "FALSE",
  },
  {
    product_id: 1509,
    product_name: "Palm Black Armchair",
    custom_field_id: 7002,
    custom_field_name: "Usage",
    custom_field_value: "Indoor & Ourdoor",
    delete: "FALSE",
  },
  {
    product_id: 1509,
    product_name: "Palm Black Armchair",
    custom_field_id: 7003,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Yes stack up to 10 chairs",
    delete: "FALSE",
  },
  {
    product_id: 1509,
    product_name: "Palm Black Armchair",
    custom_field_id: 7004,
    custom_field_name: "Dimensions",
    custom_field_value: "Size: 59 x 58 x 84 cm (LxWxH)",
    delete: "FALSE",
  },
  {
    product_id: 1509,
    product_name: "Palm Black Armchair",
    custom_field_id: 7005,
    custom_field_name: "Material",
    custom_field_value: "PU Rattan",
    delete: "FALSE",
  },
  {
    product_id: 1509,
    product_name: "Palm Black Armchair",
    custom_field_id: 7006,
    custom_field_name: "Cushion",
    custom_field_value: "Yes, Black",
    delete: "FALSE",
  },
  {
    product_id: 1510,
    product_name: "Palm Black 2 Seater Sofa",
    custom_field_id: 7007,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1510,
    product_name: "Palm Black 2 Seater Sofa",
    custom_field_id: 7008,
    custom_field_name: "Colour",
    custom_field_value: "Black",
    delete: "FALSE",
  },
  {
    product_id: 1510,
    product_name: "Palm Black 2 Seater Sofa",
    custom_field_id: 7009,
    custom_field_name: "Material",
    custom_field_value: "PU Rattan",
    delete: "FALSE",
  },
  {
    product_id: 1510,
    product_name: "Palm Black 2 Seater Sofa",
    custom_field_id: 7010,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Yes stack up to 12 benches",
    delete: "FALSE",
  },
  {
    product_id: 1510,
    product_name: "Palm Black 2 Seater Sofa",
    custom_field_id: 7011,
    custom_field_name: "Usage",
    custom_field_value: "Indoor & Outdoor",
    delete: "FALSE",
  },
  {
    product_id: 1510,
    product_name: "Palm Black 2 Seater Sofa",
    custom_field_id: 7012,
    custom_field_name: "Dimensions",
    custom_field_value: "72 x 127 x 83 cm (LxWxH)",
    delete: "FALSE",
  },
  {
    product_id: 1510,
    product_name: "Palm Black 2 Seater Sofa",
    custom_field_id: 7013,
    custom_field_name: "Cushion",
    custom_field_value: "Yes, black",
    delete: "FALSE",
  },
  {
    product_id: 1640,
    product_name: "Smartie Bench Black (5 seater)",
    custom_field_id: 7925,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1640,
    product_name: "Smartie Bench Black (5 seater)",
    custom_field_id: 7926,
    custom_field_name: "Colour",
    custom_field_value: "Black",
    delete: "FALSE",
  },
  {
    product_id: 1640,
    product_name: "Smartie Bench Black (5 seater)",
    custom_field_id: 7927,
    custom_field_name: "Seats",
    custom_field_value: "5",
    delete: "FALSE",
  },
  {
    product_id: 1640,
    product_name: "Smartie Bench Black (5 seater)",
    custom_field_id: 7928,
    custom_field_name: "Suitable for",
    custom_field_value: "Indoor use",
    delete: "FALSE",
  },
  {
    product_id: 1640,
    product_name: "Smartie Bench Black (5 seater)",
    custom_field_id: 7930,
    custom_field_name: "Dimensions",
    custom_field_value: "Height: 52cm/20in Width: 183cm/77in Depth: 50cm/20in",
    delete: "FALSE",
  },
  {
    product_id: 1640,
    product_name: "Smartie Bench Black (5 seater)",
    custom_field_id: 8046,
    custom_field_name: "Material",
    custom_field_value: "Solid wood",
    delete: "FALSE",
  },
  {
    product_id: 1640,
    product_name: "Smartie Bench Black (5 seater)",
    custom_field_id: 8047,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1641,
    product_name: "Smartie Bench White (5 seater)",
    custom_field_id: 7921,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1641,
    product_name: "Smartie Bench White (5 seater)",
    custom_field_id: 7922,
    custom_field_name: "Colour",
    custom_field_value: "White",
    delete: "FALSE",
  },
  {
    product_id: 1641,
    product_name: "Smartie Bench White (5 seater)",
    custom_field_id: 7923,
    custom_field_name: "Seats",
    custom_field_value: "5",
    delete: "FALSE",
  },
  {
    product_id: 1641,
    product_name: "Smartie Bench White (5 seater)",
    custom_field_id: 7924,
    custom_field_name: "Suitable for",
    custom_field_value: "Indoor Use",
    delete: "FALSE",
  },
  {
    product_id: 1641,
    product_name: "Smartie Bench White (5 seater)",
    custom_field_id: 7929,
    custom_field_name: "Dimensions",
    custom_field_value: "Height: 52cm/20in Width: 183cm/77in Depth: 50cm/20in",
    delete: "FALSE",
  },
  {
    product_id: 1641,
    product_name: "Smartie Bench White (5 seater)",
    custom_field_id: 8071,
    custom_field_name: "Material",
    custom_field_value: "Wooden",
    delete: "FALSE",
  },
  {
    product_id: 1641,
    product_name: "Smartie Bench White (5 seater)",
    custom_field_id: 8072,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1653,
    product_name: "Hampton Wooden Folding Chair",
    custom_field_id: 7956,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1653,
    product_name: "Hampton Wooden Folding Chair",
    custom_field_id: 7957,
    custom_field_name: "Colour",
    custom_field_value: "Warm Oak",
    delete: "FALSE",
  },
  {
    product_id: 1653,
    product_name: "Hampton Wooden Folding Chair",
    custom_field_id: 7958,
    custom_field_name: "Wood",
    custom_field_value: "Beech",
    delete: "FALSE",
  },
  {
    product_id: 1653,
    product_name: "Hampton Wooden Folding Chair",
    custom_field_id: 7959,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Foldable",
    delete: "TRUE",
  },
  {
    product_id: 1653,
    product_name: "Hampton Wooden Folding Chair",
    custom_field_id: 8074,
    custom_field_name: "Material",
    custom_field_value: "Solid beech wood frame with rattan mesh seat and back",
    delete: "FALSE",
  },
  {
    product_id: 1653,
    product_name: "Hampton Wooden Folding Chair",
    custom_field_id: 8075,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Foldable design for easy storage and transport",
    delete: "FALSE",
  },
  {
    product_id: 1653,
    product_name: "Hampton Wooden Folding Chair",
    custom_field_id: 8076,
    custom_field_name: "Usage",
    custom_field_value:
      "Ideal for ceremonies, summer gatherings, and chic receptions",
    delete: "FALSE",
  },
  {
    product_id: 1654,
    product_name: "Emily Crossback Chair Light Walnut",
    custom_field_id: 7952,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1654,
    product_name: "Emily Crossback Chair Light Walnut",
    custom_field_id: 7953,
    custom_field_name: "Colour",
    custom_field_value: "Light Walnut",
    delete: "FALSE",
  },
  {
    product_id: 1654,
    product_name: "Emily Crossback Chair Light Walnut",
    custom_field_id: 7954,
    custom_field_name: "Stackable / Foldable",
    custom_field_value: "Stackable",
    delete: "FALSE",
  },
  {
    product_id: 1654,
    product_name: "Emily Crossback Chair Light Walnut",
    custom_field_id: 7955,
    custom_field_name: "Suitable for",
    custom_field_value: "Indoor or dry, covered outdoor use",
    delete: "FALSE",
  },
  {
    product_id: 1654,
    product_name: "Emily Crossback Chair Light Walnut",
    custom_field_id: 8022,
    custom_field_name: "Seat Pad",
    custom_field_value:
      "Default Seat pad is Mink. A range of available colours to choose from",
    delete: "FALSE",
  },
  {
    product_id: 1654,
    product_name: "Emily Crossback Chair Light Walnut",
    custom_field_id: 8077,
    custom_field_name: "Material",
    custom_field_value: "Hardwood",
    delete: "FALSE",
  },
  {
    product_id: 1655,
    product_name: "Chameleon Black Suede Chair",
    custom_field_id: 8036,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1655,
    product_name: "Chameleon Black Suede Chair",
    custom_field_id: 8037,
    custom_field_name: "Seat Colour",
    custom_field_value: "Black Suede",
    delete: "FALSE",
  },
  {
    product_id: 1655,
    product_name: "Chameleon Black Suede Chair",
    custom_field_id: 8038,
    custom_field_name: "Leg Colour",
    custom_field_value: "Brown",
    delete: "FALSE",
  },
  {
    product_id: 1655,
    product_name: "Chameleon Black Suede Chair",
    custom_field_id: 8039,
    custom_field_name: "Suitable for",
    custom_field_value: "Weddings, Banquets and Events",
    delete: "FALSE",
  },
  {
    product_id: 1655,
    product_name: "Chameleon Black Suede Chair",
    custom_field_id: 8048,
    custom_field_name: "Material",
    custom_field_value:
      "Black suede upholstery with eco-friendly recyclable steel construction and dark brown legs",
    delete: "FALSE",
  },
  {
    product_id: 1655,
    product_name: "Chameleon Black Suede Chair",
    custom_field_id: 8049,
    custom_field_name: "Colour",
    custom_field_value: "Black with dark brown accents",
    delete: "FALSE",
  },
  {
    product_id: 1656,
    product_name: "Chameleon White Suede Chair",
    custom_field_id: 8032,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1656,
    product_name: "Chameleon White Suede Chair",
    custom_field_id: 8033,
    custom_field_name: "Seat Colour",
    custom_field_value: "White Suede",
    delete: "FALSE",
  },
  {
    product_id: 1656,
    product_name: "Chameleon White Suede Chair",
    custom_field_id: 8034,
    custom_field_name: "Leg Colour",
    custom_field_value: "Silver",
    delete: "FALSE",
  },
  {
    product_id: 1656,
    product_name: "Chameleon White Suede Chair",
    custom_field_id: 8035,
    custom_field_name: "Suitable for",
    custom_field_value: "Weddings, Banquets and Events",
    delete: "FALSE",
  },
  {
    product_id: 1656,
    product_name: "Chameleon White Suede Chair",
    custom_field_id: 8050,
    custom_field_name: "Material",
    custom_field_value: "Suede upholstery with a recyclable steel frame",
    delete: "FALSE",
  },
  {
    product_id: 1656,
    product_name: "Chameleon White Suede Chair",
    custom_field_id: 8051,
    custom_field_name: "Colour",
    custom_field_value: "White with silver accents",
    delete: "FALSE",
  },
  {
    product_id: 1656,
    product_name: "Chameleon White Suede Chair",
    custom_field_id: 8052,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1657,
    product_name: "Chameleon Cocoa Brown Suede Chair",
    custom_field_id: 8028,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1657,
    product_name: "Chameleon Cocoa Brown Suede Chair",
    custom_field_id: 8029,
    custom_field_name: "Seat Colour",
    custom_field_value: "Cocoa Brown Suede",
    delete: "FALSE",
  },
  {
    product_id: 1657,
    product_name: "Chameleon Cocoa Brown Suede Chair",
    custom_field_id: 8030,
    custom_field_name: "Leg Colour",
    custom_field_value: "Brown",
    delete: "FALSE",
  },
  {
    product_id: 1657,
    product_name: "Chameleon Cocoa Brown Suede Chair",
    custom_field_id: 8031,
    custom_field_name: "Suitable for",
    custom_field_value: "Weddings, Banquets and Events",
    delete: "FALSE",
  },
  {
    product_id: 1657,
    product_name: "Chameleon Cocoa Brown Suede Chair",
    custom_field_id: 8053,
    custom_field_name: "Material",
    custom_field_value: "Suede upholstery with recyclable steel frames",
    delete: "FALSE",
  },
  {
    product_id: 1657,
    product_name: "Chameleon Cocoa Brown Suede Chair",
    custom_field_id: 8054,
    custom_field_name: "Colour",
    custom_field_value: "Cocoa brown",
    delete: "FALSE",
  },
  {
    product_id: 1657,
    product_name: "Chameleon Cocoa Brown Suede Chair",
    custom_field_id: 8055,
    custom_field_name: "Usage",
    custom_field_value: "Indoor",
    delete: "FALSE",
  },
  {
    product_id: 1658,
    product_name: "Chameleon Charcoal Suede Chair",
    custom_field_id: 8024,
    custom_field_name: "Case size",
    custom_field_value: "1",
    delete: "FALSE",
  },
  {
    product_id: 1658,
    product_name: "Chameleon Charcoal Suede Chair",
    custom_field_id: 8025,
    custom_field_name: "Seat Colour",
    custom_field_value: "Charcoal Suede",
    delete: "FALSE",
  },
  {
    product_id: 1658,
    product_name: "Chameleon Charcoal Suede Chair",
    custom_field_id: 8026,
    custom_field_name: "Leg Colour",
    custom_field_value: "Silver",
    delete: "FALSE",
  },
  {
    product_id: 1658,
    product_name: "Chameleon Charcoal Suede Chair",
    custom_field_id: 8027,
    custom_field_name: "Suitable for",
    custom_field_value: "Weddings, Banquets and Events",
    delete: "FALSE",
  },
  {
    product_id: 1658,
    product_name: "Chameleon Charcoal Suede Chair",
    custom_field_id: 8056,
    custom_field_name: "Material",
    custom_field_value: "Charcoal suede with recyclable steel legs",
    delete: "FALSE",
  },
  {
    product_id: 1658,
    product_name: "Chameleon Charcoal Suede Chair",
    custom_field_id: 8057,
    custom_field_name: "Colour",
    custom_field_value:
      "Charcoal finish with seat pad options in cocoa brown, white, and black",
    delete: "FALSE",
  },
];

// handle deletions first because they can conflict with custom field name canges
data.sort((a) => (a.delete === "TRUE" ? -1 : 1));

async function test() {
  try {
    require("../../config/config").config("ha");
    for (let i = 0; i < data.length; i++) {
      console.log(i, data.length);
      const row = data[i];
      let cf: CustomField;
      try {
        cf = await getCustomField(row.product_id, row.custom_field_id);
      } catch (err: any) {
        if (err.status === 404) {
          continue;
        } else {
          throw err;
        }
      }


      if (row.delete === "TRUE") {
        console.log(
          `deleting custom field name:${cf.name}; value:${cf.value};`
        );
        try {
          await new Promise((res) => setTimeout(res, 3000));
          await deleteCustomField(row.product_id, row.custom_field_id);
          continue;
        } catch (err: any) {
          if (err.status === 404 || err.response?.data?.status === 404) {
            continue;
          } else {
            throw err;
          }
        }
      }


      if (
        row.custom_field_name !== cf.name ||
        row.custom_field_value !== cf.value
      ) {
        console.log(
          `updating custom field name:${cf.name} => ${row.custom_field_name} value:${cf.value} => ${row.custom_field_value};`
        );
        await new Promise((res) => setTimeout(res, 3000));
        try {
          await updateCustomField(
            row.product_id,
            row.custom_field_id,
            row.custom_field_name,
            row.custom_field_value
          );
        } catch (err: any) {
          throw err;
        }
      }
    }
  } catch (err: any) {
    if (err.response) {
      if (err.response.data) {
        console.log(err.response.data);
      } else {
        console.log(err.response);
      }
    } else {
      console.log(err);
    }
  }
}
test();
