import axios from "axios";
require("./config/config");

// Replace 'YOUR_AHREFS_API_KEY' with your actual Ahrefs API key
const API_KEY = process.env.AHREFS_KEY;

// Array of keywords to get traffic data for
const keywords = [
  "American Crew",
  "Advanced Nutrition",
  "Australian Gold",
  "Alfaparf",
  "Alumier MD",
  "ASAP",
  "AVEDA",
  "ALISO",
  "Ariana Grande",
  "Annutri ",
  "Avène",
  "AyuGlo",
  "Azzaro",
  "Act+Acre",
  "ANSWR",
  "AYA Supplements",
  "Ameliorate",
  "Bare By Vogue",
  "Bondi Sands",
  "BetterYou",
  "Bioderma ",
  "Beauty Works ",
  "Benefit ",
  "BYSK Sarah Keary",
  "Biabelle",
  "Bellamianta ",
  "Bumble and Bumble ",
  "Bahama Skin ",
  "Beauty Box ",
  "Color Wow",
  "CND Nails",
  "Clinicare",
  "CeraVe",
  "Caudalie",
  "Clinisoothe+",
  "Christophe Robin",
  "COOLA",
  "Childs Farm",
  "Calvin Klein ",
  "Cosrx",
  "Clarins",
  "Davines",
  "Dolce & Gabbana",
  "Distinct Beauty ",
  "Deesse ",
  "Dermalogica",
  "Dr Hauschka",
  "Dripping Gold",
  "Diesel",
  "Dyson ",
  "Dermalogica ",
  "DMK Skincare",
  "Davidoff",
  "Elemis",
  "Environ",
  "Embryolisse",
  "ESPA",
  "Eylure",
  "Eleven",
  "Elie Saab",
  "Elegant Touch ",
  "Evo",
  "Essie ",
  "Emma Hardie",
  "Eve Lom",
  "e.l.f. Cosmetics",
  "Epionce",
  "Full Brow Cosmetics ",
  "Foreo",
  "Formulae Prescott",
  "fabÜ ",
  "Footlogix",
  "GHD",
  "Gift Card",
  "GROUND",
  "GESKE",
  "He Shi",
  "Hot Tools",
  "Heliocare",
  "Hush & Hush",
  "Health & Her",
  "HydroPeptide ",
  "hismile",
  "Hair By Sam McKnight",
  "Hero",
  "Image Skincare",
  "Inglot",
  "Issey Miyake",
  "Iconic London ",
  "Jane Iredale",
  "Joico",
  "James Read",
  "Josh Wood Colour ",
  "Kérastase",
  "Kevin Murphy",
  "Kemon",
  "Kalmar",
  "Klorane ",
  "K18",
  "Kash Beauty",
  "Korres ",
  "L'Oréal Professionnel",
  "Luna by Lisa Jordan",
  "L'Occitane",
  "Long4Lashes",
  "Lancaster",
  "Lullabellz ",
  "Living Proof",
  "La Bougie ",
  "Lusso Tan ",
  "MoroccanOil",
  "Murad",
  "Mama Mio",
  "Margaret Dabbs",
  "Medik8",
  "MONDAY Haircare",
  "Molton Brown",
  "Moschino ",
  "Marc Jacobs ",
  "My Vitamins",
  "Minimalist",
  "Nioxin",
  "Neom",
  "NAK",
  "Neostrata",
  "Nuxe",
  "Narciso Rodriguez",
  "Nivea",
  "Novomins",
  "Olaplex",
  "Omnilux ",
  "Oway ",
  "Oh K!",
  "OPI",
  "Obagi ",
  "Omorovicza",
  "Pureology",
  "Pestle & Mortar",
  "Patchology",
  "PRAI ",
  "P20",
  "Philip Kingsley",
  "Pharma Plus ",
  "Pearl Beauty ",
  "Piz Buin ",
  "Q+A",
  "Redken",
  "Revive Active",
  "Revlon",
  "RevitaLash",
  "REN",
  "REVOLUTION",
  "Ralph Lauren",
  "Rosalique",
  "Rathbornes 1488",
  "Shu Uemura",
  "Spotlight Whitening",
  "SOSU Cosmetics",
  "Skinade",
  "Skingredients",
  "SkinCeuticals",
  "Steampod",
  "Seavite",
  "St Tropez",
  "Spacemasks",
  "Sculpted By Aimee Connolly",
  "Sanctuary ",
  "Seoulista",
  "Skin Formulas",
  "Shiseido",
  "Scott Barnes",
  "Sigma",
  "SEABODY",
  "Sarah Chapman",
  "Sun Bum",
  "SKIN KRUSH",
  "Shark",
  "Seoulista ",
  "Skinny Tan ",
  "Skin Generics ",
  "Sómas",
  "Swedish Nutra",
  "Swedish Collagen ",
  "Solgar",
  "Sundae Body",
  "Solar Buddies",
  "Skinician",
  "Tangle Teezer",
  "Trilogy",
  "This Works",
  "Tisserand",
  "TLC",
  "The Handmade Soap Company",
  "Tan Organic",
  "The Inkey List",
  "Tweezerman",
  "The Solution ",
  "theBalm",
  "Tommy Hilfiger",
  "Travalo",
  "The Tan Brush ",
  "True Beauty By Aideen Kate ",
  "Tan-Luxe",
  "Ultrasun",
  "Urban Decay",
  "Vita Liberata",
  "Voya",
  "Viviscal",
  "Viktor & Rolf",
  "Vitabiotics",
  "Wella Professional",
  "Weleda",
  "WILD",
  "XEN-GLOW",
  "YonKa",
  "Yourzooki",
  "Zadig&Voltaire",
  "Zelens ",
  "Zo Skin Health ",
];

async function getKeywordTraffic(keyword: string) {
    try {
      const response = await axios.get('https://api.ahrefs.com/v1/keyword/traffic', {
        params: {
          key: API_KEY,
          keyword: keyword
        }
      });
  
      const data = response.data;
      // Process the traffic data as needed
      console.log(data);
      return data;
    } catch (error: any) {
      console.error('Error fetching traffic data:', error.response.data);
      return null;
    }
  }
  
  async function main() {
    for (const keyword of keywords) {
      const trafficData = await getKeywordTraffic(keyword);
      if (trafficData) {
        // Do something with the traffic data
        console.log(`Traffic for ${keyword}: ${trafficData.traffic}`);
      }
    }
  }
  
  main();