require("../../config/config");
import sgMail from "@sendgrid/mail";
sgMail.setApiKey(process.env.SENDGRID_API_KEY!);
import { Database } from "sqlite3";
import path from "path";
const db = new Database(path.resolve(__dirname, "./emails.db"));
const data = [
  { name: "Sinead", email: "paraskevasinead@gmail.com" },
  { name: "Grace", email: "ggbabes090@gmail.com" },
  { name: "janet", email: "moffatt952@gmail.com" },
  { name: "Mags", email: "margaretfarley91@gmail.com" },
  { name: "Paula", email: "paula.king80@gmail.com" },
  { name: "Katherine", email: "mrskatherinewilliams@gmail.com" },
  { name: "Helena", email: "helenaguerin715@gmail.com" },
  { name: "Jennifer", email: "jconnole@gmail.com" },
  { name: "Michelle", email: "mcuddigan92@gmail.com" },
  { name: "Tatiane", email: "tsouza2209@gmail.com" },
  { name: "Leah", email: "kimog142@gmail.com" },
  { name: "Ella", email: "ellagoodwinshow@gmail.com" },
  { name: "Aoife", email: "aspillane2007@gmail.com" },
  { name: "Kim", email: "kimbro80@gmail.com" },
  { name: "Edie", email: "kirkrekirk@gmail.com" },
  { name: "Sonia", email: "soniatr2000@gmail.com" },
  { name: "Emma", email: "emmajane.byrne@gmail.com" },
  { name: "Lorraine", email: "lorrainejaoreilly@gmail.com" },
  { name: "Ashley", email: "ashleytaylorsmith8@gmail.com" },
  { name: "mary", email: "mfarrellyfleming@gmail.com" },
  { name: "Lynda", email: "dohertylynda80@gmail.com" },
  { name: "Kate", email: "katedixon97@gmail.com" },
  { name: "Stacey ", email: "roches8@gmail.com" },
  { name: "Danuta", email: "arcadia171210@gmail.com" },
  { name: "Louise", email: "louisehyland14@gmail.com" },
  { name: "Antoinette", email: "antoinettedoyle.kav@gmail.com" },
  { name: "Liz", email: "starlight101m@gmail.com" },
  { name: "Niamh", email: "Niamhbetts843@gmail.com" },
  { name: "Amy", email: "amyholden2@gmail.com" },
  { name: "Caitriona ", email: "caitrionabland@gmail.com" },
  { name: "Caroline", email: "carrie.mcgee22@gmail.com" },
  { name: "Therese", email: "theresemolloy1@gmail.com" },
  { name: "Sorcha", email: "sorchameehan97@gmail.com" },
  { name: "Sharon", email: "sharonmhanley@gmail.com" },
  { name: "Juste", email: "justesamsonova@gmail.com" },
  { name: "Michelle", email: "michelledevaney17@gmail.com" },
  { name: "Amelia", email: "ameliajstarnes@gmail.com" },
  { name: "Paula", email: "paulahynes78@gmail.com" },
  { name: "Laura", email: "l.mcdonagh10@gmail.com" },
  { name: "Edel", email: "edelmgiblin@gmail.com" },
  { name: "Eileen ", email: "eileenogrady2111@gmail.com" },
  { name: "Clare", email: "clareharks@gmail.com" },
  { name: "Michelle", email: "michelle.mich7@gmail.com" },
  { name: "Marie", email: "Mariempower@gmail.com" },
  { name: "Maureen ", email: "maureenrusty@gmail.com" },
  { name: "Catherine", email: "catherinejordanemail@gmail.com" },
  { name: "Niamh ", email: "niamhmwalsh@gmail.com" },
  { name: "Debbie ", email: "tdebbie1@gmail.com" },
  { name: "Amanda", email: "amandambarry1@gmail.com" },
  { name: "Claire", email: "Claire.anne.glynn@gmail.com" },
  { name: "Robyn", email: "robyncraddock06@gmail.com" },
  { name: "Roisin", email: "roisoneill@gmail.com" },
  { name: "Clare", email: "cwalshh@gmail.com" },
  { name: "Amy", email: "acorcoran1993@gmail.com" },
  { name: "Mark", email: "jessicamurphy079@gmail.com" },
  { name: "Brenda ", email: "mcloughlinbrenda@gmail.com" },
  { name: "Kathryn ", email: "kathryntowler@gmail.com" },
  { name: "Veronica", email: "veronicacollinsmaynooth@gmail.com" },
  { name: "Cathy", email: "cathyaryan@gmail.com" },
  { name: "Aileen", email: "aileen.kelleher@gmail.com" },
  { name: "Karen", email: "kardarby@gmail.com" },
  { name: "Mags", email: "magsoleary3@gmail.com" },
  { name: "Charlie", email: "charlieoshea95@gmail.com" },
  { name: "Kristiina", email: "kris.carmel@gmail.com" },
  { name: "Diane ", email: "diomahony1@gmail.com" },
  { name: "Amanda", email: "amanda.aylward@gmail.com" },
  { name: "Niall", email: "nialldooley94@gmail.com" },
  { name: "Naomi", email: "naomi.cantwell3@gmail.com" },
  { name: "Gillian ", email: "gillianmcguinness66@gmail.com" },
  { name: "Lorna", email: "lornadowd09@gmail.com" },
  { name: "Karen", email: "Karenmcg0304@gmail.com" },
  { name: "Orla", email: "orlagaynor@gmail.com" },
  { name: "Bea", email: "bcosgrave8@gmail.com" },
  { name: "Fiona", email: "brosnanfiona@gmail.com" },
  { name: "Joan", email: "jftaylorflynn@gmail.com" },
  { name: "Dawn", email: "dawnosull@gmail.com" },
  { name: "June", email: "junemstapleton@gmail.com" },
  { name: "Hazel", email: "hazelnoone@gmail.com" },
  { name: "Michelle", email: "michelleplkeane@gmail.com" },
  { name: "Lisa", email: "lisamcwhinney@gmail.com" },
  { name: "lina", email: "pelene83@gmail.com" },
  { name: "Kirsty", email: "kirstywa@gmail.com" },
  { name: "Brenda", email: "hanlybrenda@gmail.com" },
  { name: "Sinead", email: "sineadhealion1@gmail.com" },
  { name: "Aga", email: "mugoimajo@gmail.com" },
  { name: "Sharon", email: "mylessharon7@gmail.com" },
  { name: "Marie", email: "mariewilkinson632@gmail.com" },
  { name: "Susan", email: "suemkoco@gmail.com" },
  { name: "Therese", email: "heffernantherese.coolna@gmail.com" },
  { name: "Elaine", email: "devinebyrne@gmail.com" },
  { name: "Buggy", email: "carolbuggy33@gmail.com" },
  { name: "Orla", email: "orlahaverty@gmail.com" },
  { name: "Valerie ", email: "valerieholly181@gmail.com" },
  { name: "Aisling", email: "ais.hughes4@gmail.com" },
  { name: "Deirdre", email: "dbreen1977@gmail.com" },
  { name: "Jane", email: "naglejane@gmail.com" },
  { name: "Megan", email: "Meganhaugh71@gmail.com" },
  { name: "Kristel", email: "silverspring7765@gmail.com" },
  { name: "Caitriona ", email: "caitrionautilities@gmail.com" },
  { name: "Katie", email: "katieor0808@gmail.com" },
  { name: "Emma", email: "emmacarroll6@gmail.com" },
  { name: "Joan", email: "barrettjoan4@gmail.com" },
  { name: "Theresa", email: "theresadoohan21@gmail.com" },
  { name: "Denise", email: "deniseandkevindoyle@gmail.com" },
  { name: "Anna", email: "annanawrat25@gmail.com" },
  { name: "Sinead", email: "sineadmcc1995@gmail.com" },
  { name: "Bethany", email: "bethany.rush98@gmail.com" },
  { name: "Maria", email: "mariameaney80@gmail.com" },
  { name: "Celine", email: "cmacsmartie@gmail.com" },
  { name: "Victoria", email: "vickywindrum@gmail.com" },
  { name: "Flavia", email: "flavia.onascimento@gmail.com" },
  { name: "Amanda", email: "gamanda1@gmail.com" },
  { name: "Cathy", email: "cathymcneilage@gmail.com" },
  { name: "Sharon", email: "sharonmurphy93@gmail.com" },
  { name: "Gaby ", email: "gabyrendonc@gmail.com" },
  { name: "Ciara", email: "ciarammaddy@gmail.com" },
  { name: "Lisa", email: "lmanley07@gmail.com" },
  { name: "Sandra", email: "Yurtadat2@gmail.com" },
  { name: "Angela", email: "angeoneill@gmail.com" },
  { name: "Paula", email: "pola11484@gmail.com" },
  { name: "Tracey", email: "tmalone06@gmail.com" },
  { name: "Maire", email: "mahonmaire@gmail.com" },
  { name: "Orla", email: "orlaflood@gmail.com" },
  { name: "Irina ", email: "irina.shokina77755@gmail.com" },
  { name: "Síle", email: "silekearney99@gmail.com" },
  { name: "Sarah", email: "sarah.obrien59@gmail.com" },
  { name: "Anthony", email: "AnthonyG2412@gmail.com" },
  { name: "Nicky", email: "nickyallen63@gmail.com" },
  { name: "Annette", email: "achatham62@gmail.com" },
  { name: "Yuliia", email: "yulia.k1429@gmail.com" },
  { name: "Jamie ", email: "jamiejudgedl@gmail.com" },
  { name: "Savannah", email: "savannahcorry14@gmail.com" },
  { name: "Megan", email: "goodmegs23@gmail.com" },
  { name: "Laura", email: "laurahaugh09@gmail.com" },
  { name: "Siobhan", email: "siobhancopeland71@gmail.com" },
  { name: "Lucy", email: "lucycrean19@gmail.com" },
  { name: "Helen", email: "helenbomalley9@gmail.com" },
  { name: "moira", email: "mkglenmullen@gmail.com" },
  { name: "Anne ", email: "annandgerrymcconnon@gmail.com" },
  { name: "Annie", email: "anniegalligan@gmail.com" },
  { name: "Paula ", email: "pola11484@gmail.com" },
  { name: "Susan", email: "suez101@gmail.com" },
  { name: "Hazel", email: "hazelhiggins3@gmail.com" },
  { name: "Fiona", email: "fbishop72@gmail.com" },
  { name: "Cecilia", email: "ckeogh09@gmail.com" },
  { name: "Dagmar", email: "doring.dagmar@gmail.com" },
  { name: "Patrycja", email: "patrycja.juzwiak@gmail.com" },
  { name: "Lauren", email: "lauren.k.jones.4@gmail.com" },
  { name: "Ger", email: "gerribelles@gmail.com" },
  { name: "Sophie ", email: "hsophie1913@gmail.com" },
  { name: "Rachel", email: "fogartyrachel97@gmail.com" },
  { name: "Shauna", email: "shaunamccann90@gmail.com" },
  { name: "Emer", email: "emerhobbins16@gmail.com" },
  { name: "Grainne", email: "grainne1979@gmail.com" },
  { name: "Paula ", email: "pauladonovan498@gmail.com" },
  { name: "Eilis", email: "eilisnichonchuir@gmail.com" },
  { name: "Sarah", email: "Sarahc3611@gmail.com" },
  { name: "Anne Marie ", email: "anniem301187@gmail.com" },
  { name: "Caroline", email: "carolinemcelroyqqi@gmail.com" },
  { name: "Sarah", email: "sarahkett93@gmail.com" },
  { name: "Caroline ", email: "carolineomara1@gmail.com" },
  { name: "Melanie", email: "browne.melanie@gmail.com" },
  { name: "Lisa", email: "lisamanningdunne@gmail.com" },
  { name: "Nicole", email: "campionnic@gmail.com" },
  { name: "Brid", email: "bridsharpe@gmail.com" },
  { name: "Gillian", email: "Gilltims@gmail.com" },
  { name: "Sharon", email: "dunne.sharon1@gmail.com" },
  { name: "Ailin", email: "ailinmura@gmail.com" },
  { name: "Audrey ", email: "audhur66@gmail.com" },
  { name: "Roisin O", email: "Roisinoflynn@gmail.com" },
  { name: "Matthew", email: "mattwhelan1977@gmail.com" },
  { name: "deirdre", email: "deirdrea.hayes@gmail.com" },
  { name: "Annette ", email: "anet.forde@gmail.com" },
  { name: "Shane", email: "shanealexcollins@gmail.com" },
  { name: "Angela", email: "angela.galligan@gmail.com" },
  { name: "Sinead ", email: "sineadabuckley@gmail.com" },
  { name: "Niamh", email: "niamhtallon123@gmail.com" },
  { name: "Mary", email: "mary30henry@gmail.com" },
  { name: "Martina", email: "tina.cormack@gmail.com" },
  { name: "Michelle", email: "michelle.snowlion@gmail.com" },
  { name: "Niamh", email: "niamhmch@gmail.com" },
  { name: "Siobhan", email: "siobhanproud@gmail.com" },
  { name: "Marion", email: "marionfewer@gmail.com" },
  { name: "Clíona", email: "cliona.roisin.niclochlainn@gmail.com" },
  { name: "Lida", email: "lhda.zhkou@gmail.com" },
  { name: "Patrick", email: "marymbsmith@gmail.com" },
  { name: "Sarah", email: "sarahwhelan0709@gmail.com" },
  { name: "Jenny", email: "kevinbyrnedecorators@gmail.com" },
  { name: "Anne Marie", email: "annemariecorcoran@gmail.com" },
  { name: "Patrick", email: "marymbsmith@gmail.com" },
  { name: "Suzanne", email: "suzannecourtney789@gmail.com" },
  { name: "Suzanne", email: "suzannecourtney789@gmail.com" },
  { name: "Orla", email: "orlaquinntreacy@gmail.com" },
  { name: "Gillian", email: "lillygorman@gmail.com" },
  { name: "Patricia", email: "coadytrisha11@gmail.com" },
  { name: "Grainne", email: "grainne.ryan86@gmail.com" },
  { name: "Rachael", email: "rdgendunne@gmail.com" },
  { name: "Catherine", email: "catherinehayden100@gmail.com" },
  { name: "Wilma", email: "wilmaharteveld@gmail.com" },
  { name: "Helen", email: "HelenL1977@gmail.com" },
  { name: "Eimear", email: "eimeardrummond97@gmail.com" },
  { name: "Veronica", email: "veronocallaghan@gmail.com" },
  { name: "Maria", email: "Askinsm86@gmail.com" },
  { name: "Edel ", email: "edelmcdonald5@gmail.com" },
  { name: "Karen", email: "karentdeenihan@gmail.com" },
  { name: "Anne", email: "a.hogie22@gmail.com" },
  { name: "Grace", email: "gmeeley73@gmail.com" },
  { name: "Eibhin", email: "eibhin.nolan@gmail.com" },
  { name: "Claire", email: "clairergn7@gmail.com" },
  { name: "Aine", email: "aineffarrell@gmail.com" },
  { name: "Courtney", email: "courtneydunne3@gmail.com" },
  { name: "Grace", email: "gracebrosnan@gmail.com" },
  { name: "Mary", email: "msullyo@gmail.com" },
  { name: "Kellie", email: "kellieblake90@gmail.com" },
  { name: "Bernadette", email: "bernginnell@gmail.com" },
  { name: "Niamh", email: "niamhryan8@gmail.com" },
  { name: "Olivia", email: "oliviahiggins@gmail.com" },
  { name: "Sandy", email: "sandycurran27@gmail.com" },
  { name: "Emma", email: "Kayleehendrick11@gmail.com" },
  { name: "Nigel ", email: "lynniedonnelly@gmail.com" },
  { name: "Paula", email: "paula.usher@gmail.com" },
  { name: "sinead", email: "SINEADMGAYNOR@GMAIL.COM" },
  { name: "Mara", email: "missrodger@gmail.com" },
  { name: "Cathy", email: "cathy.w.austin@gmail.com" },
  { name: "Dawn", email: "dawnmulcair@gmail.com" },
  { name: "Sarah", email: "sarahdelany1803@gmail.com" },
  { name: "Niamh", email: "niamhryanlk3@gmail.com" },
  { name: "Claire", email: "28annabell@gmail.com" },
  { name: "Laura", email: "laura.kelly.a23@gmail.com" },
  { name: "Leona", email: "leonabroughton@gmail.com" },
  { name: "Nataliia ", email: "natakol1983@gmail.com" },
  { name: "Olivia", email: "Oliviaquinn02@gmail.com" },
  { name: "Sinead", email: "sleddy95@gmail.com" },
  { name: "Laura", email: "laura.morrison242@gmail.com" },
  { name: "Magdalena ", email: "magdalena.paradowska1@gmail.com" },
  { name: "Jacqui", email: "jac13byrne@gmail.com" },
  { name: "Sharon", email: "sharonmbrowne859@gmail.com" },
  { name: "Karen ", email: "karenog80@gmail.com" },
  { name: "Tracey ", email: "traceycomiskey045@gmail.com" },
  { name: "J.C.", email: "hynes.jcm49@gmail.com" },
  { name: "lyndsay ", email: "lyndsayob10@gmail.com" },
  { name: "Joanna", email: "joanna2110@gmail.com" },
  { name: "KIRSTY", email: "oconnellkirsty@gmail.com" },
  { name: "Nikola", email: "nikolagalka718@gmail.com" },
  { name: "Jayne", email: "calamityjaynemar46@gmail.com" },
  { name: "Denise", email: "denise1treacy@gmail.com" },
  { name: "Ciara", email: "nolan.ciara18@gmail.com" },
  { name: "Michelle ", email: "michelleoneill1234@gmail.com" },
  { name: "Hayley", email: "hayleyfarrell39@gmail.com" },
  { name: "Ann", email: "ann.snelgrove@gmail.com" },
  { name: "Lesley ", email: "lesleycosgrave@gmail.com" },
  { name: "Oonagh", email: "johnanthcarroll@gmail.com" },
  { name: "Anurag", email: "anuj.satna@gmail.com" },
  { name: "Rachael", email: "rmcgrath23@gmail.com" },
  { name: "Evelyn", email: "coadytrisha11@gmail.com" },
  { name: "Rasa", email: "rasamazeikaitee@gmail.com" },
  { name: "Yvonne", email: "yfay1973@gmail.com" },
  { name: "Izabela ", email: "izabeladnolan@gmail.com" },
];
async function main() {
  for (const { name, email } of data) {
    const emailExists = await (function doesEmailExist(): Promise<number> {
      return new Promise(function (resolve, reject) {
        db.get(
          `SELECT count(email) as count FROM emails WHERE email = ?`,
          [email],
          function (err: any, row: { count: number }) {
            return err ? reject(err) : resolve(row.count);
          }
        );
      });
    })();

    if (emailExists) {
      console.log("email exists");
      continue;
    }

    const msg = {
      to: email,
      from: "daryl@beautyfeatures.ie",
      subject: /*HTML*/`Hi ${name}... How Did BeautyFeatures.ie Do?`,
      html: /*HTML*/ `<p>Dear ${name}</p>
      <p>Getting feedback from our customers is of great value to us to continually improve our customer service. We would really appreciate your assistance in leaving a Google review for our business. It will also help potential customers in their choice to shop with us. Simply <a href="https://g.page/r/CXRQBST7AgQMEAI/review" target="_blank" rel="noopener noreferrer">click here</a> to leave your review.</p>
      <p>Your satisfaction as a customer is incredibly important to us, and we&rsquo;re passionate about providing an excellent service. We truly value your feedback and your time, which helps us to continue to provide exceptional service to all our customers.</p>
      <p>If you have any questions or need further assistance, please don&apos;t hesitate to reach out to our customer support team. We are here to help!</p>
      <p>Thanks again for shopping at BeautyFeatures.ie and supporting an Irish company. Your satisfaction is our top priority, and we hope to see you again soon!</p>
      <p>Best regards,</p>
      <p>Daryl Divilly</p>
      <p>Managing Director</p>`,
    };

    try {
      await sgMail.send(msg);
      await (function recordEmailAddress() {
        return new Promise((resolve, reject) =>
          db.run(`INSERT INTO emails(email) VALUES(?)`, [email], (err) =>
            err ? reject(err) : resolve(undefined)
          )
        );
      })();
      console.log(`email sent to ${name} => ${email}`);
    } catch (err: any) {
      console.log(err.response ? err.response.body : err);
      break;
    }
  }
}
main();
