import { updateProductVariant } from "../../functions/product-variants/updateProductVariant";
import { getProductBySku } from "../../functions/products/getProductBySKU";
//import { getProductById } from "../../functions/products/getProductById";
import { getProductVariants } from "../../functions/products/getProductVariants";
import { updateProduct } from "../../functions/products/updateProduct";

require("../../config/config").config("ih");
const no_discount_category_ID = 1493;
const data = [
  {
    sku: "7553",
    description: "Ortel-P Pelvic Maternity Size 1 - Hip Size (cm) 83-89",
    stock: 1,
    cost_price: 29.99,
    margin: "10%",
    sale_price: 40.99,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7139",
    description: "Haakaa Stainless Steel Straw Straight With Ridges - M(3P)",
    stock: 20,
    cost_price: 3.38,
    margin: "10%",
    sale_price: 4.62,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "5303",
    description: "Haakaa Silicone Breast Pump Lid (Fits 100ml or 150ml)",
    stock: 263,
    cost_price: 1.51,
    margin: "10%",
    sale_price: 2.06,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6435",
    description: "Haakaa Flow Cup (Menstrual Cup) 18ml Valve",
    stock: 166,
    cost_price: 3.49,
    margin: "10%",
    sale_price: 4.77,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6099",
    description: "Haakaa 300ml Wide Neck Stainless Steel Baby Bottle - Blue",
    stock: 5,
    cost_price: 17.07,
    margin: "10%",
    sale_price: 23.33,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "40671",
    description: "Gro Fabric And Pattern Set",
    stock: 3,
    cost_price: 0.01,
    margin: "10%",
    sale_price: 0.01,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "40528",
    description: "Carriwell Lace Drop Cup Nursing Bra White Vii",
    stock: 1,
    cost_price: 14.09,
    margin: "10%",
    sale_price: 19.26,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "41500",
    description: "Ardo Tube Connector For Pumpset",
    stock: 4,
    cost_price: 2.7,
    margin: "10%",
    sale_price: 3.69,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6103",
    description: "Haakaa Wide Neck Anti-Colic Nipple (M)",
    stock: 28,
    cost_price: 2.85,
    margin: "10%",
    sale_price: 3.9,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8285",
    description: "Clevamama Blackout Blinds",
    stock: 136,
    cost_price: 12.39,
    margin: "10%",
    sale_price: 16.93,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6102",
    description: "Haakaa Wide Neck Anti-Colic Nipple (L)",
    stock: 31,
    cost_price: 2.85,
    margin: "10%",
    sale_price: 3.9,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7649",
    description: "Haakaa Silicone Re-Usable Straws - 6 Pack with Cleaner",
    stock: 61,
    cost_price: 5.44,
    margin: "10%",
    sale_price: 7.43,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7247",
    description: "Haakaa Premium Silicone Pump and Bottle Pack - Nude",
    stock: 8,
    cost_price: 34.3504,
    margin: "10%",
    sale_price: 46.95,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "5680",
    description: "Babydan Head Rest Mounted Tablet Holder",
    stock: 15,
    cost_price: 7.88,
    margin: "10%",
    sale_price: 10.77,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9654",
    description: "Haakaa Deluxe Express & Collect Travel Pack",
    stock: 37,
    cost_price: 24.3143,
    margin: "10%",
    sale_price: 33.23,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9583",
    description: "Haakaa Fresh Food Feeder and Teether  Blue",
    stock: 13,
    cost_price: 5.44,
    margin: "10%",
    sale_price: 7.43,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9584",
    description: "Haakaa Fresh Food Feeder and Teether - Copper",
    stock: 13,
    cost_price: 5.44,
    margin: "10%",
    sale_price: 7.43,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9586",
    description: "Haakaa Fresh Food Feeder and Teether - Steel Blue",
    stock: 1,
    cost_price: 5.44,
    margin: "10%",
    sale_price: 7.43,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9588",
    description: "Haakaa Fresh Food Feeder and Teether Pink",
    stock: 5,
    cost_price: 5.44,
    margin: "10%",
    sale_price: 7.43,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9587",
    description: "Haakaa Fresh Food Feeder and Teether- Slate Grey",
    stock: 23,
    cost_price: 5.44,
    margin: "10%",
    sale_price: 7.43,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7112",
    description: "Haakaa Generation 3 Silicone Breast Pump 160Ml - Grey",
    stock: 81,
    cost_price: 8.92,
    margin: "10%",
    sale_price: 12.19,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6100",
    description: "Haakaa Nano Silver Silicone Soother",
    stock: 773,
    cost_price: 4.2546,
    margin: "10%",
    sale_price: 5.81,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8711",
    description: "Haakaa Natural Rubber Owl Teether - Smiling",
    stock: 351,
    cost_price: 5.87,
    margin: "10%",
    sale_price: 8.02,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9598",
    description: "Haakaa Silicone Baby Bib - Cobalt",
    stock: 11,
    cost_price: 3.98,
    margin: "10%",
    sale_price: 5.44,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9599",
    description: "Haakaa Silicone Baby Bib - Ruby",
    stock: 13,
    cost_price: 3.98,
    margin: "10%",
    sale_price: 5.44,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9606",
    description: "Haakaa Silicone Colostrum Collector",
    stock: 15,
    cost_price: 1.5641,
    margin: "10%",
    sale_price: 2.14,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9006",
    description: "Haakaa Silicone Colostrum Collector Set",
    stock: 47,
    cost_price: 5.0769,
    margin: "10%",
    sale_price: 6.94,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7141",
    description: "Haakaa Stainless Steel Straw Straight With Ridges- S (3P)",
    stock: 61,
    cost_price: 3.38,
    margin: "10%",
    sale_price: 4.62,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7462",
    description: "Haakaa Silicone Inverted Nipple Corrector",
    stock: 144,
    cost_price: 5.38,
    margin: "10%",
    sale_price: 7.35,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9565",
    description: "Durex Cherry Lube 100ml",
    stock: 3,
    cost_price: 5.79,
    margin: "10%",
    sale_price: 7.91,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8594",
    description: "Chicco Dream Light Bear - Blue",
    stock: 1,
    cost_price: 6.8571,
    margin: "10%",
    sale_price: 9.37,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8712",
    description: "Haakaa Silicone Baby Food Dispensing Spoon - Grey",
    stock: 188,
    cost_price: 7.33,
    margin: "10%",
    sale_price: 10.02,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7131",
    description: "Haakaa Silicone Breast Pump Flower Stopper - White",
    stock: 330,
    cost_price: 3.32,
    margin: "10%",
    sale_price: 4.54,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8710",
    description: "Haakaa Newborn Silicone Dummy",
    stock: 358,
    cost_price: 5.87,
    margin: "10%",
    sale_price: 8.02,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "5304",
    description: "Haakaa Silicone Breast Pump Flower Stopper - Purple",
    stock: 1002,
    cost_price: 3.32,
    margin: "10%",
    sale_price: 4.54,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6881",
    description: "B.D.A™ Bra – Belly Bandit - Black - M",
    stock: 2,
    cost_price: 24.98,
    margin: "10%",
    sale_price: 34.14,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6906",
    description: "Belly Bandit Bump Support Legging - Black - S",
    stock: 1,
    cost_price: 37.48,
    margin: "10%",
    sale_price: 51.22,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6930",
    description: "Belly Bandit C-Section &Hipster Briefs - Nude - XL",
    stock: 3,
    cost_price: 22.48,
    margin: "10%",
    sale_price: 30.72,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "5160",
    description: "Belly Bandit Belly Shield - Black - LG-2XL",
    stock: 1,
    cost_price: 20.97,
    margin: "10%",
    sale_price: 28.66,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6947",
    description: "Belly Bandit Mother Tucker Shortie - Black - XS",
    stock: 1,
    cost_price: 29.98,
    margin: "10%",
    sale_price: 40.97,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9174",
    description:
      "Carriwell Maternity & Nursing Bra with Padded Carri-Gel support White 2XLarge",
    stock: 1,
    cost_price: 25.62,
    margin: "10%",
    sale_price: 35.01,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7246",
    description: "Haakaa Premium Silicone Pump and Bottle Pack - Grey",
    stock: 8,
    cost_price: 34.3504,
    margin: "10%",
    sale_price: 46.95,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9629",
    description: "Haakaa Silicone Teething Ball-Charcoal",
    stock: 42,
    cost_price: 2.93,
    margin: "10%",
    sale_price: 4.0,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9571",
    description:
      "Haakaa Baby Food and Breast Milk Freezer Tray - 4 Compartments - Pea Green",
    stock: 12,
    cost_price: 5.42,
    margin: "10%",
    sale_price: 7.41,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9570",
    description:
      "Haakaa Baby Food and Breast Milk Freezer Tray - 4 Compartments - Blush",
    stock: 6,
    cost_price: 5.42,
    margin: "10%",
    sale_price: 7.41,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9568",
    description:
      "Haakaa Baby Food and Breast Milk Freezer Tray - 4 Compartments - Apricot",
    stock: 9,
    cost_price: 5.42,
    margin: "10%",
    sale_price: 7.41,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "10374",
    description: "Little Green Baby Baby Bathtime Bundle",
    stock: 5,
    cost_price: 14,
    margin: "10%",
    sale_price: 19.13,
    bf_product: "TRUE",
    ih_product: "TRUE",
  },
  {
    sku: "10758",
    description: "Mama Mio Mini Mio Bundle of Joy Gift Set",
    stock: 14,
    cost_price: 13.41463415,
    margin: "10%",
    sale_price: 18.33,
    bf_product: "TRUE",
    ih_product: "TRUE",
  },
  {
    sku: "8053A",
    description: "Matchstick Monkey Dancing Monkey Teether Pink",
    stock: 6,
    cost_price: 9.614723779,
    margin: "10%",
    sale_price: 13.14,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8605",
    description: "Mio Muscle Motivator Revitalising Gel",
    stock: 10,
    cost_price: 11.17886179,
    margin: "10%",
    sale_price: 15.28,
    bf_product: "TRUE",
    ih_product: "TRUE",
  },
  {
    sku: "8606",
    description: "Mio Clay Away Body Cleanser",
    stock: 4,
    cost_price: 8.943089431,
    margin: "10%",
    sale_price: 12.22,
    bf_product: "TRUE",
    ih_product: "TRUE",
  },
  {
    sku: "9417",
    description: "ZAZU Musical Soft Toy - DEX",
    stock: 1,
    cost_price: 17.41,
    margin: "10%",
    sale_price: 23.79,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6501",
    description: "Clippasafe Pregnancy Bump Belt",
    stock: 3,
    cost_price: 19.1648,
    margin: "10%",
    sale_price: 26.19,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "11711",
    description: "Non Contact Infrared Thermometer",
    stock: 9,
    cost_price: 10.5,
    margin: "10%",
    sale_price: 14.35,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "10538",
    description: "Tonies Disney - Finding Nemo Audio Tonie",
    stock: 2,
    cost_price: 10.36,
    margin: "10%",
    sale_price: 14.16,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "10521",
    description: "Tonies Favourite Tales - Little Red Riding Hood Audio Tonie",
    stock: 1,
    cost_price: 10.36,
    margin: "10%",
    sale_price: 14.16,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "10522",
    description: "Tonies Disney - The Jungle Book - Baloo Audio Tonie",
    stock: 1,
    cost_price: 10.36,
    margin: "10%",
    sale_price: 14.16,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "10537",
    description: "Tonies Disney - Cinderella Audio Tonie",
    stock: 1,
    cost_price: 10.36,
    margin: "10%",
    sale_price: 14.16,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "10536",
    description: "Tonies Disney - Toy Story Audio Tonie",
    stock: 2,
    cost_price: 10.36,
    margin: "10%",
    sale_price: 14.16,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "10005",
    description:
      "Beaba Stainless steel storage pot 300ml - Dark Mist/Light Pink",
    stock: 3,
    cost_price: 9.92,
    margin: "10%",
    sale_price: 13.56,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "10006",
    description: "Beaba Stainless steel storage pot 500ml - Baltic Blue/White",
    stock: 3,
    cost_price: 11.3516,
    margin: "10%",
    sale_price: 15.51,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "10007",
    description:
      "Beaba Stainless steel storage pot 500ml - Light Pink/Night Blue",
    stock: 3,
    cost_price: 12.4,
    margin: "10%",
    sale_price: 16.95,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6883",
    description: "B.D.A™ Bra – Belly Bandit - Black - XL",
    stock: 4,
    cost_price: 24.98,
    margin: "10%",
    sale_price: 34.14,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6877",
    description: "Bandita Nursing Bra - Belly Bandit  - Black - M",
    stock: 1,
    cost_price: 28.48,
    margin: "10%",
    sale_price: 38.92,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "11448",
    description: "Health & Her Aromatherapy Sleep Balm 40g",
    stock: 4,
    cost_price: 5.22,
    margin: "10%",
    sale_price: 7.13,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "11917",
    description: "Beautiful Beginnings Fun Time Shape Sorter Ball",
    stock: 2,
    cost_price: 6.54,
    margin: "10%",
    sale_price: 8.94,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6999",
    description: "Earth Friendly Baby Calming Lavender Body Lotion 250ml",
    stock: 2,
    cost_price: 3.2967,
    margin: "10%",
    sale_price: 4.51,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7001",
    description:
      "Earth Friendly Baby Calming Lavender Shampoo & Bodywash 250ml",
    stock: 1,
    cost_price: 2.6264,
    margin: "10%",
    sale_price: 3.59,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7004",
    description: "Earth Friendly Baby Moisturising Shea Massage Oil 125ml",
    stock: 4,
    cost_price: 2.6264,
    margin: "10%",
    sale_price: 3.59,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "100270",
    description: "Drugs Test Card (Screens For 10 Substances)",
    stock: 23,
    cost_price: 3.0769,
    margin: "10%",
    sale_price: 4.21,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "11727",
    description: "Izmi Baby Wrap  Bamboo - Grey",
    stock: 1,
    cost_price: 44.19,
    margin: "10%",
    sale_price: 60.39,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "11726",
    description: "Izmi Baby Wrap Bamboo - Slate",
    stock: 1,
    cost_price: 44.19,
    margin: "10%",
    sale_price: 60.39,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7554",
    description: "Ortel-P Pelvic Maternity Size 2 - Hip Size (cm) 90-96",
    stock: 2,
    cost_price: 29.99,
    margin: "10%",
    sale_price: 40.99,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7557",
    description: "Ortel-P Pelvic Maternity Size 5 - Hip Size (cm) 115-125",
    stock: 1,
    cost_price: 27,
    margin: "10%",
    sale_price: 36.9,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7557A",
    description: "Ortel-P Pelvic Maternity Size 6 - Hip Size (cm) 126-136",
    stock: 2,
    cost_price: 27,
    margin: "10%",
    sale_price: 36.9,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "5173",
    description: "Pharmony Gripe Water 150ml",
    stock: 7,
    cost_price: 3.21,
    margin: "10%",
    sale_price: 4.39,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "4429",
    description: "Relactagel",
    stock: 3,
    cost_price: 8.06,
    margin: "10%",
    sale_price: 11.02,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "11921",
    description: "Studio Circus Wooden Train Set Animals 18+ Months",
    stock: 2,
    cost_price: 10,
    margin: "10%",
    sale_price: 13.67,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "11955",
    description:
      "Clevamama Mum2Me Maternity Pillow & Baby Pod - Grey / Yellow Stripes",
    stock: 23,
    cost_price: 69.42,
    margin: "10%",
    sale_price: 94.87,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7658",
    description: "Joie Bold Group 1/2/3 Car Seat - Slate",
    stock: 1,
    cost_price: 155,
    margin: "10%",
    sale_price: 211.83,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8544",
    description: "Dreambaby Bib / Smocks With Sleeves - Zookeeper & Doctor 2Pk",
    stock: 1,
    cost_price: 6.33,
    margin: "10%",
    sale_price: 8.65,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7735",
    description: "Dreambaby Chelsea 9cm Wide Gate Extension (White)",
    stock: 3,
    cost_price: 6.33,
    margin: "10%",
    sale_price: 8.65,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7742",
    description: "Dreambaby Chelsea 100cm Wide Gate Extension (White)",
    stock: 4,
    cost_price: 28.47,
    margin: "10%",
    sale_price: 38.91,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7737",
    description: "Dreambaby Chelsea 27cm Wide Gate Extension (White)",
    stock: 9,
    cost_price: 11.39,
    margin: "10%",
    sale_price: 15.57,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7738",
    description: "Dreambaby Chelsea 36cm Wide Gate Extension (White)",
    stock: 5,
    cost_price: 13.09,
    margin: "10%",
    sale_price: 17.89,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7739",
    description: "Dreambaby Chelsea 45cm Wide Gate Extension (White)",
    stock: 3,
    cost_price: 16.45,
    margin: "10%",
    sale_price: 22.48,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "7734a",
    description: "Dreambaby Chelsea Auto-Close Gate Black ( Fits 71cm - 80cm)",
    stock: 1,
    cost_price: 31.56,
    margin: "10%",
    sale_price: 43.13,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6925",
    description: "Belly Bandit C-Section &Hipster Briefs - Black - XL",
    stock: 1,
    cost_price: 29.98,
    margin: "10%",
    sale_price: 40.97,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6919",
    description: "C-Section &Undies | Belly Bandit®  - Nude - XL",
    stock: 1,
    cost_price: 37.48,
    margin: "10%",
    sale_price: 51.22,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8566",
    description: "Chicco Chairy Booster Seat Bunny (Grey)",
    stock: 3,
    cost_price: 34.37,
    margin: "10%",
    sale_price: 46.97,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6327",
    description: "Chicco Next2Stars Baby Night Light Projector Blue",
    stock: 8,
    cost_price: 18.74,
    margin: "10%",
    sale_price: 25.61,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6328",
    description: "Chicco Next2Stars Baby Night Light Projector Pink",
    stock: 2,
    cost_price: 18.74,
    margin: "10%",
    sale_price: 25.61,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8591",
    description: "Chicco First Dreams Baby Bear Neutral",
    stock: 4,
    cost_price: 18.74,
    margin: "10%",
    sale_price: 25.61,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8590",
    description: "Chicco First Dreams Baby Bear Blue",
    stock: 5,
    cost_price: 21.7907,
    margin: "10%",
    sale_price: 29.78,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8600",
    description: "Chicco First Dreams Lullaby Sheep - Blue",
    stock: 2,
    cost_price: 13.3516,
    margin: "10%",
    sale_price: 18.25,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8560",
    description: "Chicco Storage Net Black",
    stock: 5,
    cost_price: 4.06,
    margin: "10%",
    sale_price: 5.55,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8592",
    description: "Chicco First Dreams Baby Bear Pink",
    stock: 5,
    cost_price: 21.7907,
    margin: "10%",
    sale_price: 29.78,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8587",
    description: "Chicco Baby Hug 4 In 1 Meal Kit (Tray And Terry Cover) White",
    stock: 1,
    cost_price: 28.12,
    margin: "10%",
    sale_price: 38.43,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8599",
    description: "Chicco First DreamsLullaby Sheep - Pink",
    stock: 4,
    cost_price: 13.86,
    margin: "10%",
    sale_price: 18.94,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8597",
    description: "Chicco First Dreams Next2Stars Projector Neutral",
    stock: 7,
    cost_price: 18.74,
    margin: "10%",
    sale_price: 25.61,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6325",
    description: "Chicco Night Breeze Mattress Cover",
    stock: 10,
    cost_price: 13.75,
    margin: "10%",
    sale_price: 18.79,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8571",
    description: "Chicco Relax And Play Electronic Swing Cool Grey",
    stock: 1,
    cost_price: 55.63,
    margin: "10%",
    sale_price: 76.03,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8576",
    description: "Chicco Next2Me Air Side Sleeping Crib Titanium",
    stock: 1,
    cost_price: 103.2088,
    margin: "10%",
    sale_price: 141.05,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "12723",
    description: "Haakaa PRE-STERILISED Silicone Colostrum Collector Set 2pk",
    stock: 61,
    cost_price: 3.8167,
    margin: "10%",
    sale_price: 5.22,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6979",
    description: "breastvest - Breastfeeding top - Black- X-Large",
    stock: 1,
    cost_price: 7.6923,
    margin: "10%",
    sale_price: 10.51,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6975",
    description: "breastvest - Breastfeeding top - Black- X-Small",
    stock: 5,
    cost_price: 7.6923,
    margin: "10%",
    sale_price: 10.51,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6980",
    description: "breastvest - Breastfeeding top - White- X-Small",
    stock: 9,
    cost_price: 7.6923,
    margin: "10%",
    sale_price: 10.51,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "8798",
    description: "Haakaa Easy-Squeezy Silicone Bulb Syringe",
    stock: 58,
    cost_price: 1.53,
    margin: "10%",
    sale_price: 2.09,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9594",
    description: "Haakaa Pear-fect Manicure Kit - Pearl White",
    stock: 3,
    cost_price: 2.75,
    margin: "10%",
    sale_price: 3.76,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "5383",
    description: "Haakaa Silicone Nipple Shields - 2 Pack",
    stock: 174,
    cost_price: 5.41,
    margin: "10%",
    sale_price: 7.39,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6435B",
    description: "Haakaa Flow Cup (Menstrual Cup) Short Stem Flow Cup 30ml",
    stock: 90,
    cost_price: 2.8614,
    margin: "10%",
    sale_price: 3.91,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6435A",
    description: "Haakaa Flow Cup (Menstrual Cup) Short Stem Flow Cup 25ml",
    stock: 109,
    cost_price: 2.8614,
    margin: "10%",
    sale_price: 3.91,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9593",
    description: "Haakaa Pear-fect Manicure Kit - Mint Green",
    stock: 42,
    cost_price: 2.8205,
    margin: "10%",
    sale_price: 3.85,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9580",
    description: "Haakaa Breast Massager (Shell)",
    stock: 21,
    cost_price: 16.15,
    margin: "10%",
    sale_price: 22.07,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "13155",
    description: "Haakaa Bendy Silicone Cutlery Set Grey",
    stock: 99,
    cost_price: 2.65,
    margin: "10%",
    sale_price: 3.62,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9591",
    description: "Haakaa Pear-fect Manicure Kit - Coffee",
    stock: 5,
    cost_price: 2.75,
    margin: "10%",
    sale_price: 3.76,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "9592",
    description: "Haakaa Pear-fect Manicure Kit - Lemon Yellow",
    stock: 2,
    cost_price: 2.75,
    margin: "10%",
    sale_price: 3.76,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "13154",
    description: "Lansinoh Washable Nursing Pads 8Pk",
    stock: 3,
    cost_price: 11.2209,
    margin: "10%",
    sale_price: 15.34,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
  {
    sku: "6135",
    description: "Britax Romer Dualfix M isize Black (Birth to 4 Yrs)",
    stock: 3,
    cost_price: 250,
    margin: "10%",
    sale_price: 341.67,
    bf_product: "FALSE",
    ih_product: "TRUE",
  },
];

async function main() {
  // identify product ids
  // reduce to 15% margin
  // add to clearance sections
  for (const row of data) {
    try {
      console.log(`finding product id for sku: ${row.sku}...`);
      const product = await getProductBySku(row.sku);
      const variants = await getProductVariants(product.id);
      //const product = await getProductById(p_id);

      if (variants.length === 1 && variants[0].sku_id === null) {
        console.log("only one base variant. updating product");
        let updates: any = {
          sale_price: row.sale_price,
        };
        if (!product.categories.includes(no_discount_category_ID)) {
          updates.categories = [...product.categories, no_discount_category_ID];
        }
        // update product
        await updateProduct(product.id, updates);
      } else {
        console.log("looking for variant");
        const variant = variants.find((v) => v.sku === row.sku);
        if (variant) {
          console.log("variant found");

          if (!product.categories.includes(no_discount_category_ID)) {
            await updateProduct(product.id, {
              categories: [...product.categories, no_discount_category_ID],
            });
          }

          // update variant
          await updateProductVariant(product.id, variant.id, {
            sale_price: row.sale_price,
          });
        }
      }
      console.log(`updated product with sku: ${row.sku}`);
    } catch (err) {
      console.log(err);
      continue;
    }
  }
  console.log("done");
}
main();
