require("../../config/config").config("bf");
const { applyFilter } = require("../../functions/filters/applyFilter");
const {
  getProductIdByName,
} = require("../../functions/products/getProductIdByName");

const data = [
  {
    Key: "Skin Concerns",
    Value: "Acne / Blemish",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "X",
    "Decleor Green Mandarin Scrub Mask 50ml": "X",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "X",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "X",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "X",
    "Decleor Rosemary Active Essence 200ml": "X",
    "Decleor Rosemary Night Balm 15ml": "X",
    "Decleor Rosemary Targeted Care 9ml": "X",
    "Decleor Rosemary Black Clay Mask 50ml": "X",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "X",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "X",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Skin Concerns",
    Value: "Anti Pollution",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "X",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "X",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "X",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "X",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "X",
    "Decleor Rosemary Active Essence 200ml": "X",
    "Decleor Rosemary Night Balm 15ml": "X",
    "Decleor Rosemary Targeted Care 9ml": "X",
    "Decleor Rosemary Black Clay Mask 50ml": "X",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "X",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Skin Concerns",
    Value: "Dark Circles",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "X",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "X",
    "Decleor Antidote Serum 30ml": "",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "X",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Skin Concerns",
    Value: "Dry Skin",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "X",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "X",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "X",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "X",
    "Decleor Lavande Fine Bath & Shower Gel": "X",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "X",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "X",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "X",
    "Decleor White Magnolia Rosy Cream 50ml": "X",
    "Decleor White Magnolia Collection": "X",
    "Decleor White Magnolia Mask 50ml": "X",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "X",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "X",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "X",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "X",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "X",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "X",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "X",
    "Decleor Aromessence Neroli Bigarade": "X",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "X",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "X",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "X",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Skin Concerns",
    Value: "Dull Skin",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "X",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "X",
    "Decleor Eye Cream Jasmine 15ml": "X",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "X",
    "Decleor Green Mandarin Scrub Mask 50ml": "X",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "X",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "X",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "X",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "X",
    "Decleor Neroli Bigarade Facial Toner 400ml": "X",
    "Decleor Neroli Bigarade Body Milk 195ml": "X",
    "Decleor Neroli Bigarade Oil Mask 50ml": "X",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "X",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "X",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "X",
  },
  {
    Key: "Skin Concerns",
    Value: "Fine Lines",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "X",
    "Decleor Light Day Cream Lavender Fine 50ml": "X",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "X",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "X",
    "Decleor Green Mandarin Scrub Mask 50ml": "X",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "X",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "X",
    "Decleor White Magnolia Rosy Cream 50ml": "X",
    "Decleor White Magnolia Collection": "X",
    "Decleor White Magnolia Mask 50ml": "X",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "X",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "X",
    "Decleor Aromessence Neroli Bigarade": "X",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "X",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "X",
  },
  {
    Key: "Skin Concerns",
    Value: "Hyperpigmentation",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Skin Concerns",
    Value: "Oiliness",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "X",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "X",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "X",
    "Decleor Rosemary Active Essence 200ml": "X",
    "Decleor Rosemary Night Balm 15ml": "X",
    "Decleor Rosemary Targeted Care 9ml": "X",
    "Decleor Rosemary Black Clay Mask 50ml": "X",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "X",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Skin Concerns",
    Value: "Pregnancy Safe",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Skin Concerns",
    Value: "Psoriasis",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "X",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Skin Concerns",
    Value: "Redness/ Rosacea",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "X",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "X",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "X",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "X",
    "Decleor Rosemary Active Essence 200ml": "X",
    "Decleor Rosemary Night Balm 15ml": "X",
    "Decleor Rosemary Targeted Care 9ml": "X",
    "Decleor Rosemary Black Clay Mask 50ml": "X",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "X",
    "Decleor Aromessence - White Magnolia 15ml": "X",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "X",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "X",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Skin Concerns",
    Value: "Sensitive Skin",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "X",
    "Decleor Eye Cream Absolute - Peony 15ml": "X",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "X",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "X",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "X",
    "Decleor Cica Botanic Mask 50ml": "X",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "X",
    "Decleor White Magnolia Intensive Cure 75ml": "X",
    "Decleor White Magnolia Rosy Cream 50ml": "X",
    "Decleor White Magnolia Collection": "X",
    "Decleor White Magnolia Mask 50ml": "X",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "X",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "X",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "X",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "X",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Skin Concerns",
    Value: "White / Blackheads",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "X",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "X",
    "Decleor Rosemary Active Essence 200ml": "X",
    "Decleor Rosemary Night Balm 15ml": "X",
    "Decleor Rosemary Targeted Care 9ml": "X",
    "Decleor Rosemary Black Clay Mask 50ml": "X",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "X",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Key Ingredients",
    Value: "Antioxidants",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "X",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "X",
    "Decleor Green Mandarin Scrub Mask 50ml": "X",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "X",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "X",
    "Decleor White Magnolia Rosy Cream 50ml": "X",
    "Decleor White Magnolia Collection": "X",
    "Decleor White Magnolia Mask 50ml": "X",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "X",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "X",
    "Decleor Rosemary Active Essence 200ml": "X",
    "Decleor Rosemary Night Balm 15ml": "X",
    "Decleor Rosemary Targeted Care 9ml": "X",
    "Decleor Rosemary Black Clay Mask 50ml": "X",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "X",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "X",
  },
  {
    Key: "Key Ingredients",
    Value: "Glycolic Acid",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "X",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Key Ingredients",
    Value: "Hyaluronic Acid",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "X",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "X",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Key Ingredients",
    Value: "Retinol",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Key Ingredients",
    Value: "Salicylic Acid",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "X",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "X",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "X",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Key Ingredients",
    Value: "Vegan",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Key Ingredients",
    Value: "Vitamin C",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "X",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "X",
    "Decleor Green Mandarin Scrub Mask 50ml": "X",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "X",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "X",
  },
  {
    Key: "Skin Type",
    Value: "Dry Skin",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "X",
    "Decleor Eye Cream Absolute - Peony 15ml": "X",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "X",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "X",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "X",
    "Decleor Green Mandarin Scrub Mask 50ml": "X",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "X",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "X",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "X",
    "Decleor White Magnolia Rosy Cream 50ml": "X",
    "Decleor White Magnolia Collection": "X",
    "Decleor White Magnolia Mask 50ml": "X",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "X",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "X",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "X",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "X",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "X",
    "Decleor Neroli Bigarade Oil Mask 50ml": "X",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "X",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "X",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "X",
    "Decleor Aromessence Neroli Bigarade": "X",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "X",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "X",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "X",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
  {
    Key: "Skin Type",
    Value: "Dull Skin",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "X",
    "Decleor Eye Cream Jasmine 15ml": "X",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "X",
    "Decleor Green Mandarin Scrub Mask 50ml": "X",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "X",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "X",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "X",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "X",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "X",
  },
  {
    Key: "Skin Type",
    Value: "Normal & Combination",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "",
    "Decleor Eye Cream Absolute - Peony 15ml": "",
    "Decleor Light Day Cream Lavender Fine 50ml": "X",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "X",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "",
    "Decleor Night Balm Green Mandarin 15ml": "X",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "X",
    "Decleor Green Mandarin Scrub Mask 50ml": "X",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "",
    "Decleor Cica Botanic Mask 50ml": "X",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "",
    "Decleor White Magnolia Intensive Cure 75ml": "",
    "Decleor White Magnolia Rosy Cream 50ml": "",
    "Decleor White Magnolia Collection": "",
    "Decleor White Magnolia Mask 50ml": "",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "X",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "X",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "X",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "X",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "X",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "X",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "X",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "X",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "X",
    "Decleor Rosemary Active Essence 200ml": "X",
    "Decleor Rosemary Night Balm 15ml": "X",
    "Decleor Rosemary Targeted Care 9ml": "X",
    "Decleor Rosemary Black Clay Mask 50ml": "X",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "X",
    "Decleor Aromessence - White Magnolia 15ml": "",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "X",
    "Decleor Aromessence Neroli Bigarade": "X",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "X",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "",
    "Decleor Aromessence Mandarine Verte 15ml": "X",
  },
  {
    Key: "Skin Type",
    Value: "Sensitive Skin",
    "Decleor Day Cream and Mask - Rose Damascena 50ml": "X",
    "Decleor Eye Cream Absolute - Peony 15ml": "X",
    "Decleor Light Day Cream Lavender Fine 50ml": "",
    "Decleor HamamÃ©lis Bi-Phase Makeup Remover Face & Eyes 200ml": "X",
    "Decleor Cica-Botanic Eucalyptus Balm 50ml": "X",
    "Decleor Night Balm Green Mandarin 15ml": "",
    "Decleor Eye Cream Jasmine 15ml": "",
    "Decleor Antidote Serum 30ml": "X",
    "Decleor Green Mandarin Overnight Bi Phase Peel 30ml": "",
    "Decleor Green Mandarin Scrub Mask 50ml": "",
    "Decleor Lavande Fine Bath & Shower Gel": "",
    "Decleor Shower Gel Rose 250ml": "X",
    "Decleor Cica Botanic Mask 50ml": "X",
    "Decleor Green Mandarin Vitamin Glow Cream 50ml": "",
    "Decleor Rich Lifting Cream Lavender Iris 50ml": "",
    "Decleor Cornflower Eye Gel 15ml": "X",
    "Decleor White Magnolia Intensive Cure 75ml": "X",
    "Decleor White Magnolia Rosy Cream 50ml": "X",
    "Decleor White Magnolia Collection": "X",
    "Decleor White Magnolia Mask 50ml": "X",
    "Decleor Rich Day Cream Neroli Bigarade 50ml": "",
    "Decleor - Light Day Cream Neroli Bigarade - 50ml": "",
    "Decleor Baume De Nuit (Night Balm) Neroli Bigarade 15ml": "",
    "Decleor Cocoon Day Cream Neroli Bigarade 50ml": "",
    "Decleor Aroma Cleanse Cleansing Milk with Neroli 400ml": "",
    "Decleor Shower Gel Neroli 250ml": "",
    "Decleor Luxury Size Neroli Shower Gel 400ml": "",
    "Decleor Neroli Bigarade Cleansing Mousse 100ml": "",
    "Decleor Aroma Cleanse Tonifying Lotion with Neroli 400ml": "",
    "Decleor Luxury Size Neroli Bigarade Gradual Glow Lotion 400ml": "",
    "Decleor Neroli Bigarade Cleansing Micellar Oil 195ml": "X",
    "Decleor Neroli Bigarade Facial Toner 400ml": "",
    "Decleor Neroli Bigarade Body Milk 195ml": "",
    "Decleor Neroli Bigarade Oil Mask 50ml": "",
    "Decleor Neroli Bigarade Gradual Glow Lotion 200ml": "",
    "Decleor Rosemary White Clay Daily Care 50ml": "",
    "Decleor Rosemary Black Clay Cleansing Gel 100ml": "",
    "Decleor Rosemary Active Essence 200ml": "",
    "Decleor Rosemary Night Balm 15ml": "",
    "Decleor Rosemary Targeted Care 9ml": "",
    "Decleor Rosemary Black Clay Mask 50ml": "",
    "Decleor Rosemary Handwash Scrub 400ml": "",
    "Decleor Rosemary Bundle": "",
    "Decleor Aromessence - White Magnolia 15ml": "X",
    "Decleor Aromessence Lavande Fine Oil Serum 15ml": "",
    "Decleor Aromessence Neroli Bigarade": "",
    "Decleor Aromessence Rose D'Orient Soothing comfort Oil Serum 15ml": "X",
    "Decleor Aromessence Lavandula Iris Rejuvenating Night Balm 15ml": "",
    "Decleor Aromessence Rose d'Orient Soothing comfort Night face Balm 15ml (Sensitive Skin)":
      "X",
    "Decleor Aromessence Mandarine Verte 15ml": "",
  },
];

(async function () {
  for (const field of data) {
    const products = Object.keys(field).filter(
      (name) => name !== "Key" && name !== "Value"
    );
    for (const product of products) {
      if (field[product].toLowerCase() === "x") {
        const id = await getProductIdByName(product).catch(console.log);
        if (!id || typeof id !== "number")
          return console.log("failed to fetch ID");
        const res = await applyFilter(id, field.Key, field.Value).catch((err) =>
          console.log(err.data.title)
        );
        console.log(
          `${field.Key}=${field.Value} was added to ${product}`,
          res || 422 // unprocessable entity
        );
      }
    }
  }
})();
