const { createRedirect } = require("../../functions/redirects/createRedirect");

require("../../config/config").config("ch");

const oldURLS = [
  "/ee/images/uploads/blog/beaulieuhouse-9.jpg",
  "/ee/images/uploads/blog/beaulieuhouse-25.jpg",
  "/ee/images/uploads/blog/Candleabra.jpg",
  "/ee/images/uploads/blog/Giant-Lego-optimised.jpg",
  "/ee/images/uploads/blog/newreseizedgames.jpg",
  "/ee/images/uploads/blog/Irish_Soaps.png",
  "/ee/images/uploads/blog/image006.jpg",
  "/ee/images/uploads/blog/plate1.jpg",
  "/ee/images/uploads/blog/ColouredGlass1.jpg",
  "/ee/images/uploads/blog/AMARYLLIS-winter-wedding-flower.jpg",
  "/ee/images/uploads/blog/ivycandle.jpg",
  "/ee/images/uploads/blog/Citadel-Inn_Catering2.jpg",
  "/ee/images/uploads/blog/inspo3.jpg",
  "/ee/images/uploads/blog/Personalised_Bottles_(8).png",
  "/ee/images/uploads/blog/xandos.jpg",
  "/ee/images/uploads/blog/inspo2.jpg",
  "/ee/images/uploads/blog/269-152180.jpg",
  "/ee/images/uploads/blog/Primary-Colours.jpg",
  "/ee/images/uploads/blog/survival_kit.png",
  "/ee/images/uploads/blog/White-pops.jpg",
  "/ee/images/uploads/blog/Roses---winter-wedding-flowers.jpg",
  "/ee/images/uploads/blog/vintagetablesetting.jpg",
  "/ee/images/uploads/blog/reusable_water.png",
  "/ee/images/uploads/blog/Halloween-Table-setting.jpg",
  "/ee/images/uploads/blog/plate3.jpg",
  "/ee/images/uploads/blog/photobooth_props_(2).png",
  "/ee/images/uploads/blog/inspo7.jpg",
  "/ee/images/uploads/blog/Rustic_Table.jpg",
  "/ee/images/uploads/blog/vintagebirdcagepinterest2.jpg",
  "/ee/images/uploads/blog/_main/Rustic_header.jpg",
  "/ee/images/uploads/blog/_main/Tara_Fay_Hero_Image.jpg",
  "/ee/images/uploads/blog/Med_Chicken.jpg",
  "/ee/images/uploads/blog/image001.jpg",
  "/ee/images/uploads/blog/Charger-Plates1.jpg",
  "/ee/images/uploads/blog/TIP_4_BBQ.jpg",
  "/ee/images/uploads/blog/lotto.png",
  "/ee/images/uploads/blog/goldcutleryandgoldrimmedglasses.jpg",
  "/ee/images/uploads/blog/Gardenia---winter-flowers-for-weddings.jpg",
  "/ee/images/uploads/blog/ColouredGlass3.jpg",
  "/ee/images/uploads/blog/BBQ_TIP_5.jpg",
  "/ee/images/uploads/blog/Standard_Chafer_2016.jpg",
  "/ee/images/uploads/blog/anemone-winter-flowers.jpg",
  "/ee/images/uploads/blog/inspo_6.jpg",
  "/ee/images/uploads/blog/15e7ff65171cc2973714b82b470fb357.jpg",
  "/ee/images/uploads/blog/idea-2.jpg",
  "/ee/images/uploads/blog/beaulieuhouse-30.jpg",
  "/ee/images/uploads/blog/Untitled.jpg",
  "/ee/images/uploads/blog/inspo1.jpg",
  "/ee/images/uploads/blog/Rustic_Chair_2x.jpg",
  "/ee/images/uploads/blog/beaulieuhouse-20.jpg",
  "/ee/images/uploads/blog/Idea-1._rustic_vibes.jpg",
  "/ee/images/uploads/blog/vintage-bird-cage-decor_(1)smaller.jpg",
  "/ee/images/uploads/blog/black-pumpkin-with-rhinestones.jpg",
  "/ee/images/uploads/blog/croquetset.jpg",
  "/ee/images/uploads/blog/inspo4.jpg",
  "/ee/images/uploads/blog/Capture.PNG",
  "/ee/images/uploads/blog/009-900x12002.jpg",
  "/ee/images/uploads/blog/BBQ_TIP_2.jpg",
  "/ee/images/uploads/blog/frenchboules.jpg",
  "/ee/images/uploads/blog/ccfd9a27d1f742fd017f962cf4661053.jpg",
  "/ee/images/uploads/blog/Carnation-winter-wedding-flowers.jpg",
  "/ee/images/uploads/blog/halloween-Table-Runner.jpg",
  "/ee/images/uploads/blog/2._Jams.png",
  "/ee/images/uploads/blog/Rustic_Chair_3x.jpg",
  "/ee/images/uploads/blog/inspo5.jpg",
  "/ee/images/uploads/blog/beaulieuhouse-3-thumb.jpg",
  "/ee/images/uploads/blog/skittlesset.jpg",
  "/ee/images/uploads/blog/ColouredGlass2.jpg",
  "/ee/images/uploads/blog/7c951db14b6ceafbb2bbd2254e5995bc--halloween-decorating-ideas-halloween-party-ideas.jpg",
  "/blog/2018/05/weddin-dress%20vintage",
  "/ee/images/uploads/blog/BBQ_TIP_3.jpg",
  "/ee/images/uploads/blog/idea-4.jpg",
  "/ee/images/uploads/blog/Babys-breath-winter-flower.jpg",
  "/ee/images/uploads/blog/_main/tara_fay.jpg",
  "/ee/images/uploads/blog/idea-5.jpg",
  "/ee/images/uploads/blog/giant_jenga.jpg",
  "/ee/images/uploads/blog/Wine-botlles.jpg",
  "/ee/images/uploads/blog/Rustic_Chair_1x.jpg",
  "/ee/images/uploads/blog/BBQ_TIP_1.jpg",
  "/ee/images/uploads/blog/Personalised_Bottles.png",
  "/ee/images/uploads/blog/Black-Crockery.jpg",
  "/ee/images/uploads/blog/269-152153.jpg",
  "/ee/images/uploads/blog/9Wicked-Feast-16.jpg",
  "/ee/images/uploads/blog/beaulieuhouse-32.jpg",
  "/ee/images/uploads/blog/_main/gamesblog1.jpg",
  "/ee/images/uploads/blog/idea-3.jpg",
  "/ee/images/uploads/blog/image003.jpg",
  "/ee/images/uploads/blog/Los-Angeles-copper-and-black-wedding-shoot-menu-on-place-setting.jpg",
  "/ee/images/uploads/blog/Ranunculus-winter-weedding-flowers.jpg",
  "/ee/images/uploads/blog/inspo6.jpg",
  "/ee/images/uploads/blog/plate2.jpg"
];

const newURL = `https://cdn11.bigcommerce.com/s-jqwssthhhd/images/stencil/960w/uploaded_images/12.jpg?t=1627549976`;

(async () => {
  for (const oldURL of oldURLS) {
    await createRedirect(oldURL, newURL).catch((err) => {
      throw new Error("Somethign went wrong");
    });
  }
  console.log("done")
})();
